### ISSUE TITLE
报警合并功能是否取消了

### ISSUE THREAD

**Issue by tonygshliu** [open-falcon/falcon-plus#112]
在说明文档里看到 Links是为报警合并功能写的组件。
但是遍寻也没找到这个组件。
请问是否集成到falcon-plus中了。

**Comment by YouZhengChuan** [comment]
好像是前端的组件，还是用"open-falcon"里面的，比如“dashboard”、“protal”、“query”等。

**Comment by laiwei** [comment]
0.2的文档还没有更新完成

告警合并仍然是支持的，只是links已经被集成在统一的dashboard中了

**Comment by tonygshliu** [comment]
thanks very much
