### ISSUE TITLE
grafana 不能显示出图 指标能读出来

### ISSUE THREAD

**Issue by tonygshliu** [open-falcon/falcon-plus#114]
<img width="1133" alt="2017-05-25 3 09 22" src="https://cloud.githubusercontent.com/assets/2952223/26439815/35abae4e-415c-11e7-9985-f238da3df51e.png">

指标名称能选出来，但是就是没有数据显示在上面的图上，请问这是什么原因啊。

**Comment by YouZhengChuan** [comment]
建议你执行下select语句，看看结果。

**Comment by masato25** [comment]
可以先将api module的 conf 设成 "db_bug": true & "log_level": "debug"
然后观测看看 debug log
