### ISSUE TITLE
设置agent的hostname，但是endpoint却有两个

### ISSUE THREAD

**Issue by chrisccnu** [open-falcon/falcon-plus#118]
![image](https://cloud.githubusercontent.com/assets/13851902/26516989/53059920-42c2-11e7-89d3-db88394c6570.png)
![image](https://cloud.githubusercontent.com/assets/13851902/26517008/88e18da6-42c2-11e7-8efb-aa1ed2bf57a3.png)

**Comment by laiwei** [comment]
@chrisccnu  是不是你没有设定agent的hostname之前，运行过agent？

**Comment by chrisccnu** [comment]
没有，感觉是部分指标还是取的hostname，如下图，主机名的endpoint只有部分指标，pm1的下面指标明显多很多，而且是不一样的，按我的理解如果我启动过，主机名的endpoint底下应该不止这几个指标的数据
![image](https://cloud.githubusercontent.com/assets/13851902/26612301/8355b908-45e6-11e7-9b40-5b50f0156ed9.png)

![image](https://cloud.githubusercontent.com/assets/13851902/26612362/d97efa56-45e6-11e7-9ea9-60981ec8372b.png)

**Comment by laiwei** [comment]
我看了下，这是agent 和 graph 同时部署在了同一台机器上。

- agent使用了agent cfg.json里面设置的hostname;
- graph使用了 https://github.com/niean/goperfcounter 这个自监控lib，这个自监控lib会上报模块自身的一些状态，而这个lib使用的是系统的hostname;
