### ISSUE TITLE
几处代码优化建议

### ISSUE THREAD

**Issue by rongyi** [open-falcon/falcon-plus#120]
$GOPATH/src/github.com/open-falcon/falcon-plus/g/tool.go:RmDup
$GOPATH/src/github.com/open-falcon/falcon-plus/vendor/github.com/toolkits/slice/unique.go:UniqueString
实现的是完全是相等的功能，有没有必要把这些都放在类库中呢?

$GOPATH/src/github.com/open-falcon/falcon-plus/common/utils/tags.go:SortedTags
$GOPATH/src/github.com/open-falcon/falcon-plus/common/utils/map.go:KeysOfMap
前一个函数中的实现完全可以调用后面这个函数，觉得没必要写重复代码

**Comment by laiwei** [comment]
可以提PR:)
