### ISSUE TITLE
在alarm配置了微信报警不起作用

### ISSUE THREAD

**Issue by tonygshliu** [open-falcon/falcon-plus#128]
在alarm配置文件中配置了 "im": "http://localhost:5000/wechat",
但是警报仍然只能通过sms和邮件发出，微信接口似乎并未被调用。

**Comment by laiwei** [comment]
更多信息？

**Comment by tonygshliu** [comment]
配置文件是这样的：
 "redis": {
        "addr": "127.0.0.1:6379",
        "maxIdle": 5,
        "highQueues": [
            "event:p0",
            "event:p1"
           
        ],
        "lowQueues": [
            "event:p2",
	    "event:p3",
            "event:p4",
            "event:p5",
            "event:p6"
        ],
        "userIMQueue": "/queue/user/im",
        "userSmsQueue": "/queue/user/sms",
        "userMailQueue": "/queue/user/mail"
    },
    "api": {
        "im": "http://127.0.0.1:5000/wechat",
        "sms": "http://127.0.0.1:5000/sms",
        "mail": "http://127.0.0.1:5000/mail",
        "dashboard": "http://127.0.0.1:8082",
        "plus_api":"http://127.0.0.1:8085",
        "plus_api_token": "default-token-used-in-server-side"
    },
    "falcon_portal": {
        "addr": "falcon_user:111111@tcp(127.0.0.1:3306)/alarms?charset=utf8&loc=Asia%2FChongqing",
        "idle": 10,
        "max": 100
    },
    "worker": {
        "im": 10,
        "sms": 10,
        "mail": 50
    },

alarm.log 中只有调用sms 和 mail接口的日志。
在dashboard界面 是应该填写用户的【 IM（内部通讯工具账号，比如百度hi、米聊）：】属性吗？

**Comment by XieXianbin** [comment]
:1234:

**Comment by laiwei** [comment]
在dashboard界面 是应该填写用户的【 IM（内部通讯工具账号，比如百度hi、米聊）：】属性吗？

------ 是的，必须在这里配置好你的个人微信号 @tonygshliu

**Comment by tonygshliu** [comment]
谢谢**@laiwei**
我确实配置好了微信号了，alarm 配置文件也配置好了，为什么不调用微信接口呢，难道还有别的地方需要配置？各个模块日志都看了，也没发现异常。

**Comment by laiwei** [comment]
你的告警策略可以贴出来看看吗？是不是你的策略级别为P2？ @tonygshliu

**Comment by tonygshliu** [comment]
是的，我的策略级别确实是P2

metric/tags [note]                                                                                  	condition	max	P	run
index.abs/module=cash,project=falcon [连续20分钟指标数据没有上传]	all(#20)==-1	6	2

**Comment by laiwei** [comment]
@tonygshliu 低优先级队列的报警，不会发送im。我做了修订，你可以试试了。

**Comment by sdvdxl** [comment]
@laiwei 我试了一下，p3及其以上还是不行

**Comment by tonygshliu** [comment]
现在可以发送成功了。谢谢。
