### ISSUE TITLE
sender是否可以引入对钉钉的报警支持

### ISSUE THREAD

**Issue by lyonliquid** [open-falcon/falcon-plus#134]
钉钉群聊机器人是一种比较方便的报警推送方式
只需要满足钉钉的消息json格式要求即可通过post到一个https的url的方式由钉钉的后台机器人推送报警
是否可以在sender中加入对dingtalk的支持

**Comment by sdvdxl** [comment]
可以用这个 https://github.com/sdvdxl/falcon-message

**Comment by masato25** [comment]
@sdvdxl 👍

**Comment by wenskys** [comment]
@lyonliquid 你可以自己封装个程序，将TM的传入数据封装成钉钉的，很简单的

**Comment by xiaoyang16889** [comment]
@benbenpi 钉钉报警解决了吗，求指导下
