### ISSUE TITLE
更换监控数据的存储后端

### ISSUE THREAD

**Issue by lwhile** [open-falcon/falcon-plus#135]
目前我们在用 InfluxDB 做监控系统的存储后端, 对 open-falcon  也在持续关注. 未来 open-falcon 是否有计划支持多种存储后端 ?

**Comment by ninjadq** [comment]
可否讨论一下，open falcon做时序数据数据存储和读取的时候抽象一个中间层，这样就可以方便做存储后端的转换，方便支持更多的存储后端，对于非主流的TSDB，也可以自己写一个接入层。现在支持Open TSDB的话，但是数据可以倒进去，如果看图的话，还是需要借助其他的工具，并没有发挥存储后端的作用，只是多了一个备份

**Comment by masato25** [comment]
之前有尝试引入 [fluentd](http://www.fluentd.org/), 让导出转送保持便利性 (它本身是一种资料转换格式输出的模组). 但是改动较大, 在加上需要另外维护一组fluentd cluster, 专案没有发展下去. 就测试所知 transfer 目前写法不适合写太多输出层, 测试后发现每多一种输入, transfer在内存及流量的压力会变大导自资料有机会无法正常送长. 如果 @lwhile 已经使用influxdb 作為存储后端 或许可以考虑 telegraf or  kapactor 等 influxdb 作為资料转送导出聚合处理方案.
