### ISSUE TITLE
Screen error 

### ISSUE THREAD

**Issue by zouyapeng** [open-falcon/falcon-plus#136]
![image](https://user-images.githubusercontent.com/10627855/27070895-71354f38-504d-11e7-90a6-af9f3ccde388.png)

**Comment by zouyapeng** [comment]
可能是 api 添加一个 url, 但是我 api 没有用最新的 /graph/endpointobj

**Comment by laiwei** [comment]
https://github.com/open-falcon/falcon-plus/commit/29f6b0046f8445ae6ad229d64b5c3b68747b7dda

配合这个API的改动一起用。
