### ISSUE TITLE
CentOS6.8启动后端一直卡在[falcon-nodata]

### ISSUE THREAD

**Issue by mojie126** [open-falcon/falcon-plus#138]
CentOS6.8启动后端一直卡在[falcon-nodata]，如何解决...？编译过程没出错...

**Comment by mojie126** [comment]
发现是aggregator组件启动不起来...

**Comment by mojie126** [comment]
搞定了，原来是MySQL设置了root密码...

**Comment by mojie126** [comment]
自己来备忘下...
sed -i 's/root:/username:password/g' `find . -name cfg.json`

**Comment by w675881684** [comment]
老哥，稳！
