### ISSUE TITLE
升级问题: 0.1的agent 兼容 0.2的后端

### ISSUE THREAD

**Issue by 527593036** [open-falcon/falcon-plus#139]
请问，部署了大量0.1版本的agent, 要升级到0.2版本需要一个较长的时间，能否先升级中心的transfer，graph等组件？能兼容0.1的agent？

**Comment by liangyanbina** [comment]
使用0.1的agent往0.2的transfer传数据功能都是正常的。

**Comment by 527593036** [comment]
非常感谢，@liangyanbina
