### ISSUE TITLE
编译安装时一直出现如下错误

### ISSUE THREAD

**Issue by victorywang80** [open-falcon/falcon-plus#142]
# my/falcon-plus-0.2.0/modules/api
modules/api/main.go:77: cannot use routes (type *"my/falcon-plus-0.2.0/vendor/github.com/gin-gonic/gin".Engine) as type *"github.com/open-falcon/falcon-plus/vendor/github.com/gin-gonic/gin".Engine in argument to controller.StartGin
Makefile:48: recipe for target 'api' failed
make: *** [api] Error 2

环境：
ubuntu server 16.04
go version go1.6.2 linux/amd64

**Comment by masato25** [comment]
@victorywang80  刚刚找一个干净的环境测试过, 看起来是正常的

环境:
go version go1.8.1 linux/amd64
Linux version 4.4.5-1-ARCH

可否请你升级go版本 或是 清空再试看看呢？
谢谢

**Comment by liangyanbina** [comment]
@victorywang80 编译api时报错，你是怎么解决的？

**Comment by masato25** [comment]
可以请你们尝试看看以下的步骤吗？
0. install golang
1. export GOPATH=~/Dev/go
2. go get github.com/open-falcon/falcon-plus
3. cd $GOPATH/src/github.com/open-falcon/falcon-plus
4. make all
