### ISSUE TITLE
config/confgen.sh 使用了 bash version 4 才有的 declare 語法: declare -A

### ISSUE THREAD

**Issue by humorless** [open-falcon/falcon-plus#145]
config/confgen.sh 使用了 bash version 4 才有的 declare 語法: `declare -A`
在 bash 版本比較低的系統會灌不起來。
建議：改用 bash 3 就相容的寫法，或是script 自動偵測 bash 版本，不是 version 4 的話，就噴錯誤。

[參考資料](https://stackoverflow.com/questions/6047648/bash-4-associative-arrays-error-declare-a-invalid-option)

**Comment by masato25** [comment]
@humorless  PR welcome, plz :)
