### ISSUE TITLE
plus agent问题

### ISSUE THREAD

**Issue by Aikc** [open-falcon/falcon-plus#147]

**Comment by Aikc** [comment]
1、plus将很多模块集成在一起那么在单纯部署agent，这样会把其他模块引入。感觉没有必要
2、关于agent升级问题，如果是要监控mysql ，如何快速升级

**Comment by laiwei** [comment]
plus-agent 作为独立的binary，仍然可以单独部署，没有影响。集成到falcon-plus下面主要是为了方便代码开发和协作。
