### ISSUE TITLE
关于绘图组件时区的问题

### ISSUE THREAD

**Issue by Vortexxxx** [open-falcon/falcon-plus#153]
新开了一台国外的服务器部署open-falcon，忘记调整时区，后来看图的时候才发现走的是-0800时间

调整时区重启服务器并重启open-falcone服务，观察一段时间的发现绘图出来的时间还是按-0800时间

在配置项中也没有找到相关的配置，请问应该如何将绘图的时区调整到正确的呢

![image](https://user-images.githubusercontent.com/29770643/27768395-178f1af2-5f45-11e7-91f2-5b0176ff93fc.png)

截图时间为北京时间7月2日16：30左右

**Comment by Vortexxxx** [comment]
更正一下

我查了一下-0800的时间也对不上，所以我也不知道这个是哪个地区的时间了

收集上来的数据都是时间戳，所以问题应该调整为dashboard这个绘图组件绘图时的时间是跟据什么设置来的？

**Comment by masato25** [comment]
你这个看起来像 显示的像是utc time, 只是比较怪异的是好像差距了30分钟,  后端存储的时间的依据是 unix timestamp 所以不会有时区的问题. 前端页面显示的部份看是一律显示utc  或是根据浏览器的时区显示做切换.

**Comment by Vortexxxx** [comment]
原来是这样，搞清楚了，确实是跟据浏览器时间来切换的，我把我的代理去掉之后， 显示就正常了，感谢
