### ISSUE TITLE
task模块出现 get statistics error, invalid character 'p' after top-level value

### ISSUE THREAD

**Issue by fengjian1585** [open-falcon/falcon-plus#156]
openfalcon 0.2    task 模块出现 get statistics error, invalid character 'p' after top-level value， 0.1中正常、

[root@openfalcon_alarm_sender task]# cat cfg.json
{
    "debug": false,
    "http": {
        "enable": true,
        "listen": "0.0.0.0:8002"
    },
    "index": {
        "enable": true,
        "dsn": "openfalcon:senyint.rh@tcp(172.16.230.188:3306)/graph?loc=Local&parseTime=true",
        "maxIdle": 4,
        "autoDelete": true,
        "cluster":{
            "openfalcon_judge1:6071" : "0 0 0 ? * 0-5",
            "openfalcon_judge2:6071" : "0 30 0 ? * 0-5"
        }
    },
    "collector" : {
        "enable": true,
        "destUrl" : "http://127.0.0.1:1988/v1/push",
        "srcUrlFmt" : "http://%s/statistics/all",
        "cluster" : [
            "transfer1,openfalcon_transfer1:6060",
            "transfer2,openfalcon_transfer2:6060",
            "graph1,openfalcon_graph1:6071",
            "graph2,openfalcon_graph2:6071",
            "task,openfalcon_alarm_sender:8002"
        ]
    }

#############################################
报错信息如下：

2017/07/03 13:45:00 collector.go:56: collect, start 2017-07-03 13:45:00, ts 0s
2017/07/03 13:46:00 collector.go:104: openfalcon_graph1:6071, get statistics error, invalid character 'p' after top-level value
2017/07/03 13:46:00 collector.go:104: openfalcon_graph2:6071, get statistics error, invalid character 'p' after top-level value
2017/07/03 13:46:00 collector.go:56: collect, start 2017-07-03 13:46:00, ts 0s
2017/07/03 13:47:00 collector.go:104: openfalcon_graph1:6071, get statistics error, invalid character 'p' after top-level value
2017/07/03 13:47:00 collector.go:104: openfalcon_graph2:6071, get statistics error, invalid character 'p' after top-level value
2017/07/03 13:47:00 collector.go:56: collect, start 2017-07-03 13:47:00, ts 0s
2017/07/03 13:48:00 collector.go:104: openfalcon_graph1:6071, get statistics error, invalid character 'p' after top-level value
2017/07/03 13:48:00 collector.go:104: openfalcon_graph2:6071, get statistics error, invalid character 'p' after top-level value
2017/07/03 13:48:00 collector.go:56: collect, start 2017-07-03 13:48:00, ts 0s
2017/07/03 13:49:00 collector.go:104: openfalcon_graph1:6071, get statistics error, invalid character 'p' after top-level value
2017/07/03 13:49:00 collector.go:104: openfalcon_graph2:6071, get statistics error, invalid character 'p' after top-level value
2017/07/03 13:49:00 collector.go:56: collect, start 2017-07-03 13:49:00, ts 0s
2017/07/03 13:50:00 collector.go:104: openfalcon_graph1:6071, get statistics error, invalid character 'p' after top-level value
2017/07/03 13:50:00 collector.go:104: openfalcon_graph2:6071, get statistics error, invalid character 'p' after top-level value
2017/07/03 13:50:00 collector.go:56: collect, start 2017-07-03 13:50:00, ts 0s
2017/07/03 13:51:00 collector.go:104: openfalcon_graph1:6071, get statistics error, invalid character 'p' after top-level value
2017/07/03 13:51:00 collector.go:104: openfalcon_graph2:6071, get statistics error, invalid character 'p' after top-level value
2017/07/03 13:51:00 collector.go:56: collect, start 2017-07-03 13:51:00, ts 0s
2017/07/03 13:52:00 collector.go:104: openfalcon_graph1:6071, get statistics error, invalid character 'p' after top-level value
2017/07/03 13:52:00 collector.go:104: openfalcon_graph2:6071, get statistics error, invalid character 'p' after top-level value

**Comment by liangyanbina** [comment]
1、由于graph统计数据接口路径与之前的不一样（graph_host:6071/couter/all）
2、graph v0.2接口返回的json格式与之前的也有差异导致task模板解析json失败。
我是自己写脚本获取数据，通过agent post上去。

**Comment by laiwei** [comment]
fixed https://github.com/open-falcon/falcon-plus/pull/187
