### ISSUE TITLE
no 8433 port expose and can't find agent using docker

### ISSUE THREAD

**Issue by billmoling** [open-falcon/falcon-plus#159]
I am following the docker command to use 
docker run -itd -p 8081:8081 openfalcon/falcon-plus:0.2.0 bash /run.sh hbs
to have a running open-falcon container.
I also follow the book to set up the agent on my docker host machine. I checked the log, it reports the 8433 connection refused.

I am a little confused, if the falcon-plus include "transfer"? do I need to set another transfer instance?

then even the heartbeats is not reporting error, on falcon-dashboard, there is nothing.no any server on it

**Comment by hitripod** [comment]
The docker image is a single instance for demo purpose only. Hence, only the port used by dashboard should be exposed.
