### ISSUE TITLE
由于git文件修改，安装文档需要修正

### ISSUE THREAD

**Issue by fxdjjn1234** [open-falcon/falcon-plus#160]
在安装环境变量时，由于/falcon-plus/scripts/mysql/db_schema/下面的文件不是命名为uic-db-schema.sql而是1_uic-db-schema.sql，脚本需要修改如下：

mysql -h 127.0.0.1 -u root -p < 1_uic-db-schema.sql
mysql -h 127.0.0.1 -u root -p < 2_portal-db-schema.sql
mysql -h 127.0.0.1 -u root -p < 4_graph-db-schema.sql
mysql -h 127.0.0.1 -u root -p < 3_dashboard-db-schema.sql
mysql -h 127.0.0.1 -u root -p < 5_alarms-db-schema.sql

**Comment by laiwei** [comment]
https://github.com/open-falcon/falcon-plus/pull/164/
