### ISSUE TITLE
nginx 是否 可以反向代理  transfer， heartbeat 模块？

### ISSUE THREAD

**Issue by sam2099** [open-falcon/falcon-plus#163]
Hello：

我的监控服务只有一个外网端口， 所有请求都是通过nginx 反向代理的；
是否可以用nginx 是否 可以反向代理  transfer， heartbeat 模块？

谢谢

**Comment by laiwei** [comment]
不能用作transfer、heartbeat的反向代理，因为并不是http协议。

**Comment by sam2099** [comment]
谢谢。
是go里面的rpc调用？ tcp协议？

**Comment by laiwei** [comment]
@sam2099 jsonrpc
