### ISSUE TITLE
部署过程中关于aggregator的2个问题

### ISSUE THREAD

**Issue by ccbwarlock** [open-falcon/falcon-plus#166]
环境CENTOS7，go=1.6.3，git=1.8.3.1，GOROOT指向GO安装路径，GOPATH指向另外的目录

1.根据部署手册到了Compilation中的make all时，报“make: *** [aggregator] 错误 1”
![tim 20170714110128](https://user-images.githubusercontent.com/30166243/28196534-dbef742c-6883-11e7-9406-a2f6c580e9b6.png)

2.根据https://book.open-falcon.org/zh_0_2/中提供的编译包，可以跳过问题1继续下去，在启用所有后端组件时，aggregator等了较长时间无法启动（其他业务单个都能启动）

**Comment by laiwei** [comment]
1. 需要在gopath下才能 make all
2. aggregator无法启动成功，一般是因为aggregator配置文件中数据库地址和信息没有配置正确

**Comment by ccbwarlock** [comment]
非常感谢，经过你的提示，“aggregator无法启动成功”的问题解决了（因为我习惯性部署mysql后就更新root密码导致）。

第一个问题make的时候还是报错，目录是已经切到了$GOPATH/src/github.com/open-falcon/falcon-plus/（GOPATH我配置为/home/gopath）。我最后还是使用官方教程里的编译包完成的部署

**Comment by laiwei** [comment]
@ccbwarlock
