### ISSUE TITLE
agent 在centos5.4部署启动后出现core

### ISSUE THREAD

**Issue by zhxd163** [open-falcon/falcon-plus#167]
2017/07/14 15:25:45 var.go:95: <= <Total=63, Invalid:0, Latency=0ms, Message:ok>
2017/07/14 15:25:45 plugin.go:64: <Plugins:[], Timestamp:1500017145>
2017/07/14 15:25:47 portstat.go:22: signal: segmentation fault (core dumped)

gdb falcon-agent core.4634 
GNU gdb Fedora (6.8-37.el5)
Copyright (C) 2008 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu"...

warning: Loadable segment ".tbss" outside of ELF segments

warning: core file may not match specified executable file.
Cannot access memory at address 0x797469726f697258
(gdb) bt
#0  0x0000003f0fa63696 in ?? ()
#1  0x0000000000000000 in ?? ()
(gdb) quit

gdb core.4634 
GNU gdb Fedora (6.8-37.el5)
Copyright (C) 2008 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu"...
"/data1/falcon-agent/core.4634": not in executable format: File format not recognized
(gdb) bt
No stack.
(gdb)

**Comment by laiwei** [comment]
如果你希望在centos5.x系列上运行，那么就需要从源码在centos5.x上编译。

官方主页下载的二进制是在 centos6上编译的。

**Comment by zhxd163** [comment]
在5.4编译完，报错一样的啊。。。

**Comment by shaohua-zhangmr** [comment]
GNU gdb (GDB) Red Hat Enterprise Linux (7.0.1-32.el5)
Copyright (C) 2009 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /app/falcon/open-falcon...
warning: Loadable segment ".tbss" outside of ELF segments
done.
Reading symbols from /lib64/libpthread.so.0...(no debugging symbols found)...done.
Loaded symbols for /lib64/libpthread.so.0
Reading symbols from /lib64/libc.so.6...(no debugging symbols found)...done.
Loaded symbols for /lib64/libc.so.6
Reading symbols from /lib64/ld-linux-x86-64.so.2...(no debugging symbols found)...done.
Loaded symbols for /lib64/ld-linux-x86-64.so.2

warning: no loadable sections found in added symbol-file system-supplied DSO at 0x7fff9cdd4000
Core was generated by `./open-falcon start falcon-sre'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007fff9cdd4767 in ?? ()
(gdb) bt
#0  0x00007fff9cdd4767 in ?? ()
#1  0x0000000000457156 in runtime.nanotime () at /usr/lib/golang/src/runtime/sys_linux_amd64.s:175
#2  0x0000000000420344 in runtime.(*mheap).freeSpanLocked (h=0x676a60, s=0x2b5b03134000, acctinuse=false, acctidle=true, unusedsince=0) at /usr/lib/golang/src/runtime/mheap.go:851
#3  0x000000000041fc23 in runtime.(*mheap).grow (h=0x676a60, npage=1, ~r1=false) at /usr/lib/golang/src/runtime/mheap.go:749
#4  0x000000000041f8c2 in runtime.(*mheap).allocSpanLocked (h=0x676a60, npage=1, ~r1=0x0) at /usr/lib/golang/src/runtime/mheap.go:630
#5  0x000000000041ef90 in runtime.(*mheap).alloc_m (h=0x676a60, npage=1, sizeclass=22, large=false, ~r3=0x0) at /usr/lib/golang/src/runtime/mheap.go:515
#6  0x000000000044d2ab in runtime.(*mheap).alloc.func1 () at /usr/lib/golang/src/runtime/mheap.go:579
#7  0x000000000045354b in runtime.systemstack () at /usr/lib/golang/src/runtime/asm_amd64.s:314
#8  0x000000000041f273 in runtime.(*mheap).alloc (h=0x676a60, npage=1, sizeclass=22, large=false, needzero=true, ~r4=0x40d1d9) at /usr/lib/golang/src/runtime/mheap.go:580
#9  0x00000000004130d4 in runtime.(*mcentral).grow (c=0x6786d0, ~r0=0x0) at /usr/lib/golang/src/runtime/mcentral.go:210
#10 0x00000000004129aa in runtime.(*mcentral).cacheSpan (c=0x6786d0, ~r0=0x413446) at /usr/lib/golang/src/runtime/mcentral.go:91
#11 0x000000000041270e in runtime.(*mcache).refill (c=0x2b5b03130000, sizeclass=22, ~r1=0x68f400) at /usr/lib/golang/src/runtime/mcache.go:121
#12 0x000000000044c033 in runtime.(*mcache).nextFree.func1 () at /usr/lib/golang/src/runtime/malloc.go:505
#13 0x000000000045354b in runtime.systemstack () at /usr/lib/golang/src/runtime/asm_amd64.s:314
#14 0x000000000040e1b2 in runtime.(*mcache).nextFree (c=0x2b5b03130000, sizeclass=22 '\026', v=47669893595136, s=0x44c0d0, shouldhelpgc=248) at /usr/lib/golang/src/runtime/malloc.go:506
#15 0x000000000040eb89 in runtime.mallocgc (size=416, typ=0x5952c0, needzero=true, ~r3=0x2b5b03130000) at /usr/lib/golang/src/runtime/malloc.go:658
#16 0x000000000040ef08 in runtime.newobject (typ=0x5952c0, ~r1=0x654c78) at /usr/lib/golang/src/runtime/malloc.go:785
#17 0x00000000004302c1 in runtime.malg (stacksize=32768, ~r1=0x27100055a6e0) at /usr/lib/golang/src/runtime/proc.go:2688
#18 0x00000000004253bd in runtime.mpreinit (mp=0x673ee0) at /usr/lib/golang/src/runtime/os_linux.go:261
#19 0x000000000042a853 in runtime.mcommoninit (mp=0x673ee0) at /usr/lib/golang/src/runtime/proc.go:507
#20 0x000000000042a3bf in runtime.schedinit () at /usr/lib/golang/src/runtime/proc.go:441
#21 0x000000000045330f in runtime.rt0_go () at /usr/lib/golang/src/runtime/asm_amd64.s:145
#22 0x0000000000000003 in ?? ()
#23 0x00007fff9cc8b5c8 in ?? ()
#24 0x0000000000000003 in ?? ()
#25 0x00007fff9cc8b5c8 in ?? ()
#26 0x0000000000000000 in ?? ()
(gdb) q
我也碰到同样的问题，有什么办法解决吗？

**Comment by shaohua-zhangmr** [comment]
参考网址：https://dave.cheney.net/2013/06/18/how-to-install-go-1-1-on-centos-5
原因：我在安装过程中发现好多centos5的版本都运行正常，只有一台报这个错，而且报错这台（kernel-2.6.18-164.el5.x86_64）版本还比别的centos内核版本高一些，其他centos5版本都能正常运行，最后google发现了一句这个话，说是有些centos版本不支持vDSO support导致的Segmentation Fault，从gdb调试信息也能看出来一些：warning: no loadable sections found in added symbol-file system-supplied DSO at 0x7fff9cdd4000！
解决办法：升级kernel版本，我升级到kernel-2.6.18-308.el5，启动正常！

Segfaults and crashes due to missing vDSO support
A some point during the RHEL5 release cycle support for vDSO vsyscalls was added to RedHat’s 2.6.18 kernel. However that point appears to differ by point release. For example, for RedHat 5, kernel 2.6.18-238.el5 does not work, whereas 2.6.18-238.19.1.el5 does. Running CentOS 5.9 with kernel 2.6.18.348.el5 does work.
