### ISSUE TITLE
make all  报错啊~

### ISSUE THREAD

**Issue by zhangkaka** [open-falcon/falcon-plus#169]
[root@CentOS68 falcon-plus]# make all
go build -o bin/agent/falcon-agent ./modules/agent
go build -o bin/aggregator/falcon-aggregator ./modules/aggregator
go build -o bin/graph/falcon-graph ./modules/graph
modules/graph/rrdtool/rrdtool.go:11:2: cannot find package "github.com/open-falcon/rrdlite" in any of:
	/app/go/src/github.com/open-falcon/falcon-plus/vendor/github.com/open-falcon/rrdlite (vendor tree)
	/app/go/src/vendor/github.com/open-falcon/rrdlite
	/app/go/src/github.com/open-falcon/rrdlite (from $GOROOT)
	/app/go/bin/src/github.com/open-falcon/rrdlite (from $GOPATH)
make: *** [graph] Error 1

**Comment by xiaomige** [comment]
同问

**Comment by zhxd163** [comment]
同问

**Comment by zhangkaka** [comment]
https://github.com/open-falcon/rrdlite
把这个git拉到open-falcon报错的目录下面/app/go/src/github.com/open-falcon/falcon-plus/vendor/github.com/open-falcon/rrdlite，就可以了,我测试通过，应该是作者，忘了放了！

**Comment by taomaree** [comment]
go get -u -v github.com/open-falcon/rrdlite
