### ISSUE TITLE
cannot find package "github.com/open-falcon/rrdlite"

### ISSUE THREAD

**Issue by hisensehanjie** [open-falcon/falcon-plus#170]
其他模块执行make都没问题，只有graph模块，找不到rrdlite包，错误提示：
make graph
go build -o bin/graph/falcon-graph ./modules/graph
modules/graph/rrdtool/rrdtool.go:11:2: cannot find package "github.com/open-falcon/rrdlite" in any of:
	/root/gopath/src/github.com/open-falcon/falcon-plus/vendor/github.com/open-falcon/rrdlite (vendor tree)
	/root/go/src/github.com/open-falcon/rrdlite (from $GOROOT)
	/root/gopath/src/github.com/open-falcon/rrdlite (from $GOPATH)
make: *** [graph] Error 1

**Comment by laiwei** [comment]
https://github.com/open-falcon/falcon-plus/issues/169
