### ISSUE TITLE
gateway 模式下 agent的  heartbeat 如何配置

### ISSUE THREAD

**Issue by kxst** [open-falcon/falcon-plus#178]
是不是 gateway 组件，每个机房只需要部署一个，然后给机房下的所有 agent 将数据发送到 gateway 组件，然后gateway 在转发到统一的transfer 里？ 请问这种情况下 agent 的  heartbeat ip 应该怎样配置呢？谢谢

**Comment by qlyzpqz** [comment]
有个hbs-proxy可以做代理的，用tcp代理在中间中转一下也行

**Comment by kxst** [comment]
谢谢
