### ISSUE TITLE
修改主机名后，无法出图

### ISSUE THREAD

**Issue by kxst** [open-falcon/falcon-plus#179]
请问，我修改了主机名后（shell 执行了 hostname=xxx），前端就不出图了。graph 库下的 endpoint、endpoint_counter、tag_endpoint 表，都已经有新的主机了，可是前端不出图。谢谢

**Comment by hitripod** [comment]
可以补充更多详细的资讯吗？例如数据表与更改前后的主机名

**Comment by trunks023** [comment]
1.delete the endpoint whtich name has been changed from the dashboard
2.execute "http://127.0.0.1:6071/index/updateAll" in the brower
may be help.
