### ISSUE TITLE
open-falcon over wan

### ISSUE THREAD

**Issue by DR3EVR8u8c** [open-falcon/falcon-plus#180]
Hi,
Thanks for the excellent work! However, I am just wondering how to set up the open-falcon over WAN link with http, https or ssh port only.

My company has machine rooms all around the earth and we have very restricted firewall rules to secure our network. Is it possibile use tunnel or proxy for all comunications, such as http, https or ssh?

I have gone through your docunmentation, the gateway component seems the most closed solution. But, I am not quite understand how to configure it for that purpose. 

Initially, what I assume the architecture is like that:
remote area     ----------    central monitoring
agent   -------http,https,ssh--> gateway ---normal---> central open-falcon server

Therefore, I am a bit shocked when I notice that 4 services, http, rpc, socket and transfer, need to be configured in gateway config.

Please explain how to set up open-falcon over WAN link or refer me to an appropriated document.
Thanks and regards,

**Comment by hitripod** [comment]
check this: https://github.com/open-falcon/falcon-plus/blob/master/modules/gateway/README.md
