### ISSUE TITLE
graph进程异常退出

### ISSUE THREAD

**Issue by kkkkk1530** [open-falcon/falcon-plus#181]
goroutine 107893504 [select, 2 minutes]:
net/http.(*persistConn).writeLoop(0xc42d3cc7e0)
        /home/falcon/go/src/net/http/transport.go:1704 +0x43a
created by net/http.(*Transport).dialConn
        /home/falcon/go/src/net/http/transport.go:1118 +0xa5a

goroutine 3946987 [IO wait]:
net.runtime_pollWait(0x7f35b039ec98, 0x72, 0x1d)
        /home/falcon/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc420129098, 0x72, 0xdc92c0, 0xdc4e28)
        /home/falcon/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc420129098, 0xc434804000, 0x1000)
        /home/falcon/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).Read(0xc420129030, 0xc434804000, 0x1000, 0x1000, 0x0, 0xdc92c0, 0xdc4e28)
        /home/falcon/go/src/net/fd_unix.go:250 +0x1b7
net.(*conn).Read(0xc4201e0318, 0xc434804000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /home/falcon/go/src/net/net.go:181 +0x70
bufio.(*Reader).Read(0xc436b2c540, 0xc420e51420, 0x1, 0x9, 0xc43db96d80, 0x199, 0x199)
        /home/falcon/go/src/bufio/bufio.go:213 +0x312
io.ReadAtLeast(0xdc6600, 0xc436b2c540, 0xc420e51420, 0x1, 0x9, 0x1, 0xc4387dcac8, 0x42e326, 0xc4365fca00)
        /home/falcon/go/src/io/io.go:307 +0xa9
io.ReadFull(0xdc6600, 0xc436b2c540, 0xc420e51420, 0x1, 0x9, 0x42e326, 0x3, 0x10)
        /home/falcon/go/src/io/io.go:325 +0x58
encoding/gob.decodeUintReader(0xdc6600, 0xc436b2c540, 0xc420e51420, 0x9, 0x9, 0xc4387dcb10, 0x42dc5e, 0xc400000008, 0xc436b2f2c0)
        /home/falcon/go/src/encoding/gob/decode.go:119 +0x63
encoding/gob.(*Decoder).recvMessage(0xc424805b00, 0xc4387dcb20)
        /home/falcon/go/src/encoding/gob/decoder.go:76 +0x57
encoding/gob.(*Decoder).decodeTypeSequence(0xc424805b00, 0x998200, 0xc424805b00)
        /home/falcon/go/src/encoding/gob/decoder.go:140 +0x167
encoding/gob.(*Decoder).DecodeValue(0xc424805b00, 0x8af520, 0xc42adb2260, 0x16, 0x0, 0x0)
        /home/falcon/go/src/encoding/gob/decoder.go:208 +0xe8
encoding/gob.(*Decoder).Decode(0xc424805b00, 0x8af520, 0xc42adb2260, 0x0, 0xc420164e20)
        /home/falcon/go/src/encoding/gob/decoder.go:185 +0x16d
net/rpc.(*gobServerCodec).ReadRequestHeader(0xc423150f00, 0xc42adb2260, 0x8b5840, 0xc4365fca00)
        /home/falcon/go/src/net/rpc/server.go:407 +0x45
net/rpc.(*Server).readRequestHeader(0xc420164e00, 0xdcd480, 0xc423150f00, 0xc43f8758a0, 0x16, 0x197, 0x94af01, 0x0, 0x0)
        /home/falcon/go/src/net/rpc/server.go:580 +0x6c
net/rpc.(*Server).readRequest(0xc420164e00, 0xdcd480, 0xc423150f00, 0xc420164e00, 0xc420e51440, 0xc420250700, 0xc4310ed560, 0x8b5840, 0xc4365fca00, 0x197, ...)
        /home/falcon/go/src/net/rpc/server.go:547 +0x5a
net/rpc.(*Server).ServeCodec(0xc420164e00, 0xdcd480, 0xc423150f00)
        /home/falcon/go/src/net/rpc/server.go:466 +0x77
net/rpc.(*Server).ServeConn(0xc420164e00, 0x7f35babb3000, 0xc4201e0318)
        /home/falcon/go/src/net/rpc/server.go:458 +0x373
net/rpc.ServeConn(0x7f35babb3000, 0xc4201e0318)
        /home/falcon/go/src/net/rpc/server.go:663 +0x41
github.com/open-falcon/falcon-plus/modules/graph/api.Start.func1.1(0xdcf960, 0xc4201e0318)
        /home/falcon/gopath/src/github.com/open-falcon/falcon-plus/modules/graph/api/rpc.go:79 +0xb3
created by github.com/open-falcon/falcon-plus/modules/graph/api.Start.func1
        /home/falcon/gopath/src/github.com/open-falcon/falcon-plus/modules/graph/api/rpc.go:80 +0xa6

以上是日志graph日志内容，这个问题在v0.1.0也出现过一次。

**Comment by hitripod** [comment]
资讯不足无法判断
