### ISSUE TITLE
Install falcon-plus from docker error

### ISSUE THREAD

**Issue by IamBusy** [open-falcon/falcon-plus#188]
I followed the [guideline](https://github.com/open-falcon/falcon-plus/blob/master/docker/README.md) to install falcon-plus by docker.

> docker pull openfalcon/falcon-plus:0.2.0
docker run -itd -p 8081:8081 openfalcon/falcon-plus:0.2.0 bash /run.sh hbs

 However it failded, and got the `ERROR`:

> /usr/bin/docker-current: Error response from daemon: driver failed programming external connectivity on endpoint serene_ptolemy (ecebb819c2de6e0057d6bdaedc1123673b99fe8834937ebb0d805415e8e7888a): iptables failed: iptables --wait -t filter -A DOCKER ! -i docker0 -o docker0 -p tcp -d 172.17.0.6 --dport 8081 -j ACCEPT: iptables: No chain/target/match by that name.
 (exit status 1).

And here is some info:

> ➜  docker git:(master) cat /proc/version
Linux version 3.10.0-514.6.2.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ) #1 SMP Thu Feb 23 03:04:39 UTC 2017
➜  docker git:(master) lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.2.1511 (Core)
Release:	7.2.1511
Codename:	Core
➜  docker git:(master) docker -v
Docker version 1.12.6, build 88a4867/1.12.6

**Comment by hitripod** [comment]
The error message is not related to Falcon-Plus.

> iptables failed: iptables --wait -t filter -A DOCKER ! -i docker0 -o docker0 -p tcp -d 172.17.0.6 --dport 8081 -j ACCEPT: iptables: No chain/target/match by that name.
