### ISSUE TITLE
graph定时更新unIndexedItemCache，没有写入数据库

### ISSUE THREAD

**Issue by abjackjay** [open-falcon/falcon-plus#189]
新装的环境，经常会出现有些endpoint或者counter没写入mysql数据库的情况，或者endpoint下的counter不全，但是该counter对应的rrd文件已经生成，IndexUpdateAllErrorCnt计数为0，graph的log也没报错，把rrd文件删除重启进程也不行，只有/index/updateAll全量更新才能解决问题，怀疑问题出在定时更新unIndexedItemCache的数据到mysql的过程中，但是graph的log也没打印写数据库有问题（graph的debug是关的）。

**Comment by hitripod** [comment]
更新之后还会出现这问题吗？频率？

> 只有/index/updateAll全量更新才能解决问题

**Comment by abjackjay** [comment]
全量更新后就没这个问题了，主要是刚安装完后会出现这个问题

**Comment by hitripod** [comment]
可能是数据库有变动，参考 [Book](https://book.open-falcon.org/zh_0_2/faq/graph.html)

> 手动更改graph的数据库后，可能会出现上述情况。

**Comment by abjackjay** [comment]
安装过程中就修改过一次mysql数据库的初始配置，没修改后数据库里面的内容，对比了一下官方文档，感觉跟我们的情况不一样
