### ISSUE TITLE
用grafana的singlestat来展示部分监控数据出现问题

### ISSUE THREAD

**Issue by pangyana** [open-falcon/falcon-plus#190]
grafana配了0.2的api url，
<img width="732" alt="datasource" src="https://user-images.githubusercontent.com/16829933/28657849-663d674a-72db-11e7-8413-573b89a5e52f.png">

在用grafana的singlestat面板时，数据展示有问题。
<img width="1077" alt="singlestat" src="https://user-images.githubusercontent.com/16829933/28657893-8f5d2d0e-72db-11e7-87b5-580158f49292.png">

查看api调用的日志，发现里面查数据库用的是正则，

<img width="1034" alt="log" src="https://user-images.githubusercontent.com/16829933/28658039-11440d06-72dc-11e7-8258-cc1da7c44542.png">

例如'mem.memused'这个指标，用正则查的话，就会把mem.memused.percent也查出来
<img width="876" alt="query" src="https://user-images.githubusercontent.com/16829933/28658048-17e19c14-72dc-11e7-8c5e-a099b450c949.png">

grafana singlestat面板报错如下:
<img width="735" alt="r1" src="https://user-images.githubusercontent.com/16829933/28658152-873031e8-72dc-11e7-803f-601aa44f9f45.png">
<img width="682" alt="r2" src="https://user-images.githubusercontent.com/16829933/28658165-9060d16e-72dc-11e7-922d-2463814defc8.png">

**Comment by kasimi-rin** [comment]
grafana的singlestat里配置的时候写成memused$(最后加一个“$”符号)，表示匹配终止，memused.percent就不会查出来了。 @pangyana

**Comment by pangyana** [comment]
恩，谢谢，加$可以 @kasimi-rin ，那得一个个改过来的。好像0.1 都不支持 末尾加$的。
另外还有一个问题，不知道是什么原因0.1可以，0.2不可以出不来数据，如下
<img width="1242" alt="q1" src="https://user-images.githubusercontent.com/16829933/28665582-a59ade5c-72f6-11e7-9ca6-df07f20f0729.png">
<img width="1242" alt="q2" src="https://user-images.githubusercontent.com/16829933/28665597-b2d9185e-72f6-11e7-98ca-ab82be2508cd.png">

**Comment by pangyana** [comment]
看上去像是多个系列数据，只要其中一个没有数据，就会显示不出来
<img width="1252" alt="q3" src="https://user-images.githubusercontent.com/16829933/28666194-f5a46c5e-72f8-11e7-8141-2c781b67d94a.png">

**Comment by kasimi-rin** [comment]
这个倒是没遇到过，有时候我的grafana不显示图，刷新一下就好了。

**Comment by pangyana** [comment]
@hitripod

**Comment by masato25** [comment]
剛測試過了,有一個找不到的指標也不會畫不出圖:
![check_grafana](https://user-images.githubusercontent.com/4387822/28812592-00404f02-76c8-11e7-971b-f40b81d77d52.png)
猜測是數據庫有找到這個metric但是返回結果的數據有問題 (ex. values 為 []), 如果可以去除敏感資料提供返回結果樣本, 可以幫助我們這邊除錯 謝謝.
![debug_info](https://user-images.githubusercontent.com/4387822/28812594-039ed22c-76c8-11e7-9bb1-af81cf9947d4.png)

**Comment by pangyana** [comment]
reponse里面是[],没有数据 @masato25

**Comment by pangyana** [comment]
<img width="1260" alt="22323" src="https://user-images.githubusercontent.com/16829933/28817554-24630768-76db-11e7-97d2-49df3539b963.png">

**Comment by masato25** [comment]
@pangyana 那我知道你的問題了
之前的作法是有錯誤的counter (資料庫找不到符合的metric) , 會返回空值
這個問題在https://github.com/open-falcon/falcon-plus/pull/150 已經修復.
你可以更新到最新版本的api module 應該可以解決這個問題

**Comment by pangyana** [comment]
@masato25   谢谢！
编译了最新的后，发现启动不起来，配置文件放的目录是对的，配置文件也是之前的，用了新的falcon-api，报错“time="2017-08-02T13:40:33+08:00" level=fatal msg="db conn failed with error connect to falcon_portal: dial tcp 127.0.0.1:3306: getsockopt: connection refused"”  看上去没有读取到配置文件里的配置？

**Comment by masato25** [comment]
@pangyana 我們有修復過配置檔的文件, 檢查一下
https://github.com/open-falcon/falcon-plus/blob/master/modules/api/cfg.example.json#L4
```
"db": {
		"falcon_portal": "root:@tcp(127.0.0.1:3306)/falcon_portal?charset=utf8&parseTime=True&loc=Local",
```
可能你本地的配置檔還沒修改過來

**Comment by pangyana** [comment]
@masato25  是这单词的原因，解决了，谢谢！ [泪流满面]
