### ISSUE TITLE
为什么 BindHostToHostGroup 是覆盖更新，而不是增量更新

### ISSUE THREAD

**Issue by jojohappy** [open-falcon/falcon-plus#194]
如题
如果遇到并发绑定同一个 hostgroup 时，会产生 bug

**Comment by masato25** [comment]
HI @jojohappy 感谢你的回报
这边的作法当初是想说做的单纯一点, 因為增量更新也有可能是 增量更新 + 减量删除.
例如一开始是 "a", "b", "c", "d"
后来改绑定 "a", "b", "c", "e"
"a", "b", "c" 是相同的 "d" 需要删除 "e" 需要加上. 所以当初采的实做作法就是全部去除之后一次更新的作法. (且该表本身就没有建立primary id, 所以不会造成流水号id暴量的问题)
另外你提到的并发绑定的问题. 好奇什么时候会有这样的使用情境状况呢？
另外一个问题是如果改写成 增量更新 + 减量删除就没有问题了？ 
我这边是猜测可能是资料库table lock产生的问题 (因為并发很大量重复动作, 当transaction A尚未完成 而并发请求transaction B). 
欢迎你在提供更多的资讯, 或是提供我们PR的贡献 谢谢

**Comment by masato25** [comment]
@jojohappy 這邊有個小技巧可以分享給你

其實你只需要調用 BindHostToHostGroup 即可. 然後直接提供你要綁定的機器名列表.
系統會自動幫你建立新的host  (如果此host還不存在). 其實此api就可以完成 建立 更新兩種行為.
你只需要專注你想要綁定的機器組列表即可.
希望以上的建議可以對你有幫助.

**Comment by jojohappy** [comment]
谢谢你的回复~

不过依然会存在问题，毕竟还是需要获取当前 hostgroup 的主机列表，然后再提交到 API 中。当同时操作一个 hostgroup，并且绑定不同的主机时，可能会造成主机不能绑定到 hostgroup

**Comment by masato25** [comment]
@jojohappy  感謝你的反饋, 我開了另外一個issue  https://github.com/open-falcon/falcon-plus/issues/209
計畫提供局部更新刪除的api.
