### ISSUE TITLE
Agent上报时间间隔小于30秒，修改配置文件不能搞定

### ISSUE THREAD

**Issue by w90006303** [open-falcon/falcon-plus#195]
如题，对于一些特殊场合，可能会有短时间内监控的粒度更细（间隔小于30秒），但是修改了配置文件中得间隔小于30秒时没有成功

**Comment by laiwei** [comment]
https://github.com/open-falcon/falcon-plus/blob/master/config/transfer.json#L3

小于30秒，需要修改transfer的配置来支持。  @w90006303
