### ISSUE TITLE
交换机监控图中最多只能设置24个端口

### ISSUE THREAD

**Issue by ijintong** [open-falcon/falcon-plus#196]
当前有很多大于24口的交换机，如48口的，还是堆叠的。
但是当前falcon一个图表中只能设置24个端口，希望能优化一下！

**Comment by freedomkk-qfeng** [comment]
这是因为dashboard的screen里，counter列表字符长度有限制，默认是1024。因此如果填的counter太多的话，后面的会被截断
修改 dashboard_graph 表，把 counter 的长度限制放大即可

**Comment by ijintong** [comment]
已经修改解决，谢谢亲！
