### ISSUE TITLE
open-falcon API

### ISSUE THREAD

**Issue by xiaowei0516** [open-falcon/falcon-plus#197]
1. 请问一下 [open-falcon API](http://open-falcon.org/falcon-plus/) ，这个页面是用什么做的？我在开源代码没有找到。

2. 对于每个API的最后，都有一个 For more example, see the xxx.html,   xxx.html在api模块中是生成， 我在配置文件中将gen_doc 配置成true， 但是没有生成doc/module.html

**Comment by laiwei** [comment]
- Q：open-falcon v0.2的api文档是如何生成的？API文档地址 http://open-falcon.org/falcon-plus/
- A：人工生成yaml描述文件，通过Jekyll来生成静态站点，使用github来serve，api站点的源码在 https://github.com/open-falcon/falcon-plus/tree/master/docs 这里。不过可以通过打开api组件的gen_doc选项，然后api会把请求和应答都记录下来，作为撰写api yaml文件的参考。

**Comment by xiaowei0516** [comment]
@laiwei ，thanks， 根据你的提示，已经安装成功。
