### ISSUE TITLE
dashboard启动后WEB页上任何人都可以注册，且注册者都为管理员权限

### ISSUE THREAD

**Issue by ijintong** [open-falcon/falcon-plus#198]
当前dashboard启动后WEB页上任何人都可以注册，且注册者都为管理员权限。
这种情况只要有人知道我的WEB地址，就能注册能作恶了，希望优化一下。
希望关闭WEB页注册功能，细分管理员和普通权限。

**Comment by masato25** [comment]
在v0.2版本中 透过api module后端配置可以解决这个问题
https://github.com/open-falcon/falcon-plus/blob/master/modules/api/cfg.example.json
将 `signup_disable: true` 设定之后, 只有已登入的管理者帐号可以创建新的帐号
