### ISSUE TITLE
falcon api组件更新后 调取hostgroup等接口报Error 1046: No database selected"

### ISSUE THREAD

**Issue by liyx778** [open-falcon/falcon-plus#199]
由于之前的0.2版本api组件在添加screen时会报错，所以下载编译了最新版的api组件编译 并解决了这个问题。
但是。。又出现了新的问题（老的0.2版本没有这个问题）  执行命令：“curl -H ""Content-Type":"application/json"" -H ""Apitoken":{\"name\":\"name\",\"sig\":\"sig\"}" "http://127.0.0.1:8080/api/v1/hostgroup"”
返回“{"error":"Error 1046: No database selected"}” 
还请官方大神修复下这个问题。

**Comment by masato25** [comment]
檢查一下這個配置檔
https://github.com/open-falcon/falcon-plus/blob/master/modules/api/cfg.example.json#L4
之前有修正過 錯字, 可能你本地的配置檔還沒修正過來

**Comment by liyx778** [comment]
解决了，谢谢~
