### ISSUE TITLE
dashboard升级到0.2后，原有的注册账号登录不了

### ISSUE THREAD

**Issue by pangyana** [open-falcon/falcon-plus#201]
dashboard升级到0.2后，原有的注册账号登录不了，重新注册账号后，发现uic库的user表确实增加了一条记录，但是原来的账号登录不上报密码错误。
尝试将新账号的密码更新到老账号后，老账号能登录上。
感觉是user表的passwd字段加密方式不一样，导致老账号登不上去。

**Comment by masato25** [comment]
@pangyana 原則上0.1 & 0.2 加密的方式是一樣的
注意新舊的salt 必須一致:
https://github.com/open-falcon/falcon-plus/blob/master/modules/api/cfg.example.json#L25
```
	"signup_disable": false,
	"salt": "",
```

**Comment by pangyana** [comment]
@masato25  谢谢，解决了
