### ISSUE TITLE
升级0.2后使用dashboard的8081端口查询数据时要验证，如何取消或者验证呢

### ISSUE THREAD

**Issue by hel2o** [open-falcon/falcon-plus#207]
如v0.1时可以直接使用
http://192.168.99.27:8081/chart?endpoints%5B%5D='.$endpoints.'&counters%5B%5D='.$counters.'&graph_type=h
去获得这个counter的ID值，现在V0.2增加了验证，获得失败现在，要如何取消呢或者有没有其它的方式？

**Comment by hitripod** [comment]
可以参考 API 文档的说明：http://open-falcon.org/falcon-plus/#/authentication
