### ISSUE TITLE
HostGroup 支援机器增量 or 部份删除功能

### ISSUE THREAD

**Issue by masato25** [open-falcon/falcon-plus#209]
基于 https://github.com/open-falcon/falcon-plus/issues/194 的讨论, 大致上一般UI界面使用的需求BindHostToHostGroup 可以满足UI操作需求. 但是API使用需求上还是希望有局部增加或是删除机器.

实做提供这两个api 让hostgroup 操作可以更加弹性.

**Comment by jojohappy** [comment]
@masato25 这个问题是我现在想解决的，所以我会尽快提交一个 PR ，并在进行一些测试

**Comment by jojohappy** [comment]
#227
