### ISSUE TITLE
报一个bug，原脚本上报metric: Com_insert/port=3306，修改成com_insert/port=3306后，dashboard搜索不到对应的metrics

### ISSUE THREAD

**Issue by 527593036** [open-falcon/falcon-plus#215]
报一个bug，原脚本上报metric: Com_insert/port=3306，修改成com_insert/port=3306后，dashboard搜索不到对应的metrics

环境情况：0.2版本整套

**Comment by liangyanbina** [comment]
前几天我也遇到这个问题了.

**Comment by laiwei** [comment]
@527593036 没有太理解你的描述。 falcon dashboard中，搜索的时候是不区分大小写的。

你修改为小写后，还做了什么操作呢

**Comment by liangyanbina** [comment]
@laiwei 改为小写后，在dashboard里查不到小写的conters，只能看到大写的counters

**Comment by 527593036** [comment]
@laiwei  和@liangyanbina描述的一样，在dashboard里面搜索不到小写的counters，在graph.endpoint_counter表里面也查不到，最终通过下面的方法解决(动作有点大，也是刚好需要做这个动作)
1、rename graph.endpoint_counter to graph.endpoint_counter_tmp
2、create table graph.endpoint_counter like graph.endpoint_counter_tmp
3、curl -s 127.0.0.1:6071/index/updateAll

**Comment by laiwei** [comment]
@527593036 你这个操作确实动作有些大，不过可以解决问题 👍 

还有两个方法：
- 方法1： 删掉graph.endpoint_counter中包含 Com_insert/port=3306 的行，然后 curl -s 127.0.0.1:6071/index/updateAll；
- 方法2：直接修改graph.endpoint_counter中包含 Com_insert/port=3306 的行为com_insert/port=3306 也是没有什么影响的。
