### ISSUE TITLE
[agent] 从环境变量 ENDPOINT 来获取主机名

### ISSUE THREAD

**Issue by taomaree** [open-falcon/falcon-plus#216]
有一定的规模部署的环境中，主机名往往是随机生成无规律的。
我们的一个实践是主机名随机生成，通过环境变量 ENDPOINT 来自定义业务属性。
ENDPOINT 格式举例 nginx_1.2.3.4, db_mysql_pay_11.22.33.44

这样有以下好处：
- 根据环境变量能快速识别该主机的业务信息，比如主要业务、IP地址。
- 上报数据中，endpoint 的信息比较丰富,不需要额外上报 tag 来标识。
- 方便维护主机组，主机名如果是随机的，策略里面主机名的识别和管理也比较麻烦。
- 所有falcon-agent的配置文件统一，相当于“无状态”的业务，升级和管理方便。
- 方便在 docker 中部署 falcon-agent。 

客户端的 endpoint 取值优先级为：

1.  cfg.json 中的 hostname 属性
2. 系统环境变量 ENDPOINT
3. 系统的主机名

相关的PR ：
#219

**Comment by laiwei** [comment]
@taomaree 挺好的想法和改动，赞。

**Comment by taomaree** [comment]
在合并的代码基础上，新提交了一个PR，支持从指定的环境变量取值。
这样更灵活地适应不同的部署环境。

比如，我们线上已经定义了一个指定的环境变量，而我们又不想维护一套agent的私有分支，
所以需要再提交这个PR，做到可以自定义，希望达到各取所需的目的。

#223

**Comment by laiwei** [comment]
@taomaree agent添加配置项比较复杂，社区版本我直接在你的基础上修改为 FALCON_ENDPOINT环境变量了
