### ISSUE TITLE
[agent] UEFI 引导分区 /boot/efi 为 vfat 格式 inodes 为0

### ISSUE THREAD

**Issue by taomaree** [open-falcon/falcon-plus#218]
UEFI 引导分区 /boot/efi 为 vfat 格式 inodes 为0，上报的数据为：
df.bytes 均有正常数据，而 df.inodes 相关数据均为 0 。

建议类似于 df.bytes.total 的处理 。
当 df.inodes.total 为 0 时，df.inodes 相关数据 ( df.inodes.total, df.inodes.used,
df.inodes.free, df.inodes.used.percent, df.inodes.free.percent ) 不再上报。

相关PR #217

**Comment by laiwei** [comment]
@taomaree merged 👍
