### ISSUE TITLE
ping redis fail ERR operation not permitted

### ISSUE THREAD

**Issue by YouZhengChuan** [open-falcon/falcon-plus#221]
version: 2.0.2
os env: Linux xxxxxx 2.6.32-573.el6.x86_64 #1 SMP Thu Jul 23 15:44:03 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Error: 
`17:17:00 redis.go:41: [ERROR] ping redis fail ERR operation not permitted`

使用root方式运行也会写入redis失败

**Comment by laiwei** [comment]
redis的功能和以什么用户运行无关。你需要看看是不是确实网络都不通
@YouZhengChuan

**Comment by YouZhengChuan** [comment]
是因为redis启用了密码，但是falcon源码中没有支持，以增加支持解决了
