### ISSUE TITLE
关于关闭注册和只读帐号

### ISSUE THREAD

**Issue by CastroKKK** [open-falcon/falcon-plus#224]
你好！有几个疑问小弟不太清楚，麻烦指导下，谢谢
1、我看了你的关闭注册，第一步signup_disable这里如果要关闭应该设置成true吧？
2、第二步和第三部的2个文件是源码，要重新编译吗？

另外如何创建一个只读帐号呢？

求指导。谢谢！

**Comment by masato25** [comment]
@CastroKKK 
關於關閉註冊 將api module 的 signup_disable 設為 true 就可以了. 之後在註冊就使用管理者帳號做註冊

我不懂第二步第三步的意思是？ 
另外只讀帳號的定義是？ 如果是只能登入觀看不能做任何操作的類型的使用者的話. 目前我們沒有這方面的使用者權限設計.
