### ISSUE TITLE
在screen中添加加和graph后无法取消加和

### ISSUE THREAD

**Issue by yuline** [open-falcon/falcon-plus#225]
在screen中添加graph可以选择对counter值进行加和，但是选择加和后就无法再次取消。
疑似这段代码有问题：
https://github.com/open-falcon/falcon-plus/blob/master/modules/api/app/controller/dashboard_graph/dashboard_graph_controller.go

line：189-191
	if inputs.Method != "" {
		d.Method = inputs.Method
	}

从前端代码看：在取消加和时inputs.Method值就是''，而在api  DashboardGraphUpdate方法中如果method为空就不会再修改数据库中的graph 的method字段。
rrd/view/dashboard/screen.py:
line218: method = request.form.get("method", '').upper()

**Comment by laiwei** [comment]
很好的反馈👍  ，可以来一个pull-request:)

**Comment by yuline** [comment]
看起来直接删除
if inputs.Method != "" {
d.Method = inputs.Method
}即可，在python的update方法里，如果之前已经设置过了method，使用DashboardGraph.update()方法时会自动将method字段补充为原graph的method。
如果之前没有选择method，会将method字段置为“”。

**Comment by yuline** [comment]
gorm中现在的Updates(struct)用法不支持重置空值：

// WARNING when update with struct, GORM will only update those fields that with non blank value
// For below Update, nothing will be updated as "", 0, false are blank values of their types
db.Model(&user).Updates(User{Name: "", Age: 0, Actived: false})
