### ISSUE TITLE
tmp_graph 这个数据表的目的是什么？

### ISSUE THREAD

**Issue by xiaowei0516** [open-falcon/falcon-plus#226]
hi，
    今天看了半天 graph 模块，一直没看懂tmp_graph是干什么用的？

   里面存储了：
             endpoint  metric       md5  timestamp

**Comment by masato25** [comment]
印象中這是v1 opefalcon用來暫存畫圖條件的table ，暫存之後就可以透過hash讀回畫圖條件，在falcon-plus中沒有用到 如果製作自己的前端操作頁面時有需求可以加入使用

**Comment by laiwei** [comment]
恩恩 这张表在0.2中也是有用的：）

用于dashboard看图时，自动把一组指标变成一个id，这样用户就可以分享这个链接达到分享图表的目的。

@xiaowei0516 @masato25

**Comment by xiaowei0516** [comment]
谢谢！  @laiwei  @masato25
