### ISSUE TITLE
后台登陆不了, 怎么回事？

### ISSUE THREAD

**Issue by leeyongda** [open-falcon/falcon-plus#229]
raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8080): Max retries exceeded with url: /api/v1/user/create (Caused by : [Errno 111] Connection refused)

**Comment by laiwei** [comment]
api组件没有启动，请检查一下 @leeyongda

**Comment by xuyitao** [comment]
我也碰到这个问题，确实是api组件没有启动，原因是如下：

>time="2017-08-25T12:32:28+08:00" level=fatal msg="db conn failed with error connect to falcon_portal: Error 
1045: Access denied for user 'root'@'localhost' (using password: NO)" 

看log应该是数据库没有权限，我用的是mariadb，用户名root，密码没办法设置成空，这个怎么解？

**Comment by laiwei** [comment]
@xuyitao 你可以修改api的配置文件，在配置文件中指定定mariadb的密码。

**Comment by bxhbpdxhzGithub** [comment]
level=fatal msg="db conn failed with error connect to falcon_portal: dial tcp 127.0.0.1:3306: getsockopt: connection refused

**Comment by bxhbpdxhzGithub** [comment]
level=fatal msg="db conn failed with error connect to falcon_portal: dial tcp 127.0.0.1:3306: getsockopt: connection refused
 这个是什么原因呀

**Comment by keiler2018** [comment]
api 组件驱动了 也报这个错误啊

**Comment by laiwei** [comment]
> api 组件驱动了 也报这个错误啊

请检查下 api 所在的机器，是否可以访问你的 MySQL。
