### ISSUE TITLE
急求falcon部分常见繁琐问题处理办法！！！

### ISSUE THREAD

**Issue by CastroKKK** [open-falcon/falcon-plus#231]
各位大大好：

1、目前alarm删除case的方式一次性十行还是不够效率，我想在mysql数据库中的alarm_case 直接删除数据，是否安全？副作用？

2、服务器目前几千台，部分hostname变化或人为修改，导致太多垃圾endpoint，是否有自动清理或者手动清理endpoint无效值的方法。

**Comment by masato25** [comment]
@CastroKKK 手動刪除event_case 是沒有問題的,  前提是你確認這些數據都已經都不需要了.
刪除一個event_case 會將連帶該id 所關聯的 events & event_note 一併刪除.

**Comment by laiwei** [comment]
@CastroKKK
 
第一个问题，删除event_case如 @masato25 的回答，你也可以借助API来完成；

第二个问题，垃圾endpoint的删除，你可以用task这个模块来做，或者你去定期删除数据库中许久没有更新的行，可以参考faq:  https://book.open-falcon.org/zh_0_2/faq/

![image](https://user-images.githubusercontent.com/792850/29771935-cc89fff2-8c28-11e7-902c-a9039fd76d2e.png)

**Comment by Xuexiang825** [comment]
@laiwei 删除过期索引 curl -s "127.0.0.1:6071/index/delete" 提示404 page not found

**Comment by kxst** [comment]
你们是什么公司几千台机器，你需要保证   falcon_portal.host 表中的数据是正确的，然后根据  falcon_portal.host 表删除另外三张表，sql 如下。
delete a from graph.endpoint a left join falcon_portal.host b on a.endpoint=b.hostname where b.hostname is null
delete a from graph.endpoint_counter a left join graph.endpoint b on a.endpoint_id=b.id where b.id is null
delete a from graph.tag_endpoint a left join graph.endpoint b on a.endpoint_id=b.id where b.id is null

**Comment by Jiangnan-Ora-Xia** [comment]
自定义endpoint后，删除原来的endpoint，使用curl -s http://127.0.0.1:6071/index/updateAll刷新后，旧的和新自定义的都存在，而且每个Counter数都重复了，具体步骤如下：
falcon_portal： delete from host where hostname='xx’;
graph: 
        delete from endpoint where endpoint='xxx’;
        delete from endpoint_counter where endpoint_id=xx;

curl -s http://127.0.0.1:6071/index/updateAll

**Comment by wushengwusheng** [comment]
请问还能回复我吗？
1.我在http://open-falcon.org/falcon-plus/#/alarm_eventcases_list中没有找到删除event_case的api
2.我控制台查看了dashboard删除alarm case的接口是/portal/alarm-dash/case/delete，我调用给我返回了html代码，没生效
请问现在如何删除指定alarm case？

**Comment by masato25** [comment]
falcon-plus 的设计思维是 alarm 如果触发，可以等它自动恢复，或是使用 eventnote 来去更新状态 ignored or unresolved. 当标记为 ignored or unresolved 的 alarm 不会显示，http://open-falcon.org/falcon-plus/#/alarm_eventnote_create. 
alarm 数值是否正常主要看 status，如果持续 alarm 产生 case 还是会被 reopen.

----

如果是 dadhboard 的话，它使用的是自己的 api 没有使用 falcon-plus,
https://github.com/open-falcon/dashboard/blob/4383d1d4be5b6d773e449fb6dfaa5a079ece057b/rrd/view/portal/alarm.py#L52-L74

可以试试这样调用看看:
```
curl -X POST \
  http://localhost:8080/portal/alarm-dash/case/delete \
  -F ids=999
```

**Comment by wushengwusheng** [comment]
十分感谢大佬的解答！！！


| |
吴升
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | 王雅人 ***@***.***> |
| 发送日期 | 2022年08月25日 14:49 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [open-falcon/falcon-plus] 急求falcon部分常见繁琐问题处理办法！！！ (#231) |

falcon-plus 的设计思维是 alarm 如果触发，可以等它自动恢复，或是使用 eventnote 来去更新状态 ignored or unresolved. 当标记为 ignored or unresolved 的 alarm 不会显示，http://open-falcon.org/falcon-plus/#/alarm_eventnote_create.
alarm 数值是否正常主要看 status，如果持续 alarm 产生 case 还是会被 reopen.

如果是 dadhboard 的话，它使用的是自己的 api 没有使用 falcon-plus,
https://github.com/open-falcon/dashboard/blob/4383d1d4be5b6d773e449fb6dfaa5a079ece057b/rrd/view/portal/alarm.py#L52-L74

可以试试这样调用看看:

curl -X POST \

  http://localhost:8080/portal/alarm-dash/case/delete \

  -F ids=999

**Comment by wushengwusheng** [comment]
感谢大佬的回答！！！@masato25

**Comment by wushengwusheng** [comment]
<img width="1163" alt="image" src="https://user-images.githubusercontent.com/30250875/186832793-1d215405-fe43-42f9-ba66-0a025f98e695.png">
<img width="1351" alt="image" src="https://user-images.githubusercontent.com/30250875/186832825-785511f9-ace3-4ea7-a7a7-c4f55e18be65.png">

请问下，这个接口的开始时间和结束时间是不是有要求相隔多久？@masato25
