### ISSUE TITLE
falcon_api  创建nodata问题

### ISSUE THREAD

**Issue by xiaowei0516** [open-falcon/falcon-plus#232]
hi，
     nodata接口创建一条记录的时候报错！错误为下：
    ```
   Field 't_create' doesn't have a default value
    ```
按照api代码逻辑，sql 操作方法：
```
mysql> INSERT INTO `mockcfg` (`name`,`obj`,`obj_type`,`metric`,`tags`,`dstype`,`step`,`mock`,`creator`) VALUES ('testnodata','docker-agent','host','test.metric','','GAUGE','60','-1','zhangxiaowei');

```

正确的应该是：
```
ysql> INSERT INTO `mockcfg` (`name`,`obj`,`obj_type`,`metric`,`tags`,`dstype`,`step`,`mock`,`creator`,`t_create`) VALUES ('testnodata','docker-agent','host','test.metric','','GAUGE','60','-1','zhangxiaowei','2009-01-01 12:12:12');
Query OK, 1 row affected (0.01 sec)

```

**Comment by xiaowei0516** [comment]
[链接地址](http://open-falcon.org/falcon-plus/#/nodata_create)

**Comment by laiwei** [comment]
你的MySQL版本是什么？ @xiaowei0516

**Comment by MistShi** [comment]
---

CREATE TABLE `mockcfg` (
  `id`       BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name`     VARCHAR(255) NOT NULL DEFAULT '' COMMENT 'name of mockcfg, used for uuid',
  `obj`      VARCHAR(10240) NOT NULL DEFAULT '' COMMENT 'desc of object',
  `obj_type` VARCHAR(255) NOT NULL DEFAULT '' COMMENT 'type of object, host or group or other',
  `metric`   VARCHAR(128) NOT NULL DEFAULT '',
  `tags`     VARCHAR(1024) NOT NULL DEFAULT '',
  `dstype`   VARCHAR(32)  NOT NULL DEFAULT 'GAUGE',
  `step`     INT(11) UNSIGNED  NOT NULL DEFAULT 60,
  `mock`     DOUBLE  NOT NULL DEFAULT 0  COMMENT 'mocked value when nodata occurs',
  `creator`  VARCHAR(64)  NOT NULL DEFAULT '',
  **`t_create` DATETIME NOT NULL COMMENT 'create time',**
  `t_modify` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'last modify time',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

---
--- 
	mockcfg := f.Mockcfg{
		Name:    inputs.Name,
		Obj:     inputs.Obj,
		ObjType: inputs.ObjType,
		Metric:  inputs.Metric,
		Tags:    inputs.Tags,
		DsType:  inputs.DsType,
		Step:    inputs.Step,
		Mock:    inputs.Mock,
		Creator: user.Name,
	}
---

**Comment by laiwei** [comment]
https://github.com/open-falcon/falcon-plus/pull/460  @xiaowei0516
