### ISSUE TITLE
agent实现只做push上报

### ISSUE THREAD

**Issue by wenskys** [open-falcon/falcon-plus#249]
大神们，求教个问题
问题1：我想把agent放容器中，然后只做push上报，不让他监控基础的cpu、内存这些，除了ignore一个个添加外(目前逐个添加了100多个)，有参数可以不上报这些基础数据么
问题2：小米监控中rpc是tcp还是http的rpc呢

**Comment by laiwei** [comment]
1. 没有这个配置
2. tcp
