### ISSUE TITLE
在调用Update partial hosts in HostGroup接口时报404错误

### ISSUE THREAD

**Issue by Nafee-Chen** [open-falcon/falcon-plus#254]
PATCH http://10.116.0.9:8080/api/v1/hostgroup/20/host
Headers:
Apitoken {"name":"chennf","sig":"ad95ceaa98fe11e7add82c44fd8a49d8"}
Accept application/json
Content-Type application/json
Body:
{
  "hosts": ["test-container"],
  "action": "add"
}

在调用接口时，一直报404错误：404 page not found。

**Comment by masato25** [comment]
@Nafee-Chen 可以请你确认, 你的 `api` 模组版本是否更新到最新版吗？ 
我使用最新版手边测试, 无法重现这个404问题

**Comment by shaohua-zhangmr** [comment]
curl -H ""Content-Type":"application/json"" -H ""Apitoken":{"name":"hahaha","sig":"default-token-used-in-server-side"}" --request PATCH "http://xx.xx.xx.xx:8080/api/v1/hostgroup/33/host" -d '{"hosts":"10.125.196.121","action":"add"}'
在调用接口时，一直报404错误：404 page not found
请指教下，谢谢

**Comment by wongchao** [comment]
@masato25 api 模块组版本如何确认是否更新到呢？ 按照git book 2.0 版本安装, 直接使用编译好的二进制。 没有使用源码编译。
