### ISSUE TITLE
在调用Get Metric List接口时报404错误

### ISSUE THREAD

**Issue by Nafee-Chen** [open-falcon/falcon-plus#255]
GET http://10.116.0.9:8080/api/v1/metric/tmplist
Headers:
Apitoken {"name":"chennf","sig":"ad95ceaa98fe11e7add82c44fd8a49d8"}
Accept application/json

调用该接口时报404错误：404 page not found。

**Comment by laiwei** [comment]
@Nafee-Chen 

抱歉，文档搞错了，这里api的url应该是：/api/v1/metric/default_list

稍后修订文档。
