### ISSUE TITLE
alarm  调用redis , redis 设置密码

### ISSUE THREAD

**Issue by Mr-xin-Z** [open-falcon/falcon-plus#256]
alarm 配置怎么添加 带密码 redis 配置?

**Comment by lemonzone2010** [comment]
我也遇到这个问题了

**Comment by mdh67899** [comment]
这个要改代码了，judge和alarm里面cfg.json里面加上密码配置，GlobalConfig的结构体加上密码字段，改一下ParseConfig方法，在InitRedisConnPool()的方法里面加个判断，密码为空就跳过，有密码就验证, 总体来说改的不多

**Comment by laiwei** [comment]
@Mr-xin-Z 现在不支持设置redis的密码
