### ISSUE TITLE
希望提供 grafana-falcon-datasource 详细的查询语法的文档。

### ISSUE THREAD

**Issue by rrfeng** [open-falcon/falcon-plus#258]
目前只能自己摸索，而且还有一些 bug，或者特性。用起来很难。

**Comment by masato25** [comment]
可以参考 https://github.com/open-falcon/falcon-plus/pull/262 的文档
或是参考测试 https://github.com/open-falcon/falcon-plus/blob/master/modules/api/app/controller/graph/grafana_controller_test.go
