### ISSUE TITLE
v0.2.1版编译graph组件报错

### ISSUE THREAD

**Issue by tycjlee** [open-falcon/falcon-plus#259]
相同环境下编译v0.2.0成功的。
[root@rhel6 falcon-plus]# make graph
go build -o bin/graph/falcon-graph ./modules/graph
unexpected directory layout:
        import path: github.com/gin-gonic/gin
        root: /open-falcon/Paasapplications/mygo/src
        dir: /open-falcon/Paasapplications/mygo/src/github.com/open-falcon/falcon-plus/vendor/github.com/gin-gonic/gin
        expand root: /open-falcon/Paasapplications/mygo/src
        expand dir: /open-falcon/Paasapplications/mygo/src/github.com/open-falcon/falcon-plus/vendor/github.com/gin-gonic/gin
        separator: /
make: *** [graph] 错误 1

**Comment by imzye** [comment]
进到module/graph目录里面，用go build main.go编译呢？

**Comment by laiwei** [comment]
确保gopath等环境变量是设置OK的 @tycjlee
