### ISSUE TITLE
请问按天上报数据，应该怎么处理？

### ISSUE THREAD

**Issue by Yuani** [open-falcon/falcon-plus#260]
请问按天上报的数据能处理吗？如果可以，应该怎么处理？

**Comment by CastroKKK** [comment]
我也遇到这个问题，我现在遇到的问题是以下两个：

1、我的step设置的是86400，但是我发现举例我在一天的24小时中上报的任何一个时间点的1次数据，显示的当日数据点时间都是  am 8：00  ？？？ 黑人问号？？？ 这是为何？

2、我有一个push数据是今天才能拿到昨天的上报数据，那么我上报时时间戳时间-86400 之后push为什么不能出现在昨日的dashboard图形中的昨日数据图中呢？我应该如何正确操作？

**Comment by laiwei** [comment]
duplicated with https://github.com/open-falcon/falcon-plus/issues/271
