### ISSUE TITLE
请问 transfer 抱这个错 

### ISSUE THREAD

**Issue by kxst** [open-falcon/falcon-plus#261]
错误描述： rpc.go:35: listener.Accept occur error: accept tcp [::]:8433: accept4: too many open files

已经调整过 ulimit，依旧会出现。

**Comment by laiwei** [comment]
那确实是系统fd不够，你的设置是否生效了，或者是否够大。
@kxst

**Comment by kxst** [comment]
ulimit 的软和硬已经调整到 65535了，内核句柄数  /proc/sys/fs/file-max 也已经调整到 1627151。 可是隔断时间问题依然会出现。是  modules/transfer/receiver/rpc/rpc.go 的 35行那块代码有问题吗？感觉是个死循环。

func StartRpc() {
        if !g.Config().Rpc.Enabled {
                return
        }

        addr := g.Config().Rpc.Listen
        tcpAddr, err := net.ResolveTCPAddr("tcp", addr)
        if err != nil {
                log.Fatalf("net.ResolveTCPAddr fail: %s", err)
        }

        listener, err := net.ListenTCP("tcp", tcpAddr)
        if err != nil {
                log.Fatalf("listen %s fail: %s", addr, err)
        } else {
                log.Println("rpc listening", addr)
        }

        server := rpc.NewServer()
        server.Register(new(Transfer))

        for {
                conn, err := listener.Accept()
                if err != nil {
                        log.Println("listener.Accept occur error:", err)
                        continue
                }
                // go rpc.ServeConn(conn)
                go server.ServeCodec(jsonrpc.NewServerCodec(conn))
        }

**Comment by Yanjunhui** [comment]
死循环 没毛病啊  接受连接 本来就得是死循环

**Comment by kxst** [comment]
感谢，问题找到了，是进程的 ulimit 没有修改。

**Comment by xiaowei0516** [comment]
@kxst ,请关闭这个issue

**Comment by carrotshub** [comment]
> 感谢，问题找到了，是进程的 ulimit 没有修改。

遇到同样问题，请教下是怎么解决的？
