### ISSUE TITLE
Grafana插件中函数似乎不能用

### ISSUE THREAD

**Issue by PhantomThief** [open-falcon/falcon-plus#264]
例如aliasByNode之类的，各种尝试都无法使用。

Grafana版本为4.4.1

有没有一个具体的例子？确认下我们使用的方式正确。

**Comment by masato25** [comment]
你举例的这个函数在graph中是没有作用的
当初这个open-falcon grafana 插件是采用 graphite_grafana_plugin 插件来修改的,
http://graphite.readthedocs.io/en/latest/functions.html

有一些code没有移除, 所以可能你们修改code的时候这些函数会显示出来. 这些在graph中都没有相对应的后端实做. 所以是没有功能的

**Comment by PhantomThief** [comment]
@masato25 那有没有可能提供呢？比如alias的功能在渲染legend时还是很有用的，不然tag老长老长直接怼到legend上也是很难过……
