### ISSUE TITLE
关于增量更新时间间隔

### ISSUE THREAD

**Issue by imzye** [open-falcon/falcon-plus#265]
graph模块的index_update_incr_task.go这个里面有个增量索引更新时间，注释中写的默认是30s，可是代码中（如下）好像是1s，不知道这里该如何理解？

const (
	IndexUpdateIncrTaskSleepInterval = time.Duration(1) * time.Second // 增量更新间隔时间, 默认30s
)

**Comment by laiwei** [comment]
@imzye 代码写的和注释不一致，你可以提pr修改为30秒
