### ISSUE TITLE
graph模块经常出现OOM

### ISSUE THREAD

**Issue by imzye** [open-falcon/falcon-plus#267]
两个graph同一套代码，一个正常，另一个经常OOM，不知道是不是hash的不均匀？

<img width="681" alt="screen shot 2017-10-08 at 14 16 38" src="https://user-images.githubusercontent.com/9260235/31314447-9914ffe2-abc6-11e7-9383-90e4d269f7ea.png">

**Comment by laiwei** [comment]
运行时free看看，内存占用情况和内容总大小。

hash不均理论上是有可能的

**Comment by laiwei** [comment]
@imzye 有进一步信息吗

**Comment by imzye** [comment]
将两个大内存的graph换成4个稍小内存的graph，修改transfer配置后就没再出现这个问题。@laiwei

之前我尝试修改graph源码里面的DefaultMaxCacheSize，CLEAN_CACHE，FLUSH_DISK_STEP，FLUSH_MAX_WAIT这些常量参数，重编译运行一段时间后（3 - 9小时）都会出现上述OOM问题，不知道是否是因为磁盘的随机写性能太差，导致数据来不及落到盘上，最终OOM。
