### ISSUE TITLE
judge启动时需要初始化LastEvents的数据

### ISSUE THREAD

**Issue by abjackjay** [open-falcon/falcon-plus#270]
在judge重启前，产生了很多告警，且状态都为PROBLEM，在judge重启过程中，这些告警对应的counter的值都没有达到阈值，judge重启后，之前产生的告警事件无法恢复成OK状态。比如某个agent的设备关机，此时agent.alive的直为0，触发了告警，生成了eventcase，然后重启judge进程，同时将设备开机，假设设备先开机，此时agent.alive的值为1，但是judge中LastEvents没有对应的数据，导致sendEventIfNeed方法中没有触发sendEvent，该event的status一直为PROBLEM，无法恢复，需要让agent.alive的值为0，触发一下告警，让LastEvents有对应的数据。在judge启动时能否从eventcase表中将所有告警事件同步过来保存到LastEvents中作为初始数据。

**Comment by laiwei** [comment]
未恢复的event status，可以考虑人工每天巡检，从alarm-dashboard上清除。

这样改代码，会很复杂，牵扯多。
