### ISSUE TITLE
【报错】上报数据中有中文时，graph 读取数据报错：errno: 0x023a, str:opening error

### ISSUE THREAD

**Issue by Yuani** [open-falcon/falcon-plus#274]
现象：
上报的数据加上了中文标签，graph 存储正常，grafana 读取数据展示正常，但是graph 会报错：errno: 0x023a, str:opening error

请问：
这是graph 的BUG 嘛？还是说不支持中文？或者说我上报格式不对？

**Comment by imzye** [comment]
https://github.com/yubo/rrdlite/blob/master/rrd_error.h
这个错误好像是打开文件错误，貌似跟中文无关，跟磁盘性能好像关系比较大

**Comment by Yuani** [comment]
graph 是否有最大文件打开数限制？这里通过grafana读取数据使用，使用了正则表单，和这个有关系吗？

**Comment by laiwei** [comment]
文件打开出错，请看看系统日志，或者看看系统设置中fd的限制是多少？ @Yuani

**Comment by Yuani** [comment]
@laiwei   是ulimit -n  的值吗？

# ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 59672
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 655360
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 12000
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

**Comment by laiwei** [comment]
这个错误，应该是读取不存在的counter造成的，可以忽略。
