### ISSUE TITLE
api调用session有效期问题

### ISSUE THREAD

**Issue by blackholll** [open-falcon/falcon-plus#276]
使用/api/v1/user/login登录后，返回值得格式为 {u'admin': False, u'sig': u'1bf7be50b3a511e7b66f525400934378', u'name': u'test'} 没有有效期字段。
而且每次登录获取的sig的值是一样的。那么是意味着这个sig可以永久使用？ 其他api调用是直接带上这个sig即可，以后都无需登录了？

**Comment by masato25** [comment]
@blackholll  目前的作法, 是的. 只要使用者没有做登出的动作的话. 现在的sig是不会过期的.
建议在task 模组中 撰写定期程序将过期的session从资料库裡面清除. 如果你有相关的实做欢迎贡献到社群来
