### ISSUE TITLE
告警邮件不生效

### ISSUE THREAD

**Issue by luhuan01** [open-falcon/falcon-plus#279]
curl http://8.15.4.85:4000/sender/mail -d "tos=xxxx@163.com&subject=告警测试&content=告警测试"
x509: certificate is valid for 域名, not 邮件服务器域名
配置文件：
/root/project/src/github.com/open-falcon/mail-provider/cfg.json
```
{
    "debug": true,
    "http": {
        "listen": "0.0.0.0:4000",
        "token": ""
    },
    "smtp": {
        "addr": "邮件服务器域名:25",
        "username": "user",
        "password": "passwd",
        "from": "xxxx@163.com"
    }
}
```
配置文件:
/home/work/open-falcon/alarm/config/cfg.json
![image](https://user-images.githubusercontent.com/19201057/31871236-66855f56-b7e5-11e7-80c4-916f0546bf6a.png)

**Comment by luhuan01** [comment]
```
def main_py():
    ts = int(time.time())
    host_name = hostname()
    with file('ip.txt', 'r') as f:
        load_list = json.load(f)
        result_list = []
        ping_list = []
        for line in load_list:
            vm_ping(line['ip'], line['hostname'], result_list)
        for line in result_list:
            ping_dict = {}
            ping_dict['endpoint'] = host_name
            ping_dict['metric'] = "ping-%s-%s" % (line['ip'], line['endpoint'])
            ping_dict['timestamp'] = ts
            ping_dict['step'] = 5
            ping_dict['value'] = line['value']
            ping_dict['counterType'] = "GAUGE"
            ping_dict['tags'] = ""
            ping_list.append(ping_dict)
    data = json.dumps(ping_list)
    ping_lists(data)
    r2 = requests.post("http://8.15.4.85:1988/v1/push", data)
    print r2.text

if __name__ == '__main__':
    while True:
        main_py()
        time.sleep(5)
```

![image](https://user-images.githubusercontent.com/19201057/31928724-c6cebb6e-b8cb-11e7-972f-a9141efccf19.png)

**Comment by luhuan01** [comment]
![image](https://user-images.githubusercontent.com/19201057/31928985-b5246520-b8cc-11e7-8db4-e09e1037a72c.png)

**Comment by luhuan01** [comment]
```
[{"endpoint": "tmp-network-ecs-img.novalocal", "tags": "", "timestamp": 1508768070, "metric": "ping-192.168.4.161-vm2-kvm-vpc1", "value": 1, "counterType": "GAUGE", "step": 5}, {"endpoint": "tmp-network-ecs-img.novalocal", "tags": "", "timestamp": 1508768070, "metric": "ping-172.16.1.15-vm4-kvm-vpc2", "value": 1, "counterType": "GAUGE", "step": 5}, {"endpoint": "tmp-network-ecs-img.novalocal", "tags": "", "timestamp": 1508768070, "metric": "ping-8.15.4.85-falcon-server", "value": 0, "counterType": "GAUGE", "step": 5}, {"endpoint": "tmp-network-ecs-img.novalocal", "tags": "", "timestamp": 1508768070, "metric": "ping-192.168.3.87-vm5-kvm-vpc1", "value": 1, "counterType": "GAUGE", "step": 5}, {"endpoint": "tmp-network-ecs-img.novalocal", "tags": "", "timestamp": 1508768070, "metric": "ping-192.168.4.194-vm6-xen-vpc1", "value": 1, "counterType": "GAUGE", "step": 5}, {"endpoint": "tmp-network-ecs-img.novalocal", "tags": "", "timestamp": 1508768070, "metric": "ping-192.168.3.79-tmp-network-ecs-img.novalocal", "value": 1, "counterType": "GAUGE", "step": 5}]
[{"endpoint": "tmp-network-ecs-img.novalocal", "tags": "", "timestamp": 1508768076, "metric": "ping-192.168.4.161-vm2-kvm-vpc1", "value": 1, "counterType": "GAUGE", "step": 5}, {"endpoint": "tmp-network-ecs-img.novalocal", "tags": "", "timestamp": 1508768076, "metric": "ping-172.16.1.15-vm4-kvm-vpc2", "value": 1, "counterType": "GAUGE", "step": 5}, {"endpoint": "tmp-network-ecs-img.novalocal", "tags": "", "timestamp": 1508768076, "metric": "ping-8.15.4.85-falcon-server", "value": 1, "counterType": "GAUGE", "step": 5}, {"endpoint": "tmp-network-ecs-img.novalocal", "tags": "", "timestamp": 1508768076, "metric": "ping-192.168.3.87-vm5-kvm-vpc1", "value": 1, "counterType": "GAUGE", "step": 5}, {"endpoint": "tmp-network-ecs-img.novalocal", "tags": "", "timestamp": 1508768076, "metric": "ping-192.168.4.194-vm6-xen-vpc1", "value": 1, "counterType": "GAUGE", "step": 5}, {"endpoint": "tmp-network-ecs-img.novalocal", "tags": "", "timestamp": 1508768076, "metric": "ping-192.168.3.79-tmp-network-ecs-img.novalocal", "value": 1, "counterType": "GAUGE", "step": 5}]

```

**Comment by luhuan01** [comment]
![image](https://user-images.githubusercontent.com/19201057/31930671-2204d21e-b8d3-11e7-85b6-f4032b1a2986.png)

**Comment by luhuan01** [comment]
现在看其中一台机器tmp-network-ecs-img.novalocal的net.if.in.bytes/iface=eth0 conter，选取时间是2017.10.21 20:00 -----2017.10.25 09:10 这段时间的流量图：
![2017-10-25_091810](https://user-images.githubusercontent.com/19201057/31975728-d1bf7de8-b965-11e7-83b2-188194d61d9d.png)

**Comment by luhuan01** [comment]
![2017-10-25_092127](https://user-images.githubusercontent.com/19201057/31975853-9ad984d0-b966-11e7-9674-0d373c48427a.png)

**Comment by luhuan01** [comment]
可以看到上面每两个点之间的时间间隔是二十分钟，现在把时间选取为2017.10.25 08:25 -----2017.10.25 09:25，时间为一个小时
![2017-10-25_092600](https://user-images.githubusercontent.com/19201057/31975929-fe710748-b966-11e7-8ae2-381649867b57.png)

**Comment by luhuan01** [comment]
![2017-10-25_092751](https://user-images.githubusercontent.com/19201057/31975961-2b1b31d8-b967-11e7-8132-7a3225767e5b.png)

**Comment by luhuan01** [comment]
再放大图上的8:30---8:31之间的图：
![2017-10-25_092858](https://user-images.githubusercontent.com/19201057/31976005-6262388a-b967-11e7-9427-2db2ef7675b5.png)

明确最小的采样周期是一分钟，一分钟记录一个点，那这样的话和选取时间10月21号到10月25号这个长的区间段的采样二十分钟有冲突，疑问：同一个counter同一张图，采样周期分别为20分钟和1分钟，这个怎么理解呢

**Comment by luhuan01** [comment]
自定义push上去的数据，实际设置的step是5秒，每隔5秒执行一次ping操作
查询一小时的图：
![image](https://user-images.githubusercontent.com/19201057/31976987-4bf1ee5a-b96d-11e7-9149-4d154c9ebb20.png)

**Comment by luhuan01** [comment]
![image](https://user-images.githubusercontent.com/19201057/31977067-b8e58486-b96d-11e7-971c-22ec1a01eaae.png)

**Comment by luhuan01** [comment]
如果选取的周期是一天，图上采样就是2分半一个点：
![2017-10-25_101938](https://user-images.githubusercontent.com/19201057/31977198-30aaee48-b96e-11e7-9757-e9cf537b0db5.png)

**Comment by luhuan01** [comment]
![2017-10-25_133011](https://user-images.githubusercontent.com/19201057/31981964-c9a82c4a-b988-11e7-9376-05151b275bf8.png)

**Comment by luhuan01** [comment]
![2017-10-25_133213](https://user-images.githubusercontent.com/19201057/31982018-10cb5c28-b989-11e7-8f52-1ac100a0791a.png)

**Comment by laiwei** [comment]
这个issue里面分为两个问题 @luhuan01 

1. 邮件网关报错 x509: certificate is valid，和falcon本身没有关系，请Google查找邮件网关证书配置相关内容

2. 近一个小时 和 近一天，不同的跨度返回的数据精度是不一样的，这是falcon的数据采样机制决定的。更多细节可以参考 https://book.open-falcon.org/zh_0_2/dev/change_graph_rra.html
