### ISSUE TITLE
告警邮件的模板在哪里修改？

### ISSUE THREAD

**Issue by imzye** [open-falcon/falcon-plus#280]
是否可以自定义报警邮件的样式呢？想增加一些html标签，让报警邮件好看一些。

**Comment by wenskys** [comment]
同问，想自定义下msg、tm和mail的。@imzye 要是实现了多交流下

**Comment by liangyanbina** [comment]
告警消息在alarm里生成，需要在alarm里做修改。

**Comment by laiwei** [comment]
@imzye 可以修改alarm的代码

或者利用callback机制自行组织告警消息（不推荐）

**Comment by imzye** [comment]
好的，谢谢啦，@laiwei

**Comment by wenskys** [comment]
@imzye 自己写个脚本封装了
