### ISSUE TITLE
[FAQ]graph中，对于同一个Counter，收到的数据Timestamp，和在Store中第一个数据的Timestamp相比，时间较小，则会丢弃，这是为什么呢。

### ISSUE THREAD

**Issue by YouZhengChuan** [open-falcon/falcon-plus#292]
https://github.com/open-falcon/falcon-plus/blob/1ec5d184022263ed7411a0ad3b04058bbfd39e86/modules/graph/api/graph.go#L112

在这行代码中可以看到，对于同一个Counter，在收到数据的时候，如果该数据的Timestamp小于Store中第一个数据的Timestamp，则该数据会被丢弃。
我想知道，这个地方出于这个考虑，是因为rrdtool的限制么，不能在Store中插入数据，只能追加数据吗？

有一些时候，agent有可能会配置多个transfer，在某些极端的情况，出现网络抖动时，可能大部分transfer都会超时，agent在发送某一分钟数据的重试时间可能会大于1分钟，这样就算agent最后重试成功了，该数据也会被丢弃。

就是说如果之前旧的数据一直在重试没有成功，但是新的数据如果已经发送成功的话，等到旧的数据成功后，因为新的数据已经写入进去了，旧的数据也会被丢掉了。

**Comment by mdh67899** [comment]
https://github.com/open-falcon/falcon-plus/blob/1ec5d184022263ed7411a0ad3b04058bbfd39e86/modules/graph/store/store.go#L84

感觉这段代码是为了防止出现时间不同步而产生的脏数据吧

比如机器现在上传的数据时间戳是100， 但是突然重启，重启之后机器当前的时间戳是50, 那么重启后上传时间戳50-100的数据怎么处理？对于graph来说同一段时间上传了两次数据，两次数据合并掉那么后期看50-100这段时间的数据还具有可信性吗？
 
graph和judge里面存的数据是按照时间线性排序的，新上传的数据时间戳必须大于已上传数据的时间戳，这样处理起来才不用考虑时间污染的问题，上传的“老数据”索性直接丢掉等机器的时间恢复“正常“之后再说

至于agent和transfer之间的网络抖动基本上无解，judge收到了ts为100上传数据判断是合法的，不需要触发报警，网络抖动又收到了ts为80数据，是需要触发报警的，这种情况怎么处理？索性把ts为80的数据丢掉，按ts最大数据可信性最高，否则对网络抖动还能怎么办呢？顶多产生一条上报数据时间戳乱序的日志或者报警

**Comment by laiwei** [comment]
- Q: `我想知道，这个地方出于这个考虑，是因为rrdtool的限制么，不能在Store中插入数据，只能追加数据吗？`
- A: 是的，在rrdtool的设计模式下，数据只能追加，不能插入。所以falcon在graph中提前对数据做了一个按照时间戳的排序；

这个排序只是针对同一个counter的多个数据点进行排序，只要你不存在多个agent 上报同一个counter，那么就不会出现你说的 网络抖动被丢数据的问题:)

@YouZhengChuan @mdh67899
