### ISSUE TITLE
v2.1 全英文版本

### ISSUE THREAD

**Issue by ghostlyman** [open-falcon/falcon-plus#293]
是否有针对v2.1的英文版本，即所有的配置和显示页面均为英文。
或是通过修改或替换某些配置文件，将可能存在中文的语言全部替换成英文。

谢谢

**Comment by laiwei** [comment]
- Q: open-falcon 有英文版本吗？
- A: open-falcon v0.2开始，dashboard部分支持i18n，点这里[参与](https://github.com/open-falcon/dashboard/blob/master/i18n.md)。

参考：[faq](http://book.open-falcon.org/zh_0_2/faq/)

@ghostlyman
