### ISSUE TITLE
更新用户组报错: 400, record not found

### ISSUE THREAD

**Issue by wangdi244** [open-falcon/falcon-plus#295]
![image](https://user-images.githubusercontent.com/13075509/33069259-eda2f7f8-ceee-11e7-8e92-1ba0454b17f8.png)
如图更新用户组报错，我点击会报这个错误，别人点击能正常更新。。。。。。。

**Comment by laiwei** [comment]
@wangdi244 没有复现这个现象:) 

你可以把api模块的日志级别设置为debug，然后看一下api模块关于这个操作的日志，方便的话贴到这个issue下面 :)

**Comment by laiwei** [comment]
@wangdi244 有新的信息更新吗？

**Comment by wangdi244** [comment]
@laiwei 应该和我修改了代码有关系，目前恢复了用go代码获取用户组的方式，没问题了！
