### ISSUE TITLE
Docker 登陆密码不对时不提示“密码错误”之类信息却提示“zero length field name in format”

### ISSUE THREAD

**Issue by hxzqlh** [open-falcon/falcon-plus#296]
如题。使用docker 容器 https://github.com/open-falcon/falcon-plus/blob/master/docker/README.md 登陆账户，如果账号和密码不匹配，输出 “zero length field name in format”，这个错误是 python2.6 导致的吧？

**Comment by laiwei** [comment]
@hxzqlh 
https://github.com/open-falcon/dashboard/issues/53
