### ISSUE TITLE
query module error: json: cannot unmarshal bool into Go value of type string

### ISSUE THREAD

**Issue by walnut-tom** [open-falcon/falcon-plus#3]
falcon-query/query.json error: json: cannot unmarshal bool into Go value of type string
GlobalConfig.Debug 应该是 bool 类型

**Comment by hitripod** [comment]
Fixed: https://github.com/open-falcon/falcon-plus/blob/a7f84c323dd24af17f79e409e8b2a3fe22e40ecd/modules/query/g/cfg.go#L32
