### ISSUE TITLE
PUSH的数据模型中(Metric)，能否支持一个Description字段

### ISSUE THREAD

**Issue by whg999** [open-falcon/falcon-plus#301]
有些事件触发的告警，想要走Open Falcon的通道统一做告警抑制、过滤等，但告警的一些定位信息无法附加上去（不属于Tag），希望能够在Metric中增加Description字段，只存储或发送邮件短信等，不涉及计算。

**Comment by laiwei** [comment]
这个支持起来，成本很高，包括后端的存储和计算成本。

**Comment by whg999** [comment]
感谢答复~能否把这个信息只传递给Judge、Alarm、Sender，而不用存储到数据库或进行计算呢？
