### ISSUE TITLE
Judge对于达到最大告警次数的告警抑制，是否可以配置超时时间

### ISSUE THREAD

**Issue by whg999** [open-falcon/falcon-plus#302]
有时候告警已处理，但在Judge的数据中还是Problem状态，且达到告警次数，导致后续新产生的告警都不会触发通知了，等产生业务影响了运维人员才发现，需要支持一个超时时间，达到这个时间后，告警抑制的次数重置为0

**Comment by laiwei** [comment]
这是个不错的需求，后续可以考虑:)

当前建议你每天巡检alarm-dashboard 来发现这类问题

**Comment by itmajing** [comment]
请问该功能实现了吗？

**Comment by gaoquan6297** [comment]
请问该功能实现了吗？
