### ISSUE TITLE
多个graph设置的时候，有个别graph会stop

### ISSUE THREAD

**Issue by zhulh200868** [open-falcon/falcon-plus#304]
多个graph设置的时候，有个别graph会stop

**Comment by zhulh200868** [comment]
启动graph以后出现以下信息：
goroutine 30764 [syscall]:
syscall.Syscall(0x4, 0xc217e7e0c0, 0xc20f667050, 0x0, 0x0, 0x41ebb9, 0x90)
        /home/xiaoju/go/src/syscall/asm_linux_amd64.s:21 +0x5
syscall.Stat(0xc217e7e080, 0x3c, 0xc20f667050, 0x0, 0x0)
        /home/xiaoju/go/src/syscall/zsyscall_linux_amd64.go:1723 +0x92
os.Stat(0xc217e7e080, 0x3c, 0x0, 0x0, 0x0, 0x0)
        /home/xiaoju/go/src/os/file_unix.go:134 +0x75
github.com/toolkits/file.IsExist(0xc217e7e080, 0x3c, 0xc2201c7f48)
        /home/xiaoju/gopath/src/github.com/toolkits/file/file.go:119 +0x32
github.com/open-falcon/graph/g.IsRrdFileExist(0xc217e7e080, 0x3c, 0xc229a3ab60)
        /home/xiaoju/gopath/src/github.com/open-falcon/graph/g/utils.go:19 +0x32
github.com/open-falcon/graph/index.ReceiveItem(0xc244d79f00, 0xc229a3ab60, 0x20)
        /home/xiaoju/gopath/src/github.com/open-falcon/graph/index/index.go:41 +0x31e
github.com/open-falcon/graph/api.handleItems(0xc244d7d7d0, 0x6, 0x6)
        /home/xiaoju/gopath/src/github.com/open-falcon/graph/api/graph.go:82 +0x276
created by github.com/open-falcon/graph/api.(*Graph).Send
        /home/xiaoju/gopath/src/github.com/open-falcon/graph/api/graph.go:40 +0x58
以后graph就stop了。

**Comment by laiwei** [comment]
@zhulh200868 

多个graph设置，具体指的是什么？

**Comment by zhulh200868** [comment]
在transfer的配置文件中设置多个graph，会出现runtime: program exceeds 10000-thread limit fatal error: thread exhaustion错误！

**Comment by laiwei** [comment]
duplicated https://github.com/open-falcon/falcon-plus/issues/306
