### ISSUE TITLE
graph出现：runtime: program exceeds 10000-thread limit fatal error: thread exhaustion

### ISSUE THREAD

**Issue by zhulh200868** [open-falcon/falcon-plus#306]
runtime: program exceeds 10000-thread limit
fatal error: thread exhaustion

**Comment by zhulh200868** [comment]
1.降低系统调用的并发
2.使用SetMaxThreads增加线程阀值，但是不建议这样使用。
降低系统调用的并发是得调整graph吗？

**Comment by laiwei** [comment]
根据golang的官方文档：https://golang.org/pkg/runtime/debug/#SetMaxThreads

>SetMaxThreads sets the maximum number of operating system threads that the Go program can use. If it attempts to use more than this many, the program crashes. SetMaxThreads returns the previous setting. The initial setting is 10,000 threads.

>The limit controls the number of operating system threads, not the number of goroutines. A Go program creates a new thread only when a goroutine is ready to run but all the existing threads are blocked in system calls, cgo calls, or are locked to other goroutines due to use of runtime.LockOSThread.


一个golang程序所创建的线程数量的默认上限是10000，golang程序只有在需要一个goroutine来运行任务，但是所有已有的线程都被block的时候，才会去新建一个线程。

所以需要追踪一下，看看在你的环境中，graph的所有线程是被block在什么地方了。

@zhulh200868

**Comment by zhulh200868** [comment]
恩，这块是的要追踪一下！
目前监控这块正在从0.1升级到0.2.1之中，所以需要等到0.2.1的时候可以查看。
目前对其中的一台graph升级到0.2.1，但是会出现内存溢出的情况，导致主机无法连接。
在tranfer连接graph的时候的策略是什么？

**Comment by zhulh200868** [comment]
目前监控这块正在从0.1升级到0.2.1之中，所以需要等到0.2.1的时候可以查看。
目前对其中的一台graph升级到0.2.1，但是会出现内存溢出的情况，导致主机无法连接。
在tranfer连接graph的时候的策略是什么？

**Comment by laiwei** [comment]
graph本身就是会占用内存，因为为了提升写磁盘的效率，最多会有半个小时的数据缓冲在内存中。所以，你需要增大graph的物理内存。 @zhulh200868

**Comment by zhulh200868** [comment]
你指的增大graph的物理内存，有具体的参数吗？还是在代码里面的？@laiwei

**Comment by zhulh200868** [comment]
@laiwei
我已经将graph全部升级为0.2.1了，目前跟踪日志发现如下：
其中1台：
2017/12/22 11:38:51 rrdtool.go:241: flush hash idx:000 size:1800 disk:00153192 net:00000000
----这台看应该是在处理数据。
其中3台：
[GIN] 2017/12/22 - 13:20:29 | 200 |      10.434µs | 192.168.1.2 |   GET     /health
----这三台一直在刷这个日志。
其中1台：
2017/12/22 11:59:55 debug.go:45: [GIN-debug] Listening and serving HTTP on 0.0.0.0:6071
----这台一直停留在这里。
是不是只有第一台在工作？
