### ISSUE TITLE
agent mountpoint 失效

### ISSUE THREAD

**Issue by kxst** [open-falcon/falcon-plus#307]
agent 的 cfg 文件里 collector 中指定了  "mountPoint": ["/tmp","/usr","/var","/dev/shm","/saetmp","/data1","/data2"]  只收集这几个 mount 的数据，可是 为啥依旧还收集到了  
mount=/run/docker/netns/61b5557888cf     和  
mount=/data0/docker/containers 
这 2个挂载点的数据呢？感谢

**Comment by zhulh200868** [comment]
能给发一些agent的日志吗？

**Comment by laiwei** [comment]
@kxst 请问falcon-agent是运行在宿主机上 还是 运行在容器里面的？

另外，请确认一下，是不是在配置mountPoint选型之前，你已经启动过agent，所以产生了另外两个挂载点的数据？

thx

**Comment by zhulh200868** [comment]
@laiwei
mountPoint 这挂载点的意思什么？
比如"mountPoint": ["/boot"]，这样配置以后只监控/boot了吗？
从日志看有这些：
time="2017-12-21T07:54:00+08:00" level=debug msg="mount point not matched with config/ignored." 
time="2017-12-21T07:54:00+08:00" level=debug msg="mount point not matched with config/etc/hostsignored." 
但是从endpoint的1988端口页面看的disk usage中还有别的目录?
是不是这是两个概念？

**Comment by laiwei** [comment]
mountPoint 指的就是 df 命令输出的最后一列：

![image](https://user-images.githubusercontent.com/792850/34240882-6b57f56c-e64c-11e7-9c55-4780353fff58.png)

**Comment by zhulh200868** [comment]
@laiwei，明白mountPoint的概念了。把agent放docker里面监控本机的挂载目录的话需要怎么设置？

**Comment by zhulh200868** [comment]
@laiwei，终于搞懂mountPoint的概念了。如果把agent放到docker里，怎么能监控宿主机的mountPoint？
