### ISSUE TITLE
Why do we need "plugins -> ./agent/plugins/" and "public -> ./agent/public" ?

### ISSUE THREAD

**Issue by zhulh200868** [open-falcon/falcon-plus#314]
When I delete the  "plugins -> ./agent/plugins/" and "public -> ./agent/public" then the http://ip:1988 will can't open ? So These are only for the agent web ？

**Comment by laiwei** [comment]
agent/public 目录是agent本机 :1988页面的html代码和素材。

agent/plugins 目录是 从远程中心端拉取下来的插件代码存放的目录。

@zhulh200868

**Comment by zhulh200868** [comment]
@laiwei，既然都是给agent的使用，为什么还有做一个软连？这个是不是没有太必要了？
