### ISSUE TITLE
make api时报错

### ISSUE THREAD

**Issue by gaogj** [open-falcon/falcon-plus#32]
使用make all 编译到api 模块时，报以下错误
# github.com/falcon-plus/modules/api
modules/api/main.go:73: cannot use routes (type *"github.com/falcon-plus/vendor/github.com/gin-gonic/gin".Engine) as type *"github.com/open-falcon/falcon-plus/vendor/github.com/gin-gonic/gin".Engine in argument to controller.StartGin
make: *** [api] 错误 2

尝试使用 make clean all 进行编译报错依旧

**Comment by gaogj** [comment]
golang 版本 1.8

**Comment by macaty** [comment]
me tooooo
[work@localhost falcon-plus]$ make api
go get ./modules/api
# github.com/falcon-plus/modules/api
modules/api/main.go:73: cannot use routes (type *"github.com/falcon-plus/vendor/github.com/gin-gonic/gin".Engine) as type *"github.com/gin-gonic/gin".Engine in argument to controller.StartGin
make: *** [api] Error 2

**Comment by macaty** [comment]
[work@localhost falcon-plus]$ go version
go version go1.8 linux/amd64

**Comment by masato25** [comment]
can you redo those step again? I can't see this error message on my side.
![tty](https://cloud.githubusercontent.com/assets/4387822/24734818/194250a8-1ab2-11e7-9dd1-c3264ab29a6f.gif)

**Comment by wenskys** [comment]
这个才刚上不久，还是等稳定版本吧

**Comment by macaty** [comment]
[work@localhost falcon-plus]$ make trash
go get -u github.com/rancher/trash
trash -k -cache package_cache_tmp
INFO[0000] Trash! Reading file: 'trash.yml'             
INFO[0000] Checking out 'github.com/Sirupsen/logrus', commit: '61e43dc76f7ee59a82bdf3d71033dc12bea4c77d' 
INFO[0000] Checking out 'github.com/gin-gonic/gin', commit: 'v1.1.4' 
INFO[0000] Checking out 'github.com/masato25/yaag', commit: 'b04f9b8a11ae0427e738ef1affd11a3184bb144d' 
INFO[0000] Checking out 'github.com/open-falcon/rrdlite', commit: 'b82d08f8da852b242ac87cd22f1cd01d33337d5d' 
INFO[0000] Checking out 'github.com/spf13/cobra', commit: '7be4beda01ec05d0b93d80b3facd2b6f44080d94' 
INFO[0000] Checking out 'github.com/spf13/viper', commit: '5ed0fc31f7f453625df314d8e66b9791e8d13003' 
INFO[0000] Checking out 'github.com/toolkits/nux', commit: '40e948efd15371c0381842833894bc71dea076e4' 
INFO[0000] Copying deps...                              
INFO[0000] Copying deps... Done                         
[work@localhost falcon-plus]$ make api
go get ./modules/api
# github.com/falcon-plus/modules/api
modules/api/main.go:73: cannot use routes (type *"github.com/falcon-plus/vendor/github.com/gin-gonic/gin".Engine) as type *"github.com/gin-gonic/gin".Engine in argument to controller.StartGin
make: *** [api] ´íÎó 2
[work@localhost falcon-plus]$

**Comment by masato25** [comment]
我把GOPATH整个清空,又在重新测试了一次.  依然没办法重现这个问题.

请问你们是直接`git clone github.com/open-falcon/falcon-plus/` or `go get github.com/open-falcon/falcon-plus/` 之后就直接编译吗？ 还是其实你们有更改过 `module/api/main.go` 档案呢？ 

或是请你附上你的 module/api/main.go 档案. 我可以帮你看看问题来源

**Comment by macaty** [comment]
work@ubuntu:~$export HOME=/home/work
work@ubuntu:~$export WORKSPACE=$HOME/open-falcon
work@ubuntu:~$mkdir -p $WORKSPACE
work@ubuntu:~$cd $WORKSPACE

work@ubuntu:~/workspace$cd ~
work@ubuntu:~$wget http://www.golangtc.com/static/go/1.8/go1.8.linux-amd64.tar.gz
work@ubuntu:~$tar zxf go1.8.linux-amd64.tar.gz
work@ubuntu:~$mkdir -p workspace/src
work@ubuntu:~$echo "" >> .bashrc
work@ubuntu:~$echo 'export GOROOT=$HOME/go' >> .bashrc
work@ubuntu:~$echo 'export GOPATH=$HOME/workspace' >> .bashrc
work@ubuntu:~$echo 'export PATH=$GOROOT/bin:$GOPATH/bin:$PATH' >> .bashrc
work@ubuntu:~$echo "" >> .bashrc


work@ubuntu:~/workspace$ cd $GOPATH/src
work@ubuntu:~/workspace/src$ mkdir github.com
work@ubuntu:~/workspace/src$ cd github.com
work@ubuntu:~/workspace/src/github.com$ git clone https://github.com/open-falcon/falcon-plus.git
Cloning into 'falcon-plus'...
cd falcon-plus/remote: Counting objects: 4934, done.
remote: Compressing objects: 100% (378/378), done.
remote: Total 4934 (delta 225), reused 0 (delta 0), pack-reused 4553
Receiving objects: 100% (4934/4934), 12.98 MiB | 1.26 MiB/s, done.
Resolving deltas: 100% (2511/2511), done.
Checking connectivity... done.
work@ubuntu:~/workspace/src/github.com$ cd falcon-plus/

work@ubuntu:~/workspace/src/github.com/falcon-plus$ make trash
go get -u github.com/rancher/trash
trash -k -cache package_cache_tmp
INFO[0000] Trash! Reading file: 'trash.yml'             
INFO[0000] Preparing cache for 'github.com/Sirupsen/logrus' 
INFO[0003] Checking out 'github.com/Sirupsen/logrus', commit: '61e43dc76f7ee59a82bdf3d71033dc12bea4c77d' 
INFO[0003] Preparing cache for 'github.com/gin-gonic/gin' 
INFO[0103] Checking out 'github.com/gin-gonic/gin', commit: 'v1.1.4' 
INFO[0103] Preparing cache for 'github.com/masato25/yaag' 
INFO[0328] Checking out 'github.com/masato25/yaag', commit: 'b04f9b8a11ae0427e738ef1affd11a3184bb144d' 
INFO[0328] Preparing cache for 'github.com/open-falcon/rrdlite' 
INFO[0333] Checking out 'github.com/open-falcon/rrdlite', commit: 'b82d08f8da852b242ac87cd22f1cd01d33337d5d' 
INFO[0333] Preparing cache for 'github.com/spf13/cobra' 
INFO[0348] Checking out 'github.com/spf13/cobra', commit: '7be4beda01ec05d0b93d80b3facd2b6f44080d94' 
INFO[0348] Preparing cache for 'github.com/spf13/viper' 
INFO[0501] Checking out 'github.com/spf13/viper', commit: '5ed0fc31f7f453625df314d8e66b9791e8d13003' 
INFO[0501] Preparing cache for 'github.com/toolkits/nux' 
INFO[0510] Checking out 'github.com/toolkits/nux', commit: '40e948efd15371c0381842833894bc71dea076e4' 
INFO[0510] Copying deps...                              
INFO[0510] Copying deps... Done                         


work@ubuntu:~/workspace/src/github.com/falcon-plus$ make api
go get ./modules/api
# cd .; git clone https://go.googlesource.com/net /home/work/workspace/src/golang.org/x/net
Cloning into '/home/work/workspace/src/golang.org/x/net'...
fatal: unable to access 'https://go.googlesource.com/net/': Failed to connect to go.googlesource.com port 443: Connection refused
package golang.org/x/net/context: exit status 128
package golang.org/x/sys/unix: unrecognized import path "golang.org/x/sys/unix" (https fetch: Get https://golang.org/x/sys/unix?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
package golang.org/x/text/transform: unrecognized import path "golang.org/x/text/transform" (https fetch: Get https://golang.org/x/text/transform?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
package golang.org/x/text/unicode/norm: unrecognized import path "golang.org/x/text/unicode/norm" (https fetch: Get https://golang.org/x/text/unicode/norm?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
Makefile:11: recipe for target 'api' failed
make: *** [api] Error 1

//安装依赖文件，看是不是这个golang的文件不对呢？
work@ubuntu:~/workspace/src/github.com/falcon-plus$mkdir -p /home/work/workspace/src/golang.org/x/
work@ubuntu:cd /home/work/workspace/src/golang.org/x/
work@ubuntu:~/workspace/src/golang.org/x$ git clone https://github.com/golang/sys 
Cloning into 'sys'...
remote: Counting objects: 2277, done.
remote: Compressing objects: 100% (47/47), done.
remote: Total 2277 (delta 24), reused 0 (delta 0), pack-reused 2230
Receiving objects: 100% (2277/2277), 1.55 MiB | 201.00 KiB/s, done.
Resolving deltas: 100% (1830/1830), done.
Checking connectivity... done.
work@ubuntu:~/workspace/src/golang.org/x$ git clone https://github.com/golang/net
Cloning into 'net'...
remote: Counting objects: 6440, done.
remote: Compressing objects: 100% (37/37), done.
remote: Total 6440 (delta 14), reused 0 (delta 0), pack-reused 6403
Receiving objects: 100% (6440/6440), 5.10 MiB | 582.00 KiB/s, done.
Resolving deltas: 100% (4495/4495), done.
Checking connectivity... done.
work@ubuntu:~/workspace/src/golang.org/x$ git clone https://github.com/golang/text
Cloning into 'text'...
remote: Counting objects: 3532, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 3532 (delta 0), reused 0 (delta 0), pack-reused 3529
Receiving objects: 100% (3532/3532), 12.31 MiB | 176.00 KiB/s, done.
Resolving deltas: 100% (2322/2322), done.
Checking connectivity... done.
work@ubuntu:~/workspace/src/github.com$ cd /home/work/workspace/src/github.com/open-falcon
work@ubuntu:~/workspace/src/github.com/falcon-plus$ make api
go get ./modules/api
# github.com/falcon-plus/modules/api
modules/api/main.go:73: cannot use routes (type *"github.com/falcon-plus/vendor/github.com/gin-gonic/gin".Engine) as type *"github.com/gin-gonic/gin".Engine in argument to controller.StartGin
Makefile:11: recipe for target 'api' failed
make: *** [api] Error 2

**Comment by macaty** [comment]
[Uploading main.go.zip…]()

**Comment by macaty** [comment]
能发布一个二进制的falcon-plus包含所有包的版本吗？能让我们先用一下。好像测试很多遍都编译不了

[main.go.zip](https://github.com/open-falcon/falcon-plus/files/906225/main.go.zip)

**Comment by masato25** [comment]
@macaty 我编译了一个x86_64的编译包 你可以尝试看看
https://github.com/masato25/falcon-plus/raw/pre-release_file/open-falcon-v2.0.0.tar.gz

**Comment by macaty** [comment]
谢谢。已经安装中 @masato25

**Comment by masato25** [comment]
@macaty 不客气.
我后来起了一个docker环境依照你上面给的log做了一次.
发现问题了, 问题应该释出在golang的tar包 `http://www.golangtc.com/static/go/1.8/go1.8.linux-amd64.tar.gz`
我这边是使用

**Comment by vance928** [comment]
看来只能在github.com/open-falcon/falcon-plus/ 这个指定的完整目录下编译
