### ISSUE TITLE
请问expression可以这样配置(tags!=zzz, metric=xxx)吗？或者说支持正则吗？

### ISSUE THREAD

**Issue by yinwoods** [open-falcon/falcon-plus#323]
在expression下配置报警策略，目前是(metric=xxx, endpoint=yyy)，因为metric下有多个tag，而有的tag不适合加到监控中去，请问能否这样配置：
`(tags!=zzz, metric=xxx, endpoint=yyy)`
如果不行的话，是否支持正则表达式呢？

**Comment by laiwei** [comment]
@yinwoods 当前版本不支持tag反选，tag value 不支持正则。预期18年下旬会推出滴滴实现的多样化策略，支持正则和反选。
