### ISSUE TITLE
NoData对于group下配置，不生效

### ISSUE THREAD

**Issue by penuel-leo** [open-falcon/falcon-plus#327]
RT

**Comment by zhulh200868** [comment]
您的host.maintain_begin和host.maintain_end的值分别会是多少？
能提供一下吗？

**Comment by penuel-leo** [comment]
这个我理解错了，maintain_begin和maintain_end是指机器维修时间吧，即不需要上报nodata和监控数据的时间是不是？
我之前理解为是需要监控的时间了
