### ISSUE TITLE
数据库5.0版本问题导致graph组件无法正常插入数据

### ISSUE THREAD

**Issue by udevil** [open-falcon/falcon-plus#33]
环境：
centos 6.5 x86_64
mysql  Ver 14.12 Distrib 5.0.96

报错位置：
index_update_incr_task.go:101: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'endpoint(endpoint, ts, t_create) VALUES (?, ?, now()) ON DUPLICATE KEY UPDATE id' at line 1

验证解决方案：
表名endpoint后需有空格，才能正常执行。

mysql 5.1版本上未发现此类问题。

**Comment by laiwei** [comment]
5.0版本也太老了：）
