### ISSUE TITLE
关于graph模块的查询支持Tag

### ISSUE THREAD

**Issue by ideascf** [open-falcon/falcon-plus#330]
你好，请问graph模块的查询接口，有支持Tag的计划吗？我看现在代码里面的查询参数中没有Tag。
![image](https://user-images.githubusercontent.com/5330706/34409100-8f44608a-ec02-11e7-8066-aae7aec001e1.png)

**Comment by laiwei** [comment]
@ideascf 支持tag查询需要对当前的设计做大的改动。且目前还没有一个比较好的索引方案。预期会在18年下旬，推出滴滴实现的支持tag查询的版本。
