### ISSUE TITLE
POST /api/v1/expression Create Expression接口不支持right_value字段为负数

### ISSUE THREAD

**Issue by zhsongqing** [open-falcon/falcon-plus#331]
func (this APICreateExrpessionInput) CheckFormat() (err error) {
	validOp := regexp.MustCompile(`^(>|=|<|!)(=)?$`)
	validRightValue := regexp.MustCompile(`^\d+$`)
	switch {
	case !validOp.MatchString(this.Op):
		err = errors.New("op's formating is not vaild")
	case !validRightValue.MatchString(this.RightValue):
		err = errors.New("right_value's formating is not vaild")
	}
	return
}

**Comment by laiwei** [comment]
fixed:)

**Comment by zhsongqing** [comment]
thx
