### ISSUE TITLE
open-falcon报警触发函数all 支持10个点？

### ISSUE THREAD

**Issue by leonjoyce** [open-falcon/falcon-plus#337]
open-falcon报警触发函数设置为 all（15）时，采样点15次都满足报警设置，但是没有报警。
把15设为10，即可报警。

请问报警触发函数all 有没有监控点数限制？

**Comment by laiwei** [comment]
点数有限制，不能超过judge配置文件中remain所指定的数字上限，如下图：
![image](https://user-images.githubusercontent.com/792850/34475168-3df3f5b8-efc4-11e7-809a-e70f7c7d0b86.png)

@leonjoyce
