### ISSUE TITLE
当有报警产生的时候,alarm程序会崩溃.

### ISSUE THREAD

**Issue by sunchangsong** [open-falcon/falcon-plus#341]
目前处于测试阶段发现了这个问题.
好像是一个空指针,不知道是我哪里设置有问题,还是怎么.
我使用的是docker启动的.默认配置都没有修改.只是修改了报警mail的url

redis里的值为:
{
    "id":"e_1_5aabcc9d427034120ab3fc275e2494e9",
    "strategy":null,
    "expression":{
        "id":1,
        "metric":"redis.used_memory",
        "tags":{
            "endpoint":"ip-10-5-11-248"
        },
        "func":"max(#1)",
        "operator":"\u003e",
        "rightValue":1,
        "maxStep":1000,
        "priority":3,
        "note":"test",
        "actionId":1
    },
    "status":"PROBLEM",
    "endpoint":"ip-10-5-11-248",
    "leftValue":11441376,
    "currentStep":6,
    "eventTime":1514903700,
    "pushedTags":{
        "port":"6379"
    }
}

报错的代码event_operation.go:83行,内容:eve.Strategy.Note
看样子应该是因为Strategy为null导致的.
我看了网上有人贴出来的redis里的值,expression是空的Strategy是有值的.这个版本的问题吗?
网上贴的值.如:
{
    "id":"s_7_9e899684e61cce209c14444cfb4e33bc",
    "strategy":{
        "id":7,
        "metric":"mem.memfree.percent",
        "tags":{
        },
        "func":"all(#3)",
        "operator":"\u003c=",
        "rightValue":100,
        "maxStep":3,
        "priority":0,
        "note":"memfree alarm test",
        "tpl":{
            "id":2,
            "name":"memery",
            "parentId":0,
            "actionId":1,
            "creator":"admin"
        }
    },
    "expression":null,
    "status":"PROBLEM",
    "endpoint":"bogon",
    "leftValue":33.335713095833036,
    "currentStep":3,
    "eventTime":1450764720,
    "pushedTags":{
    }
}

DEBU[0435] pop event: <Endpoint:ip-10-5-11-248, Status:PROBLEM, Strategy:<nil>, Expression:<Id:1, Metric:redis.used_memory, Tags:map[endpoint:ip-10-5-11-248], max(#1)>1 MaxStep:1000, P3 test ActionId:1>, LeftValue:11482344, CurrentStep:4, PushedTags:map[port:6379], TS:2018-01-02 14:25:00> 
[ORM]2018/01/02 14:25:01  -[Queries/default] - [  OK /    db.Query /     0.3ms] - [select * from event_cases where id = ?] - `e_1_5aabcc9d427034120ab3fc275e2494e9`
DEBU[0435] events: <Endpoint:ip-10-5-11-248, Status:PROBLEM, Strategy:<nil>, Expression:<Id:1, Metric:redis.used_memory, Tags:map[endpoint:ip-10-5-11-248], max(#1)>1 MaxStep:1000, P3 test ActionId:1>, LeftValue:11482344, CurrentStep:4, PushedTags:map[port:6379], TS:2018-01-02 14:25:00> 
DEBU[0435] expression is null: false                    
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x638737]

goroutine 20 [running]:
panic(0x96d580, 0xc420012080)
        /usr/lib/golang/src/runtime/panic.go:500 +0x1a1
github.com/open-falcon/falcon-plus/modules/alarm/model/event.InsertEvent(0xc4202a86c0)
        /go/src/github.com/open-falcon/falcon-plus/modules/alarm/model/event/event_operation.go:83 +0x847
github.com/open-falcon/falcon-plus/modules/alarm/cron.popEvent(0xc420294040, 0x4, 0x4, 0x0, 0x0, 0x0)
        /go/src/github.com/open-falcon/falcon-plus/modules/alarm/cron/event_reader.go:76 +0x5d1
github.com/open-falcon/falcon-plus/modules/alarm/cron.ReadLowEvent()
        /go/src/github.com/open-falcon/falcon-plus/modules/alarm/cron/event_reader.go:37 +0x61
created by main.main
        /go/src/github.com/open-falcon/falcon-plus/modules/alarm/main.go:46 +0x1e5

**Comment by zhulh200868** [comment]
@sunchangsong 出现panic: runtime error: invalid memory address or nil pointer dereference这个错误的可能是在读取某个配置的值出错导致！麻烦给贴一下配置信息。

**Comment by sunchangsong** [comment]
@zhulh200868 我刚又贴了一些redis的信息.不知道能不能帮助判断问题.
目前为测试阶段,我只是把mail的url改成了一个可以get访问通的地址,并没有处理这个请求
配置文件:
{
    "log_level": "debug",
    "http": {
        "enabled": true,
        "listen": "0.0.0.0:9912"
    },
    "redis": {
        "addr": "127.0.0.1:6379",
        "maxIdle": 5,
        "highQueues": [
            "event:p0",
            "event:p1",
            "event:p2"
        ],
        "lowQueues": [
            "event:p3",
            "event:p4",
            "event:p5",
            "event:p6"
        ],
        "userSmsQueue": "/queue/user/sms",
        "userMailQueue": "/queue/user/mail"
    },
    "api": {
        "sms": "http://127.0.0.1:10086/sms",
        "mail": "http://xxxxxxx.com/productservice/places/search?city=falcon&test=falcon",
        "dashboard": "http://127.0.0.1:8081",
        "plus_api":"http://127.0.0.1:8080",
        "plus_api_token": "default-token-used-in-server-side"
    },
    "falcon_portal": {
        "addr": "root:@tcp(127.0.0.1:3306)/alarms?charset=utf8&loc=Asia%2FChongqing",
        "idle": 10,
        "max": 100
    },
    "worker": {
        "sms": 10,
        "mail": 50
    },
    "housekeeper": {
        "event_retention_days": 7,
        "event_delete_batch": 100
    }
}

**Comment by laiwei** [comment]
请使用最新版本的代码，相关bugfix见 https://github.com/open-falcon/falcon-plus/commit/c236a8c5d2b3fb358d2eb1be48cae5f91d9059ce

**Comment by sunchangsong** [comment]
谢谢
