### ISSUE TITLE
cfg.example.json 文件未看到"maxconn"字段

### ISSUE THREAD

**Issue by fnegyun** [open-falcon/falcon-plus#349]
Usage使用说明书介绍hbs 的cfg文件时也未提及,应该是忘了吧。。

**Comment by zhulh200868** [comment]
- maxConns: 连接池相关配置，最大连接数
在cfg.example.json中缺失，会给补进。
打包出来的hbs的cfg.json文件是在源码中的config目录的hbs.json修改而来的。

**Comment by laiwei** [comment]
这是在pr https://github.com/open-falcon/falcon-plus/pull/185 引入的，忘记同步修改hbs cfg.example.json了。

在 pr https://github.com/open-falcon/falcon-plus/pull/366 修复了。
