### ISSUE TITLE
open-falcon无核心单点，hbs只能是单点啊。怎么做可以hbs无单点

### ISSUE THREAD

**Issue by mosesyu95** [open-falcon/falcon-plus#354]
open-falcon无核心单点，hbs只能是单点啊。怎么做可以hbs无单点

**Comment by zhulh200868** [comment]
目前单点的只有hbs/alarm/nodata三个了！

**Comment by zhulh200868** [comment]
@mosesyu95
hbs是可以部署多台的，只要前面挂载负载均衡(例如：lvs/nginx/haproxy等)。
目前alarm和nodata是单点的。

**Comment by mosesyu95** [comment]
晓得了，谢谢
