### ISSUE TITLE
发现不了agent

### ISSUE THREAD

**Issue by ling811** [open-falcon/falcon-plus#358]
我在生产环境上安装了十四台agent，但是其中两台agent，openfalcon怎么也发现不了，没有任何信息，但是已经出现了这两台的主机名字，请问怎么测试agent和openfalcon的互通性，还有这个问题怎么解决

**Comment by zhulh200868** [comment]
“但是已经出现了这两台的主机名字”  ----  这个是什么意思？
可以看一下falcon_portal.host中是否有这两台机器的信息？

**Comment by ling811** [comment]
就是dashboard主页中的Endpoint列表中有这个两台主机的名称，
但是刷新counter列表后，cpu、df、disk、mem、net等图标信息只出现表格，但是没有各个指标详情参数内容的
还有 falcon_portal.host 在这个表里有这个两条ip记录。

**Comment by zhulh200868** [comment]
@ling811  如果没有数据的话得要看一下graph是不是正常的。

**Comment by ling811** [comment]
可是另外12个都是正常显示指标数据，另外graph.endpoint库中也有那两个不显示信息的服务器名称

**Comment by xiaowei0516** [comment]
我也遇到过同样的问题，排查方法：
1. `agent` 时间是否和主机时间同步
2.  是否一开始时间不同步，　更改时间同步之后，　没有清空rrd文件和graph　module

**Comment by missuzhang** [comment]
很有可能是楼上说的，曾经发现一个无论如何都没有数据的情况，使用graph/last接口有数据，query就是查询不到，后来找到那个rrd文件，发现第一条记录写的是2037年（主机时间开始是2037年，后来虽然同步到现在时间，但是rrd只能向后写）。额，再等二十年就能写入数据了。这种情况需要手动删除这个rrd才可以。

**Comment by ling811** [comment]
好吧，我刚刚看了服务器时间，三台的时间差了很多，谢谢三位的解惑
