### ISSUE TITLE
从api获取数据异常

### ISSUE THREAD

**Issue by wangdi244** [open-falcon/falcon-plus#359]
通过 /api/v1/graph/history获取历史数据，api中抛出异常，代码中huqou获取机器的数量从1000调成了10000
![image](https://user-images.githubusercontent.com/13075509/34987514-62de36da-faf6-11e7-811c-76c01ab3aa87.png)

**Comment by laiwei** [comment]
信息不太完整，能再补充一下api 组件crash后的日志吗？ @wangdi244
