### ISSUE TITLE
graph存储策略建议

### ISSUE THREAD

**Issue by feie22** [open-falcon/falcon-plus#363]
// 1分钟一个点存 12小时
        c.RRA("AVERAGE", 0, 1, RRA1PointCnt)

        // 5m一个点存2d
	c.RRA("AVERAGE", 0, 5, RRA5PointCnt)
	c.RRA("MAX", 0, 5, RRA5PointCnt)
	c.RRA("MIN", 0, 5, RRA5PointCnt)

	// 20m一个点存7d
	c.RRA("AVERAGE", 0, 20, RRA20PointCnt)
	c.RRA("MAX", 0, 20, RRA20PointCnt)
	c.RRA("MIN", 0, 20, RRA20PointCnt)

	// 3小时一个点存3个月
	c.RRA("AVERAGE", 0, 180, RRA180PointCnt)
	c.RRA("MAX", 0, 180, RRA180PointCnt)
	c.RRA("MIN", 0, 180, RRA180PointCnt)

	// 12小时一个点存1year
	c.RRA("AVERAGE", 0, 720, RRA720PointCnt)
	c.RRA("MAX", 0, 720, RRA720PointCnt)
	c.RRA("MIN", 0, 720, RRA720PointCnt)

类似这种配置建议改成配置文件形式，方便修改

**Comment by laiwei** [comment]
修改归档策略，会对历史数据产生影响，不建议改动。

如果要改动，要非常清楚这么做的影响， 然后修改代码，发布。

如果放在配置文件中，担心给不关注这个功能的用户带来困惑和风险。 @feie22

**Comment by feie22** [comment]
感谢答复
