### ISSUE TITLE
tags有哪些特殊字符需要做转义？

### ISSUE THREAD

**Issue by luo985** [open-falcon/falcon-plus#365]
使用自定义push数据时，json数据里的tags字段的值，有哪些字符是属于特殊字符，是否有转义的方案？

**Comment by LeonardoLiuXD** [comment]
POST 又不是 GET ，没那么多需要转义的啊

**Comment by laiwei** [comment]
建议使用这些字符构成tag字符串 [a-zA-Z0-9_-] @luo985
