### ISSUE TITLE
Agent: 磁盘监控建议忽略 ISO文件的磁盘挂载点的磁盘使用率

### ISSUE THREAD

**Issue by taomaree** [open-falcon/falcon-plus#384]
当服务器 mount iso 文件时，agent 会自动上报改挂载点的磁盘使用率为 100%，进而触发相关告警。

建议：挂载 iso 文件时，不再上报该挂载点的磁盘使用率。

**Comment by LeonardoLiuXD** [comment]
配置策略的时候一般不都是用 label 控制哪个分区会产生告警么？

**Comment by taomaree** [comment]
首先，这个 metric 上报的数据意义不大。

假设挂载了iso文件到/mnt 目录，则会上报的具体信息为：
  metric：df.bytes.free.percent  
  mount:   /mnt 
  fstype:  iso9660
  value:   100%

这个监控指标的上报，个人认为没有多大的意义。

其次，由于该指标的上报，会导致告警规则配置复杂。我们此前的做法，是配置三条策略，判断 fstype 为 ext3 ext4 xfs 时，才报警。这样配策略复杂，而且不容易覆盖所有的情况。

经过综合考虑，我们目前线上已经是采取了不监控 iso 挂载目录的磁盘使用率。这样磁盘使用率的报警规则只需要配置一条，就可以适用各种场景，也不会出现遗漏。

**Comment by laiwei** [comment]
@taomaree  可以在agent的配置文件中，指定只上报某些mount点的信息

![image](https://user-images.githubusercontent.com/792850/36778357-7752b104-1ca7-11e8-8883-0506b4c3e50c.png)
