### ISSUE TITLE
redis中无任何数据，但是各项组件服务仍正常运行

### ISSUE THREAD

**Issue by yinwoods** [open-falcon/falcon-plus#386]
redis中无任何数据，但是各项组件服务仍正常运行；
请问这种情况是什么原因呢？我又该如何排查呢？
目前查找了所有日志，没有发现redis连接错误相关的报警信息

**Comment by LeonardoLiuXD** [comment]
1. redis 只用来保存 judge 传给 alarm 的告警事件，供judge处理，因此只有在有告警事件产生的时候 redis 里才会有数据。
2. 在告警事件较少的时候，alarm 会很快将 redis 中的事件全部处理完。

因此要想排查，只需要

1. 关闭 alarm 模块。
2. 配置策略，绑定 hostgroup，并出发告警，使告警事件产生积压。

**Comment by yinwoods** [comment]
感谢百忙之中抽空回复～万分感谢🙏
