### ISSUE TITLE
建议增加日志文件切割与最大值功能

### ISSUE THREAD

**Issue by cy7851** [open-falcon/falcon-plus#387]
之前遇到了api的日志撑爆了硬盘,研究了一下是因为日志级别是debug然后有很多机器请求接口导致日志几十G把一个比较小的硬盘撑爆了,而看代码,发现start里面的日志用的是golang的默认log,是直接用cmd.Stdout写到文件的,正在考虑怎么把这个换成能用writer然后可以切割文件和自动删除超过最大值的日志文件的.
如果有好的方案,请指导一下.

**Comment by binghun0518** [comment]
请问您最后如何解决的？

**Comment by zxl78585** [comment]
自己写个脚本就搞定了，给你日志切割的教程：
#! /bin/bash
LOG_PATH=/opt/tomcat/logs
TARGET_PATH=/home/backup/logs
cat ${LOG_PATH}/catalina.out > ${TARGET_PATH}/catalina.`date +%Y-%m-%d-%H%M%S`.out ; echo > ${LOG_PATH}/catalina.out
exit


0 0 * * * xxxxxxxxx.sh
日志自动删除的教程：
https://note.zxl78585.com/blog/post/zxl78585/%E8%87%AA%E5%8A%A8%E5%88%A0%E9%99%A4N%E5%A4%A9%E5%89%8D%E7%9A%84%E6%97%A5%E5%BF%97%E8%84%9A%E6%9C%AC
