### ISSUE TITLE
graph内存占用大

### ISSUE THREAD

**Issue by zhulh200868** [open-falcon/falcon-plus#397]
gc 2412 @345746.228s 4%: 1.6+24420+1.0 ms clock, 52+89/195347/551339+34 ms cpu, 85895->86600->81093 MB, 162801 MB goal, 32 P

这个表象是不是我得加graph机器的内存了？

**Comment by liangyanbina** [comment]
由于监控索引存在graph内存中，如果监控项太多的话，会比较占内存。

**Comment by GaoJiasheng** [comment]
graph缓存，主要分为两部分：
1、索引缓存，如果指标量不大的话，这部分比较少。
2、未落盘的数据缓存。这部分占用空间比较大。

目前graph默认落盘时间是30分钟，如果内存遇到瓶颈，且IO无瓶颈。可以尝试缩短落盘的周期，减少缓存。
在 g/g.go 里有几个参数，比如CACHE_DELAY、 CACHE_TIME，可以适当调整下。

**Comment by Jack0005** [comment]
还有一部分缓存是history信息，定时清理的，不过随着数据量的增大，也是会不断占用内存的。

**Comment by yangxiangyu** [comment]
在之前的 graph代码中 ，这里面的fmt.Sprintf频繁调用可能会导致内存无法回收 https://github.com/open-falcon/falcon-plus/blob/6f5275046a9e73533ce99fb098af475a4e061a73/common/utils/tags.go#L23


最新的[代码](https://github.com/open-falcon/falcon-plus/commit/81d468ff91dce9679dd20664c8eb9d4c7a75b836)使用了对象池，可以减少内存占用
https://github.com/open-falcon/falcon-plus/blob/7ee2ba2189bc24cc5d856b4f57e593a665bb5904/common/utils/tags.go#L24

另外 https://github.com/open-falcon/falcon-plus/blob/7ee2ba2189bc24cc5d856b4f57e593a665bb5904/modules/graph/cron/clean.go#L43 这里可以清除不用的cache，减少内存占用
