### ISSUE TITLE
请问配置templates与host group后，templates中的规则没有生效，大概是什么原因呢？

### ISSUE THREAD

**Issue by yinwoods** [open-falcon/falcon-plus#399]
在host group中配置了所有机器；在templates下添加了对机器磁盘、内存等基础信息的监控；
现在可以确定的是绑定了host group 与 template，但是在使用过程中并没有触发报警；
目前一个取代的做法是在expression中配置这些基础信息监控，请问下这种问题发生了，大概是什么原因呢？辛苦啦

**Comment by aprilnops** [comment]
提供几个可能原因，可以排查试下：
1. 挑一台故障的机器，dashboard查看监控数据有没有上来，是否达到报警阈值
2. 模板设置是否正确，包括生效时间、阈值、报警接收人、接收人电话
3. 模板是否被覆盖，子模板的相同策略（以metric+tag+priority区分）会覆盖掉父模板的策略
4. 机器是否设置了维护周期

**Comment by yinwoods** [comment]
@aprilnops  多谢回复；
1、目前是可以从dashboard上看到监控指标的，并且已经达到了报警阈值，所以可以认为监控数据上来了
2、模板设置是正确的，生效时间之前是默认的，后续调整到00:00-23:58还是没有收到任何报警；阈值的话已经设置为了磁盘可用空间比例小于100%即报警，还是没有收到任何报警；接受人也是没问题的，因为在expression和这个template配置了同一个报警组，而expression中的监控就能够触发报警
3、目前没有用到模版继承这一高级功能
4、机器之前没设置维护周期，现在设置了维护周期到2030年，仍然没有收到报警

再次感谢百忙之中回复问题，最后请问下能否通过某些日志来查看这些报警信息是否被触发了呢？

**Comment by yinwoods** [comment]
我新建了一个host group，并取消机器的维护周期就好了，自己对维护周期的理解出了偏差。。。非常不好意思

**Comment by qiyongxiao** [comment]
> 一个取代的做法是在expression中配置这

我也遇到这个问题，不知道什么原因

**Comment by qiyongxiao** [comment]
@yinwoods 你取消了maintain_begin核maintain_end就好了嘛？我一直以为这个是功能是主机的有效期呢

**Comment by yinwoods** [comment]
> @yinwoods 你取消了maintain_begin核maintain_end就好了嘛？我一直以为这个是功能是主机的有效期呢

不好意思，时间太久，我已经没什么印象了 。。。

**Comment by qiyongxiao** [comment]
@yinwoods 我设置了维护周期，把这个取消了之后一切都正常了
