### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by zhanglistar** [open-falcon/falcon-plus#401]
➜  falcon-plus git:(master) ✗ make all
go get ./modules/agent
go build -o bin/agent/falcon-agent ./modules/agent
go get ./modules/aggregator
go build -o bin/aggregator/falcon-aggregator ./modules/aggregator
go get ./modules/graph
# github.com/open-falcon/falcon-plus/modules/graph/rrdtool
modules/graph/rrdtool/utils.go:13:24: g.Config().IOWorkerNum undefined (type *g.GlobalConfig has no field or method IOWorkerNum)
modules/graph/rrdtool/utils.go:14:30: g.Config().FirstBytesSize undefined (type *g.GlobalConfig has no field or method FirstBytesSize)
Makefile:34: recipe for target 'graph' failed

**Comment by zhulh200868** [comment]
@zhanglistar 请在graph/config/cfg.json配置文件中添加 "ioWorkerNum": 64  参数。

**Comment by n4mine** [comment]
请将falcon的git版本更新到 1b3c224b6c6334a82b0790d3410ed926739df330 或以上，再进行编译。

**Comment by n4mine** [comment]
请将falcon的版本更新到 1b3c224 或以上，再进行编译。

**Comment by n4mine** [comment]
2周以上无反馈，close了。
