### ISSUE TITLE
Falcon agent abnormal exit with the err, Please helpp me

### ISSUE THREAD

**Issue by shaohk** [open-falcon/falcon-plus#402]
Falcon agent running period of time without any err message. But unexpected, the agent exit with the err
`acquirep: p->m=859536485376(92) p->status=1`
`fatal error: acquirep: invalid p state`
`fatal error: unexpected signal during runtime execution`

How could i solve it.
Thanks!

**Comment by zeusro** [comment]
You can check $WorkDir/$moduleName/log/logs/xxx.log

In your case,the module name is agent.

**Comment by MistShi** [comment]
@shaohk more information? or solved?

**Comment by shaohk** [comment]
solved, the reason is go'version lowwer. update go to 1.9, solved.

thx

**Comment by MistShi** [comment]
great ^_^
