### ISSUE TITLE
上报数据丢失

### ISSUE THREAD

**Issue by yuline** [open-falcon/falcon-plus#409]
对一个counter进行第一次上报后（而且只上报一次），在graph中查不到对应数据，dashboard可以搜索到counter，但是counter的值是NaN
![wechatimg209](https://user-images.githubusercontent.com/9051422/37902083-db90dd84-3125-11e8-9675-0d320f9a6209.jpeg)
![wechatimg212](https://user-images.githubusercontent.com/9051422/37902836-5399dd10-3128-11e8-8126-e7aeef9b7fdc.jpeg)

**Comment by n4mine** [comment]
非周期性的数据支持是有限的。
对于`只上报1个点的counter`来说，可能如你所见，能建立索引但不能看到曲线
请尝试继续上报以保证最低有`2个点`的数据上报。

**Comment by MistShi** [comment]
@yuline ，问题解决了么？

**Comment by yuline** [comment]
@MistShi 就是@n4mine说的原因，数据只上报了一次导致的。

**Comment by MistShi** [comment]
OK，好的~, 那issue我先close了
