### ISSUE TITLE
Nodata 设置不生效

### ISSUE THREAD

**Issue by yufeng108** [open-falcon/falcon-plus#410]
nodata 的设置信息如下：
    nodata.agent.live; group [app.server.us]/agent.live/; type=GAUGE,step=60

设置好之后在 app.server.us里关闭了一台测试机，结果agent.live并没有补上-1，后面一直是没有agent.live数据过来

**Comment by th002** [comment]
没人知道什么原因么

**Comment by th002** [comment]
是agent.alive,搞错了

**Comment by chengang2** [comment]
我配置了agent.alive 也没告警。不知道为什么
