### ISSUE TITLE
all(#3) min(#3)  actually they express the same meaning.

### ISSUE THREAD

**Issue by fishkao** [open-falcon/falcon-plus#412]
hi guys, in the alarm model, all(#3) min(#3)  actually they express the same meaning. I think eliminating  one the them will be great

**Comment by n4mine** [comment]
`all(#3) < 100` 不等同于 `min(#3) < 100`

**Comment by fishkao** [comment]
IF not , can you provide an example  that can prove   all(#3) < 100 不等同于 min(#3) < 100

**Comment by ttcats** [comment]
50，120，50
min(#3) < 100 成立
all(#3) < 100 不成立
