### ISSUE TITLE
transfer的日志文件无限增长直到用完磁盘空间

### ISSUE THREAD

**Issue by aloneGH** [open-falcon/falcon-plus#413]
在运行了几天时间之后，transfer.log文件的大小到达了28G。该文件最后几行打印如下:
2018/03/27 20:50:39 rpc.go:35: listener.Accept occur error: accept tcp [::]:8433: accept4: too many open files
2018/03/27 20:50:39 rpc.go:35: listener.Accept occur error: accept tcp [::]:8433: accept4: too many open files
2018/03/27 20:50:39 rpc.go:35: listener.Accept occur error: accept tcp [::]:8433: accept4: too many open files
2018/03/27 20:50:39 rpc.go:35: listener.Accept occur error: accept tcp [::]:8433: accept4: too many open files
2018/03/27 20:50:39 rpc.go:35: listener.Accept occur error: accept tcp [::]:8433: accept4: too many open files
2018/03/27 20:50:39 rpc.go:35: listener.Accept occur error: accept tcp [::]:8433: accept4: too many open files
2018/03/27 20:50:39 rpc.go:35: listener.Accept occur error: accept tcp [::]:8433: accept4: too many open files
2018/03/27 20:50:39 rpc.go:35: listener.Accept occur error: accept tcp [::]:8433: accept4: too many open files
2018/03/27 20:50:39 rpc.go:35: listener.Accept occur error: accept tcp [::]:8433: accept4: too many open files
问题的原因应该是 rpc.go 监听连接循环里面的打印造成的，希望能修复。

**Comment by n4mine** [comment]
1. 请给出你的配置文件
2. 请使用`ulimit -n`查看系统`open files`限制，这个限制不能太小

**Comment by aloneGH** [comment]
1. transfer的配置文件如下:
{
    "debug": true,
    "minStep": 30,
    "http": {
        "enabled": false,
        "listen": "0.0.0.0:6060"
    },
    "rpc": {
        "enabled": true,
        "listen": "0.0.0.0:8433"
    },
    "socket": {
        "enabled": false,
        "listen": "0.0.0.0:4444",
        "timeout": 3600
    },
    "judge": {
        "enabled": true,
        "batch": 200,
        "connTimeout": 1000,
        "callTimeout": 5000,
        "maxConns": 32,
        "maxIdle": 32,
        "replicas": 500,
        "cluster": {
            "judge-00" : "127.0.0.1:6080"
        }
    },
    "graph": {
        "enabled": true,
        "batch": 200,
        "connTimeout": 1000,
        "callTimeout": 5000,
        "maxConns": 32,
        "maxIdle": 32,
        "replicas": 500,
        "cluster": {
            "graph-00" : "127.0.0.1:6070"
        }
    },
    "tsdb": {
        "enabled": false,
        "batch": 200,
        "connTimeout": 1000,
        "callTimeout": 5000,
        "maxConns": 32,
        "maxIdle": 32,
        "retry": 3,
        "address": "127.0.0.1:8088"
    }
}

2. 系统的 open files 限制为65535。如果太小了，需要增加到多少合适？

3. 当too many open files这种情况的时候，能否控制下日志文件的大小？

**Comment by missuzhang** [comment]
@aloneGH  这个问题啊，首先代码中确实有点问题，listener.Accept()失败后没有sleep一下。可以在continue之前加一行 ```time.Sleep(time.Duration(time.Millisecond*10))  ``` 这样就不会疯狂打印日志了。不这对你来说也不一定是好事，不能及时的发现这个问题。应该查一下为什么会too many open files，这个应该比较好查。
1  lsof -p pid | wc -l   查看一下transfer的进程打开了多少个文件描述符
2 ulimit -n 看一下用户的ulimit设置
3 查看一下transfer的进程的limits信息
cat /proc/$(pidof falcon-transfer)/limits

对比一下数据应该会发现问题了

**Comment by aloneGH** [comment]
查看了 transfer 的进程 limits 信息，这里的 Soft limit 只有1024，比较小。
# cat /proc/$(pidof falcon-transfer)/limits
Limit                     Soft Limit           Hard Limit           Units     
Max cpu time              unlimited            unlimited            seconds   
Max file size             unlimited            unlimited            bytes     
Max data size             unlimited            unlimited            bytes     
Max stack size            8388608              unlimited            bytes     
Max core file size        0                    unlimited            bytes     
Max resident set          unlimited            unlimited            bytes     
Max processes             7282                 7282                 processes 
Max open files            1024                 4096                 files     
Max locked memory         65536                65536                bytes     
Max address space         unlimited            unlimited            bytes     
Max file locks            unlimited            unlimited            locks     
Max pending signals       7282                 7282                 signals   
Max msgqueue size         819200               819200               bytes     
Max nice priority         0                    0                    
Max realtime priority     0                    0                    
Max realtime timeout      unlimited            unlimited            us

**Comment by carrotshub** [comment]
遇到同样的问题，请问后来怎么解决的/?

**Comment by aloneGH** [comment]
参考 missuzhang 的建议, 有两个方式:
1. listener.Accept()失败后没有sleep一下。可以在continue之前加一行 time.Sleep(time.Duration(time.Millisecond*10)) 这样就不会疯狂打印日志了。但是这样治标不治本。
2. 修改 transfer 的进程的 limits 的大小, 把数值调大

**Comment by carrotshub** [comment]
感谢回复！
&nbsp; &nbsp; &nbsp;进程limits已经是系统最大值；如您所说，在listener.Accept（）失败后加sleep，这种方法治标不治本。我现在比较困惑的是为什么会大量出现listener.Accept()失败这种错误，根据目前了解猜测可能由于网络波动导致的socket失败，但是并未正确关闭。如果的确这样这个怎么规避呢？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"aloneGH"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月13日(星期三) 下午5:42
收件人:&nbsp;"open-falcon/falcon-plus"<falcon-plus@noreply.github.com&gt;;
抄送:&nbsp;"胡鹏辉"<1398141580@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [open-falcon/falcon-plus] transfer的日志文件无限增长直到用完磁盘空间 (#413)




参考 missuzhang 的建议, 有两个方式:
  
listener.Accept()失败后没有sleep一下。可以在continue之前加一行 time.Sleep(time.Duration(time.Millisecond*10)) 这样就不会疯狂打印日志了。但是这样治标不治本。
 
修改 transfer 的进程的 limits 的大小, 把数值调大

**Comment by walnut-tom** [comment]
agent 也存在这个问题，日志文件很大。cat /dev/null > var/app.log 也不行，好像写日志时使用了 seek操作。

**Comment by aloneGH** [comment]
这个问题是由于系统的网络连接数被用完了导致的，每打开建立一个连接，就要占用一个文件描述符，每个进程的文件描述符是有限制的，用完之后就无法接受新的连接，所以 listener.Accept() 就会失败。

而网络连接数用完的原因大概有两种比较常见，一个是连接数太多，确实有很多数据要传输，要建立很多连接；二是连接数据传输完之后没有及时关闭，也会导致连接数被用完。

可以查看系统的网络连接情况是不是建立了很多连接，然后需要找出为什么会建立这么多连接才能根本解决这个问题。

**Comment by carrotshub** [comment]
你讲的很对，我大约每分钟需要建立3000多个连接，但是这明显低于系统的上线65535，而transfer pid的max open_file 也是65535，通过lsof -p pid&nbsp;&gt;openfile.log，查看falcon-tr 23022 root 3289u&nbsp; &nbsp; &nbsp;IPv6 2753248496&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 0t0&nbsp; &nbsp; &nbsp;TCP ecs-4fa6:sieve-filter-&gt;175.6.234.14:61725 (ESTABLISHED)发现有大量这种建立状态的TCP连接。现在就是不能定位为什么建立的连接没有关闭。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"aloneGH"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月13日(星期三) 晚上6:13
收件人:&nbsp;"open-falcon/falcon-plus"<falcon-plus@noreply.github.com&gt;;
抄送:&nbsp;"胡鹏辉"<1398141580@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [open-falcon/falcon-plus] transfer的日志文件无限增长直到用完磁盘空间 (#413)




这个问题是由于系统的网络连接数被用完了导致的，每打开建立一个连接，就要占用一个文件描述符，每个进程的文件描述符是有限制的，用完之后就无法接受新的连接，所以 listener.Accept() 就会失败。
 
而网络连接数用完的原因大概有两种比较常见，一个是连接数太多，确实有很多数据要传输，要建立很多连接；二是连接数据传输完之后没有及时关闭，也会导致连接数被用完。
 
可以查看系统的网络连接情况是不是建立了很多连接，然后需要找出为什么会建立这么多连接才能根本解决这个问题。

**Comment by aloneGH** [comment]
结合自身的具体业务和这个项目的源码分析，可能会有结果。
