### ISSUE TITLE
关于rrd文件的删除问题

### ISSUE THREAD

**Issue by Darkera524** [open-falcon/falcon-plus#421]
目前graph部署了5个节点，最近一个节点存储空间快满了，那么就要扩容，但是扩容之后从原graph转走的一些指标文件并不会被自动删除是吗？请问那么我该如何去寻找并删除这些rrd数据文件呢？

**Comment by lts120784620** [comment]
find . -name '*.rrd' -mtime +7 | xargs rm -f  可以手动删除7天不上报数据的.rrd文件 ，没记错的话graph是根据endpoint,metric,tags做的md5，拼成“.../6070/md5[0:2]/md5_dsType_step.rrd”，也就是一种endpoint上报的metric+tag+数据类型+step都有单独的rrd文件生成，删除不会影响。在下拙见。

**Comment by Darkera524** [comment]
@lts120784620 十分感谢您的解答！
