### ISSUE TITLE
执行make all 总是报错

### ISSUE THREAD

**Issue by tonygshliu** [open-falcon/falcon-plus#43]
go get ./modules/agent
go install: no install location for directory /opt/go/src/github.com/open-falcon/falcon-plus/modules/agent outside GOPATH
	For more details see: 'go help gopath'
make: *** [agent] Error 1

**Comment by laiwei** [comment]
请确保你是在
$GOPATH/src/github.com/open-falcon/falcon-plus 这个目录

**Comment by tonygshliu** [comment]
我的系统是osx Sierra系统

**Comment by tonygshliu** [comment]
adminideMacBook-Pro:falcon-plus liugensheng$ pwd
/opt/go/src/github.com/open-falcon/falcon-plus
adminideMacBook-Pro:falcon-plus liugensheng$ sudo make all
Password:
go get -u github.com/rancher/trash
trash -k -cache package_cache_tmp
INFO[0000] Trash! Reading file: 'trash.yml'             
INFO[0000] Checking out 'github.com/Sirupsen/logrus', commit: '61e43dc76f7ee59a82bdf3d71033dc12bea4c77d' 
INFO[0000] Checking out 'github.com/gin-gonic/gin', commit: 'v1.1.4' 
INFO[0000] Checking out 'github.com/masato25/yaag', commit: 'b04f9b8a11ae0427e738ef1affd11a3184bb144d' 
INFO[0000] Checking out 'github.com/open-falcon/rrdlite', commit: 'b82d08f8da852b242ac87cd22f1cd01d33337d5d' 
INFO[0000] Checking out 'github.com/smartystreets/goconvey/convey', commit: 'HEAD' 
INFO[0000] Fetching latest commits from 'origin' for 'github.com/smartystreets/goconvey/convey' 
INFO[0001] Checking out 'github.com/spf13/cobra', commit: '7be4beda01ec05d0b93d80b3facd2b6f44080d94' 
INFO[0001] Checking out 'github.com/spf13/viper', commit: '5ed0fc31f7f453625df314d8e66b9791e8d13003' 
INFO[0001] Checking out 'github.com/toolkits/nux', commit: '40e948efd15371c0381842833894bc71dea076e4' 
INFO[0001] Copying deps...                              
INFO[0001] Copying deps... Done                         
go get ./modules/agent
go install: no install location for directory /opt/go/src/github.com/open-falcon/falcon-plus/modules/agent outside GOPATH
	For more details see: 'go help gopath'
make: *** [agent] Error 1

**Comment by laiwei** [comment]
@tonygshliu 

`sudo make all`  不要用sudo，这样环境变量就不一样了

**Comment by tonygshliu** [comment]
@laiwei 
Thanks very  much.

go get -u github.com/rancher/trash
package crypto/sha1: unrecognized import path "crypto/sha1" (import path does not begin with hostname)
package encoding/hex: unrecognized import path "encoding/hex" (import path does not begin with hostname)
package fmt: unrecognized import path "fmt" (import path does not begin with hostname)
package bufio: unrecognized import path "bufio" (import path does not begin with hostname)
package bytes: unrecognized import path "bytes" (import path does not begin with hostname)
package encoding/json: unrecognized import path "encoding/json" (import path does not begin with hostname)
package io: unrecognized import path "io" (import path does not begin with hostname)

这个问题应该怎么解决啊？

**Comment by masato25** [comment]
@tonygshliu  
可以请你尝试看看下面的这个解法吗？将GOROOT变数清除看看
https://github.com/Rivalo/discord-cli/issues/33
