### ISSUE TITLE
报警渠道设置

### ISSUE THREAD

**Issue by linusning** [open-falcon/falcon-plus#430]
![image](https://user-images.githubusercontent.com/10531436/39303897-6993fbd0-498a-11e8-9d40-b3e4bd9f1f32.png)

图示中红线部分如何自定义？

**Comment by ElevenShen** [comment]
在这个文件中可以修改：alarm/config/cfg.json
调整highQueues和lowQueues对应的event级别。

**Comment by laiwei** [comment]
@linusning 参考 https://github.com/open-falcon/falcon-plus/blob/master/modules/alarm/cron/event_consumer.go#L62 这里的代码进行自定义修改吧。
