### ISSUE TITLE
如何配置磁盘告警

### ISSUE THREAD

**Issue by chengang2** [open-falcon/falcon-plus#431]
比如我有多台机器。我不知道每台机器下挂载了多少盘。但是我希望做到每块盘都能监控到。告警发出的时候能具体知道是哪块盘空间不足。类似自动发现的功能

**Comment by chengang2** [comment]
open-falcon是已经采集了这种监控项了吗？我是自己写plugin实现的，但是遇到告警没办法提示那个挂载点空间不足的问题。

**Comment by laiwei** [comment]
请使用open-falcon的tag机制 @chengang2

**Comment by chengang2** [comment]
谢谢，已经搞定了。 @laiwei
