### ISSUE TITLE
绘图数据页面怎样才能够自动刷新

### ISSUE THREAD

**Issue by Debris2017** [open-falcon/falcon-plus#441]
把一些数据固定展示后，页面没有随着时间自动刷新。

**Comment by leoiceo** [comment]
整合grafana

**Comment by laiwei** [comment]
可以用grafana 或者 用浏览器刷新页面插件，或者修改dashboard的代码。

**Comment by RivanLuo** [comment]
> 可以用grafana 或者 用浏览器刷新页面插件，或者修改dashboard的代码。
你好，这个刷新的需求应该很正常，后期能否提供下，或者能否给出临时的修改方案？
