### ISSUE TITLE
Wrote an agent to monitoring RabbitMQ. 

### ISSUE THREAD

**Issue by barryz** [open-falcon/falcon-plus#443]
An agent written by go and monitoring RabbitMQ to get more detail metrics.
Here is the github address: https://github.com/barryz/rmqmonitor.

An agent for rabbitmq monitoring  is also provided in the official documentation, but the agent collects too few metrics.

**Comment by laiwei** [comment]
@barryz 👍 已添加到book中了，https://github.com/open-falcon/book/commit/f190bc456dc7717cbd636eefb4b841c9961a30a5
