### ISSUE TITLE
疑问：业务系统告警

### ISSUE THREAD

**Issue by chengang2** [open-falcon/falcon-plus#446]
falcon监控业务系统告警，业务方只打算出异常的时候发送告警。没问题不发送。这种情况下falcon要怎么做呢？我的理解是业务方在异常的时候至少要发送两条数据，一条异常的比如value=0，一条正常的value=1。这样falcon告警完就当做是处理成功了。后续如果有异常可以继续告警。但是业务方只希望发送异常的value=0.这种情况下，falcon要怎么处理呢

**Comment by mdh67899** [comment]
用nodata给metric补发默认值为: 1，异常值: 0由业务上报，判断条件用all(1) == 0 即可

还是建议由业务定期去push数据, 运维这一块维护nodata规则不方便维护

**Comment by chengang2** [comment]
@laiwei 用nodata的话tag必须写全，但是业务方希望告警的时候把具体的错误信息展示给告警接收方。所以我是把具体的错误做成一个tag。但是这样的话nodata就不能满足需求了。因为配置nodata的时候我不知道tag 应该填写什么。
