### ISSUE TITLE
screen的布局改成4列但是还是1列

### ISSUE THREAD

**Issue by zhaiyuyong** [open-falcon/falcon-plus#451]
![image](https://user-images.githubusercontent.com/4199724/40769104-b793c8c2-64e9-11e8-9f71-e2cc7d59cc57.png)

**Comment by laiwei** [comment]
什么浏览器？

**Comment by lann-zh** [comment]
同样有这个问题 
firefox ,chrome IE  等都试过 ，falcon 版本  Open-Falcon version 0.3, build 80edf71
![QQ截图20200910172212](https://user-images.githubusercontent.com/56669223/92710721-9ccdf080-f38a-11ea-990c-6b93fa3b0284.jpg)

**Comment by lann-zh** [comment]
同样有这个问题
firefox chrome IE 等浏览器都尝试过 falcon版本 Open-Falcon version 0.3, build 80edf71

![image](https://user-images.githubusercontent.com/56669223/92711404-18c83880-f38b-11ea-97db-427b0a037d4e.png)

**Comment by laiwei** [comment]
> 同样有这个问题
> firefox chrome IE 等浏览器都尝试过 falcon版本 Open-Falcon version 0.3, build [80edf71](https://github.com/open-falcon/falcon-plus/commit/80edf7164ccf46c05a5a0f423ccfe9bbb2c7888f)
> 
> ![image](https://user-images.githubusercontent.com/56669223/92711404-18c83880-f38b-11ea-97db-427b0a037d4e.png)

https://github.com/open-falcon/dashboard/commit/4383d1d4be5b6d773e449fb6dfaa5a079ece057b

可以更新一下代码。 @lann-zh

**Comment by lann-zh** [comment]
> > 同样有这个问题
> > firefox chrome IE 等浏览器都尝试过 falcon版本 Open-Falcon version 0.3, build [80edf71](https://github.com/open-falcon/falcon-plus/commit/80edf7164ccf46c05a5a0f423ccfe9bbb2c7888f)
> > ![image](https://user-images.githubusercontent.com/56669223/92711404-18c83880-f38b-11ea-97db-427b0a037d4e.png)
> 
> [open-falcon/dashboard@4383d1d](https://github.com/open-falcon/dashboard/commit/4383d1d4be5b6d773e449fb6dfaa5a079ece057b)
> 
> 可以更新一下代码。 @lann-zh

已经解决 谢谢
