### ISSUE TITLE
通过API调用Create Nodata时，会报错

### ISSUE THREAD

**Issue by edward9210** [open-falcon/falcon-plus#454]
原因是表mockcfg的t_create没有默认值导致的（环境为mysql 5.7.22）。
看了下源码，mockcfg_controller.go里面CreateNoData方法里，Mockcfg对象中没有t_create，外加上创建table的sql语句**`t_create` DATETIME NOT NULL COMMENT 'create time'**也没有默认值，这样才导致了插入失败。

**Comment by laiwei** [comment]
fixed https://github.com/open-falcon/falcon-plus/pull/460  @edward9210
