### ISSUE TITLE
du进程残留问题

### ISSUE THREAD

**Issue by missuzhang** [open-falcon/falcon-plus#456]
1 如果有海量小文件，使用du -bs 命令的执行时间会比较长，falcon agent调用du命令没有设置超时时间，会导致进程一直残留在操作系统中
2 du执行失败没有检查机制，采集不到数据无法触发告警。
3 du命令的执是时串行执行的 , 如果某条执行的慢，后面的结果也无法返回，同时增加了上面那种情况的出现几率

基于以上三点：
1 falcon agent调用du命令的时候，需要增加超时时间限制(30s)，超时未完成的进程杀掉。
2 采集数据失败：例如超时，文件路径不存在等等，都返回-1 ，以便可以通过配监控策略发现du执行失败。
3 du的执行改成并行。

**Comment by Jack0005** [comment]
du是对磁盘的基本监控，如果海量小文件的话，建议使用插件进行监控。而且，随着小文件数量的增加，不管如何设置超时时间，总会超限的。
