### ISSUE TITLE
update partial hosts in hostgroup API 404

### ISSUE THREAD

**Issue by lizeyun** [open-falcon/falcon-plus#466]
[root@elk_33_21 opsadmin]# curl --request PATCH http://192.168.11.51:8080/api/v1/hostgroup/1/host
404 page not found
[root@elk_33_21 opsadmin]

这个我请求的返回，请问下能给一个这个api怎么调用的文档吗，在群里问也没有人回答啊~

**Comment by xuesongbj** [comment]
@lizeyun  请看这个链接:http://open-falcon.org/falcon-plus/#/hostgroup_update

**Comment by MistShi** [comment]
@lizeyun 另外看下API的服务代码是否是最新的。
