### ISSUE TITLE
make all 需要执行多久呢？感觉看不到结束时间啊？

### ISSUE THREAD

**Issue by ZeusMartin** [open-falcon/falcon-plus#47]
make all 需要执行多久呢？感觉看不到结束时间啊？一直处于：
[work@localhost falcon-plus]$ make all
go get -u github.com/rancher/trash
trash -k -cache package_cache_tmp
INFO[0000] Trash! Reading file: 'trash.yml'             
INFO[0000] Checking out 'github.com/Sirupsen/logrus', commit: '61e43dc76f7ee59a82bdf3d71033dc12bea4c77d' 
INFO[0000] Checking out 'github.com/gin-gonic/gin', commit: 'v1.1.4' 
INFO[0000] Preparing cache for 'github.com/masato25/yaag' 

然后就一直在这个状态，

**Comment by masato25** [comment]
你可以参考看看以下这个issue的资讯
https://github.com/open-falcon/falcon-plus/issues/32

**Comment by laiwei** [comment]
翻墙:)
