### ISSUE TITLE
alarm popEvent和consume添加go 加速eventpop避免event:px队列堆积

### ISSUE THREAD

**Issue by ning1875** [open-falcon/falcon-plus#479]
func ReadLowEvent() {
	queues := g.Config().Redis.LowQueues
	if len(queues) == 0 {
		return
	}

	for {
		event, err := popEvent(queues)
		if err != nil {
			log.Errorf("ReadLowEvent get error",err)
			time.Sleep(time.Second)
			continue
		}
		go consume(event, false)
	}
}

**Comment by MistShi** [comment]
@ning1875 提个PR看看？

**Comment by ning1875** [comment]
#480

**Comment by ning1875** [comment]
恩 提了，#480
