### ISSUE TITLE
Comming Again!! curl http://127.0.0.1:8080/api/v1/aggreagtors 404 page not found

### ISSUE THREAD

**Issue by lizeyun** [open-falcon/falcon-plus#483]
[root@sz_xxr_xx tools]# curl http://127.0.0.1:8080/api/v1/aggreagtors
404 page not found
[root@sz_xx_xx tools]#
调用counter自动聚合到指定hostgroup中时又出现404的情况，上次是自动添加主机到主机群组，编译了最新版本的API就好了，这个问题不知道是不是类似情况呢？

**Comment by juesexingqiu** [comment]
你的api用错了，没有这个api

**Comment by MistShi** [comment]
http://api.open-falcon.com/doc/aggreator.html
@lizeyun ，有关aggeator的API，在这里可以参考。
