### ISSUE TITLE
SQL注入漏洞

### ISSUE THREAD

**Issue by zhazhami** [open-falcon/falcon-plus#488]
falcon-plus/modules/api/app/controller/host/hostgroup_controller.go文件48行，
falcon-plus/modules/api/app/controller/uic/user_controller.go文件489行存在SQL注入，
希望能修复

**Comment by xuesongbj** [comment]
q := c.DefaultQuery("q", ".+")
fmt.Sprintf("select * from user where name regexp '%s' limit %d,%d", q, page, limit)).Scan(&user) 

可以通过以上代码得出,q变量是由程序写死的。所以被注入可能行比较小。但从防sql注入语法角度来考虑的确存在这种问题。该问题已经提交pr[#492](https://github.com/open-falcon/falcon-plus/pull/492)

**Comment by zhazhami** [comment]
c.DefaultQuery("q", ".+")是会获取q参数的不是写死的，本来以为是私人的，刚发现是贵司的，已提交src希望能给几分。。

**Comment by xuesongbj** [comment]
/user/query?query=t27&limit=20 这个url会接收用户的参数，最红会转到api服务,的确存在这种SQL注入问题,以上提交pr可以解决该注入问题。更好的方式可以在用户入口添加一个middleware以解决这个问题。
