### ISSUE TITLE
使用dashboard配置的expression, alarm收到redis队列告警后异常退出

### ISSUE THREAD

**Issue by hoppipolla-** [open-falcon/falcon-plus#49]
expression是在dashboard上直接配置的一条。
看日志似乎是因为直接配置的expression，event的strategy为空，往表event_cases表查数据时，引用eve.Strategy.Note时报空指针了？

alarm报错日志如下(xxx代替实际的endpoint值)
···
time="2017-05-02T16:31:02+08:00" level=debug msg="pop event: <Endpoint:xxx, Status:PROBLEM, Strategy:<nil>, Expression:<Id:3, Metric:ss.estab, Tags:map[endpoint:xxx], all(#1)>100 MaxStep:3, P4  ActionId:4>, LeftValue:121, CurrentStep:1, PushedTags:map[], TS:2017-05-02 16:31:00>" 
[ORM]2017/05/02 16:31:02  -[Queries/default] - [  OK /    db.Query /     4.5ms] - [select * from event_cases where id = ?] - `e_3_2db1e7c23078c45b32d773bcb5306d14`
time="2017-05-02T16:31:02+08:00" level=debug msg="events: <Endpoint:xxx, Status:PROBLEM, Strategy:<nil>, Expression:<Id:3, Metric:ss.estab, Tags:map[endpoint:xxx], all(#1)>100 MaxStep:3, P4  ActionId:4>, LeftValue:121, CurrentStep:1, PushedTags:map[], TS:2017-05-02 16:31:00>" 
time="2017-05-02T16:31:02+08:00" level=debug msg="expression is null: false" 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x910c02]

goroutine 21 [running]:
github.com/open-falcon/falcon-plus/modules/alarm/model/event.InsertEvent(0xc42027e600)
        /root/go/src/github.com/open-falcon/falcon-plus/modules/alarm/model/event/event_operation.go:83 +0x7d2
github.com/open-falcon/falcon-plus/modules/alarm/cron.popEvent(0xc42025ddc0, 0x4, 0x4, 0x0, 0x0, 0x0)
        /root/go/src/github.com/open-falcon/falcon-plus/modules/alarm/cron/event_reader.go:76 +0x597
github.com/open-falcon/falcon-plus/modules/alarm/cron.ReadLowEvent()
        /root/go/src/github.com/open-falcon/falcon-plus/modules/alarm/cron/event_reader.go:37 +0x61
created by main.main
        /root/go/src/github.com/open-falcon/falcon-plus/modules/alarm/main.go:46 +0x1dd
···

**Comment by laiwei** [comment]
https://github.com/open-falcon/falcon-plus/commit/c236a8c5d2b3fb358d2eb1be48cae5f91d9059ce

fixed, thanks @hoppipolla-

**Comment by hoppipolla-** [comment]
测试ok
