### ISSUE TITLE
/api/v1/plugin 信息错误

### ISSUE THREAD

**Issue by xieguangtai** [open-falcon/falcon-plus#490]
```
rra=requests.post(url+'/api/v1/plugin',headers=falcon_header,data={'hostgroup_id':40, 'dir_path':'dgb'})

rra.content: 
b'{"error":"Key: \'APICreatePluginInput.GrpId\' Error:Field validation for \'GrpId\' failed on the \'required\' tag\\nKey: \'APICreatePluginInput.DirPaht\' Error:Field validation for \'DirPaht\' failed on the \'required\' tag"}\n'
```
```
rra=requests.post(url+'/api/v1/plugin',headers=falcon_header,data={'GrpId':40, 'DirPaht':'dgb'})

rra.content:
b'{"id":37,"grp_id":40,"dir":"dgb","create_user":"xieguangtai"}\n'
```
你们的api网站上可不是这么说的
http://api.open-falcon.com/#/plugin_create
```
Request
{
  "hostgroup_id": 343,
  "dir_path": "testpath"
}

Response
Status: 200
{
  "id": 1501,
  "grp_id": 343,
  "dir": "testpath",
  "create_user": "root"
}
```

**Comment by MistShi** [comment]
@xieguangtai 你使用的falcon的哪个版本？

**Comment by xieguangtai** [comment]
0.2.1源码里面也是这样的呀。用的就是0.2.1版。

**Comment by xieguangtai** [comment]
~/go/src/github.com/open-falcon/falcon-plus/modules/api/app/controller/host/plugins_controller.go 第50行。

**Comment by MistShi** [comment]
应该是没有指定 Content-Type， requests的默认是text/plain。
`type APICreatePluginInput struct {
	GrpId   int64  `json:"hostgroup_id" binding:"required"`
	DirPaht string `json:"dir_path" binding:"required"`
}`
需要是“application/json”

**Comment by xieguangtai** [comment]
这个DirPaht应该写作DirPath?
还有你们
～/go/src/github.com/open-falcon/falcon-plus/modules/api/app/controller/host/hostgroup_controller.go
第85行的   func BindHostToHostGroup(c *gin.Context) 和
第443行的 func bindHostToHostGroup(c *gin.Context, hostgroup f.HostGroup, hosts []string) 
看着有点懵逼

**Comment by xuesongbj** [comment]
1. PatchHostGroupHost 函数对BindHostToHostGroup函数打的Patch,主要做了检查group是否存在，以及限制了对group仅允许添加和删除操作。在进行add操作时,调用了bindHostToHostGroup函数。
       grpIDParams := c.Params.ByName("host_group")
	if grpIDParams == "" {
		h.JSONR(c, badstatus, "grp id is missing")
		return
	}
	grpID, err := strconv.Atoi(grpIDParams)
	if err != nil {
		log.Debugf("grpIDParams: %v", grpIDParams)
		h.JSONR(c, badstatus, err)
		return
	}

	action := inputs.Action
	if action != "add" && action != "remove" {
		h.JSONR(c, badstatus, "action must be add or remove")
		return
	}
2. 关于字段名字问题，已经提交pr. [#490](https://github.com/open-falcon/falcon-plus/pull/491)

**Comment by MistShi** [comment]
确实有些代码存在冗余，有优化的空间

**Comment by MistShi** [comment]
这个issue先close了，其他讨论可以另开
