### ISSUE TITLE
有没有docker部署方式

### ISSUE THREAD

**Issue by ljw4010** [open-falcon/falcon-plus#493]
RT

**Comment by MistShi** [comment]
目前还没有，不过却是可以提供的一种部署模式。

**Comment by walnut-tom** [comment]
其他的模块docker image自己能搞定，agent在docker里面跑监控主机要改github.com/toolkits/nux，我是在openshift里面

**Comment by MistShi** [comment]
@ljw4010 最新的commit，支持了docker部署：687031965939e7503ba04786fff0de9e30bfa4be

**Comment by ljw4010** [comment]
很棒，@MistShi，你要不搞，我就准备自己搞了，我先学习下你的！

**Comment by ljw4010** [comment]
不过README还没加Dockerfile怎么使用，你这个单机部署更适合吧，我后面可能也参照@walnut-tom 兄弟的做法，每个模块都打个镜像，先用compose搞一把。

**Comment by hitripod** [comment]
https://github.com/open-falcon/falcon-plus/blob/master/docker/README.md

**Comment by ljw4010** [comment]
> https://github.com/open-falcon/falcon-plus/blob/master/docker/README.md

good job

**Comment by liudonghua123** [comment]
希望可以提供相应的 docker-compose.yml
