### ISSUE TITLE
端口监控告警按照文档配置，hbs服务报异常

### ISSUE THREAD

**Issue by michaelzqw** [open-falcon/falcon-plus#494]
端口监控告警按照文档配置，hbs服务报异常
2018/07/17 16:35:53 expression.go:55: ERROR: parse each(endpoint=iZbp1gg82g9l9k9o9sylcaZ metric=net.port.listen/port=9090) fail

**Comment by mdh67899** [comment]
看代码是这里的问题:
https://github.com/open-falcon/falcon-plus/blob/6719104b12a688ac6148f55b577cdbb93196bf9e/modules/hbs/db/expression.go#L80

表达式写成 `each(endpoint=iZbp1gg82g9l9k9o9sylcaZ metric=net.port.listen port=9090) `试试

**Comment by MistShi** [comment]
@michaelzqw，参考@mdh67899的方案，解决了么？
