### ISSUE TITLE
falcon grafana插件alerting报警功能使用？

### ISSUE THREAD

**Issue by younglifestyle** [open-falcon/falcon-plus#499]
grafana : 5.2   
使用falcon插件，alerting功能无法正常使用，这里是有什么需要注意的吗？

**Comment by MistShi** [comment]
@younglifestyle alerting功能，是falcon的告警功能，还是grafana的？

**Comment by younglifestyle** [comment]
不好意思，我的问题不够清晰，是grafana的alerting

**Comment by MistShi** [comment]
哦，那可能要研究一下grafana的alerting功能，目前我们是把grafana仅作为数据展示的组件进行适配的。告警的配置和触发，是在falcon的平台上进行配置的。

**Comment by younglifestyle** [comment]
好的，非常高兴能得到你的回答，谢谢你
