### ISSUE TITLE
graph缩容

### ISSUE THREAD

**Issue by ning1875** [open-falcon/falcon-plus#502]
graph缩容是否可以这样配置transfer :将下掉的机器配置成双打 
        下掉前
		"cluster": {
			"graph-00": "要下掉的机器1:6070,存在机器1:6070",
			"graph-01": "要下掉的机器2:6070,存在机器2:6070",
			"graph-03": "存在机器1:6070",
			"graph-04": "存在机器2:6070",
        }
		下掉后
		"cluster": {
			"graph-00": "存在机器1:6070",
			"graph-01": "存在机器2:6070",
			"graph-03": "存在机器1:6070",
			"graph-04": "存在机器2:6070",
        }

**Comment by mdh67899** [comment]
graph貌似不支持缩容，不过有一个简单粗暴的方法倒是可以试试:
1. 把要下掉的两台机器的graph停掉，把这两台机器的rrd文件全部拷到另外其他机器的rrd目录中
2. transfer和api配置里面去除这两台机器的连接信息，重启进程

**Comment by MistShi** [comment]
@mdh67899 ，可行，简单粗暴~

**Comment by walnut-tom** [comment]
这样能查询出来吗？

**Comment by GaoJiasheng** [comment]
@ning1875 其实graph扩容的流程，完全可以用来缩容。这些简单粗暴的做法虽能解决问题，但是不太推荐。
打开migrate配置项，根据扩容的逻辑来进行缩容，与扩容的逻辑是一样的，graph集群经过一个rrd文件迁移的过程，可以很好的实现缩容。
关于扩容的细节，可以参考：
https://www.jianshu.com/p/a87ab10e09c7

**Comment by walnut-tom** [comment]
> @ning1875 其实graph扩容的流程，完全可以用来缩容。这些简单粗暴的做法虽能解决问题，但是不太推荐。
> 打开migrate配置项，根据扩容的逻辑来进行缩容，与扩容的逻辑是一样的，graph集群经过一个rrd文件迁移的过程，可以很好的实现缩容。
> 关于扩容的细节，可以参考：
> https://www.jianshu.com/p/a87ab10e09c7

能给个缩容时的具体配置例子吗？谢谢！有时候就是换台机器，复制文件过程比较长，想先扩后缩达到目的

**Comment by lts120784620** [comment]
@walnut-tom 原集群"cluster": {
"graph-00": "机器1:6070",
"graph-01": "机器2:6070"}
