### ISSUE TITLE
nodata aggregator 可以配多实例吗？

### ISSUE THREAD

**Issue by panpan-zhang** [open-falcon/falcon-plus#510]
RT

**Comment by panpan-zhang** [comment]
@MistShi

**Comment by MistShi** [comment]
目前不行，是整体的拉取的策略和数据处理

**Comment by panpan-zhang** [comment]
@MistShi aggregator 也不行吗？

**Comment by missuzhang** [comment]
@panpan-zhang  都是可以的，我们都这么用两年多了。原理很简单，就是nodata和aggregator都是把数据补到transfer，只要计算结果相同，多发几次也没啥影响。你爱部署几台就部几台，不过两台足够了，都挂了算你倒霉，多了也浪费资源。

**Comment by MistShi** [comment]
@missuzhang 哈哈，对对，我多虑了重复发的问题。

**Comment by panpan-zhang** [comment]
@missuzhang @MistShi 哈哈，非常感谢！
