### ISSUE TITLE
dashboard  -> template -> 告警联系人错误

### ISSUE THREAD

**Issue by cxjchocolate** [open-falcon/falcon-plus#52]
[0.2 ]打开dashboard http://host:8081/team/SWC-CS/users, 无论什么group都显示相同的users。而且有规律的显示最新创建的group users。经过测试，不仅是显示问题，告警也收到影响。目前虽然template设置有多个group，但是所有告警都只发送给唯一一个group中的users

**Comment by masato25** [comment]
@cxjchocolate 谢谢你的回报
我尝试在我这边测试了, 无法重现你的问题. 请问我的测试过程有错误吗？谢谢

![team_page](https://cloud.githubusercontent.com/assets/4387822/25650422/5631161c-300f-11e7-9dfe-7561648f3611.png)
![team_page_api1](https://cloud.githubusercontent.com/assets/4387822/25650426/5ba39ca0-300f-11e7-9180-54319b027579.png)
![team_page_api2](https://cloud.githubusercontent.com/assets/4387822/25650428/6031e5e2-300f-11e7-9c65-68204e89c9b7.png)

**Comment by cxjchocolate** [comment]
步骤一样的。不知道和环境有没有关系。
我是从0.1升级到0.2的，整个数据库没有改变。

**Comment by cxjchocolate** [comment]
我会再用api的方式做下测试，事后回报

**Comment by cxjchocolate** [comment]
我使用api接口测试：http://host:8080/api/v1/team/name/oo http://host:8080/api/v1/team/name/oo2
结果还是一样。

**Comment by cxjchocolate** [comment]
正好周末修复好了
https://github.com/open-falcon/falcon-plus/commit/0fc1e3dcbcb98e3308c98f7f209967bae21f97ae
