### ISSUE TITLE
请问alarm添加微信api不生效，手动curl发送消息可以成功，模板策略p为0，alarm页面有告警信息

### ISSUE THREAD

**Issue by FaithGX** [open-falcon/falcon-plus#521]
{
    "log_level": "debug",
    "http": {
        "enabled": true,
        "listen": "0.0.0.0:8134"
    },
    "redis": {
        "addr": "127.0.0.1:6389",
        "maxIdle": 5,
        "highQueues": [
            "event:p0",
            "event:p1",
            "event:p2"
        ],
        "lowQueues": [
            "event:p3",
            "event:p4",
            "event:p5",
            "event:p6"
        ],
        "userIMQueue": "/queue/user/im",
        "userSmsQueue": "/queue/user/sms",
        "userMailQueue": "/queue/user/mail"
    },
    "api": {
        "im": "http://127.0.0.1:8137/wechat",
        "sms": "http://127.0.0.1:10086/sms",
        "mail": "http://127.0.0.1:10086/mail",
        "dashboard": "http://127.0.0.1:8081",
        "plus_api":"http://127.0.0.1:8080",
        "plus_api_token": "default-token-used-in-server-side"
    },
    "falcon_portal": {
        "addr": "111111:11111@tcp(127.0.0.1:3306)/alarms?charset=utf8&loc=Asia%2FChongqing",
        "idle": 10,
        "max": 100
    },
    "worker": {
        "im": 10,
        "sms": 10,
        "mail": 50
    },
    "housekeeper": {
        "event_retention_days": 7,
                            

![image](https://user-images.githubusercontent.com/42664148/44563972-58675c00-a793-11e8-8412-41bbe1e19a42.png)

![image](https://user-images.githubusercontent.com/42664148/44564011-83ea4680-a793-11e8-9807-82a1dd521b42.png)

alarm版本为v0.2

redis中有告警信息
![image](https://user-images.githubusercontent.com/42664148/44576984-82844280-a7c2-11e8-8904-58faa9c546d5.png)

![image](https://user-images.githubusercontent.com/42664148/44576996-8912ba00-a7c2-11e8-943b-e912c646dfc6.png)

@laiwei  @MistShi

**Comment by FaithGX** [comment]
![image](https://user-images.githubusercontent.com/42664148/44564055-aed49a80-a793-11e8-8eff-7ba188da80f5.png)

**Comment by MistShi** [comment]
![image](https://user-images.githubusercontent.com/1921485/44768267-605c3d00-ab93-11e8-8571-7dd1097c3249.png)
@FaithGX ，alarm在发送告警的时候，会有如下的两种可能的日志，你看看是否有。如果是正确的日志，那么通常应该是调用提供的wechat的url的返回是OK。可以把wechat的API里面增加一些日志看看是哪里有问题。

**Comment by FaithGX** [comment]
您好，我在alarm日志中没有找到send的关键字相关日志，在页面中是有告警信息的，api手动测试也是可以的
![image](https://user-images.githubusercontent.com/42664148/44837120-48f08300-ac6b-11e8-9ec5-1281eda5e166.png)
![image](https://user-images.githubusercontent.com/42664148/44837129-50b02780-ac6b-11e8-98a4-87e0607aa74f.png)
![image](https://user-images.githubusercontent.com/42664148/44837161-6d4c5f80-ac6b-11e8-8163-cd29eb8a8891.png)
![image](https://user-images.githubusercontent.com/42664148/44837195-85bc7a00-ac6b-11e8-8b38-47e728441dc9.png)
@MistShi

**Comment by FaithGX** [comment]
已解决
