### ISSUE TITLE
缺少create dashboardgraph 接口

### ISSUE THREAD

**Issue by walnut-tom** [open-falcon/falcon-plus#528]

**Comment by walnut-tom** [comment]
<img width="657" alt="image" src="https://user-images.githubusercontent.com/17786463/44839595-c7502380-ac71-11e8-9e1d-eab3373b572d.png">
**找到了原来叫 “Create User”**

**Comment by MistShi** [comment]
。。。额，哈哈哈，👍

**Comment by MistShi** [comment]
@walnut-tom API文档已经改过来了，多谢提醒 ^_^
