### ISSUE TITLE
能否监控bond网卡

### ISSUE THREAD

**Issue by libeilin** [open-falcon/falcon-plus#529]
我这边设置了
metric: net.if.in.bytes
tag: iface=bond0
但是这样看来是无效的

**Comment by varlove** [comment]
贴个ifconfig的输出看一下？

**Comment by aprilnops** [comment]
按照如下配置试试：
agent的配置文件中加上bound:
```
 "collector": {
        "ifacePrefix": ["eth", "em", "bound"],
        "mountPoint": []
    }
```
然后查看机器上的文件/proc/net/dev是否有bound网卡的相关数据。

**Comment by libeilin** [comment]
谢谢，各位解决了，不太熟悉配置
这个可以解决了
"ifacePrefix": ["eth", "em", "bound"],
