### ISSUE TITLE
nodata  异常crash

### ISSUE THREAD

**Issue by g18600081938** [open-falcon/falcon-plus#53]
go 1.7.5  1.8.1
./open-falcon start 可以启动nodata  但是一会就crash 
下边是错误日志，找不到事哪里的问题，能帮忙看下吗

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x47da14]

goroutine 34 [running]:
panic(0x74af20, 0xc42000e0d0)
        /home/data/ops/app/go/src/runtime/panic.go:500 +0x1a1
github.com/open-falcon/falcon-plus/modules/nodata/collector.fetchItemsAndStore(0xc4200bd100, 0x2, 0x2, 0x2, 0x0, 0x0, 0x0)
        /home/data/ops/app/src/github.com/open-falcon/falcon-plus/modules/nodata/collector/collector_cron.go:136 +0x584
github.com/open-falcon/falcon-plus/modules/nodata/collector.collectDataOnce.func1(0xc42000f530, 0xc4200508c0, 0xc4200bd100, 0x2, 0x2, 0x2)
        /home/data/ops/app/src/github.com/open-falcon/falcon-plus/modules/nodata/collector/collector_cron.go:82 +0x73
created by github.com/open-falcon/falcon-plus/modules/nodata/collector.collectDataOnce
        /home/data/ops/app/src/github.com/open-falcon/falcon-plus/modules/nodata/collector/collector_cron.go:84 +0x26c

**Comment by cxjchocolate** [comment]
应该是nodata/config/cfg.json错误了。
错误的如下
```
    "query":{
        "connectTimeout": 5000,
        "requestTimeout": 30000,
        "queryAddr": "%%QUERY_HTTP%%"
    },
```

正确的应该是
```
    "query":{
        "connectTimeout": 5000,
        "requestTimeout": 30000,
        "queryAddr": "0.0.0.0:9966"
    },
```

**Comment by laiwei** [comment]
好的，谢谢反馈，我来看看这个问题：）
@g18600081938 @cxjchocolate

**Comment by g18600081938** [comment]
@cxjchocolate  @laiwei  falcon-plus  没有query 模块 
炜哥有plus change的文档吗

**Comment by laiwei** [comment]
@g18600081938 我会修改nodata去访问api组件的

changelog还没有整理

**Comment by laiwei** [comment]
@g18600081938 @cxjchocolate fixed:)

https://github.com/open-falcon/falcon-plus/commit/28dc15d85825e7f159a8f03352af47f9b1163ac0
