### ISSUE TITLE
在win10下用Visual Studio Code/Go1.11编译Agent出错

### ISSUE THREAD

**Issue by michaelzhangjiang** [open-falcon/falcon-plus#534]
一、环境：
  Win10 64位，Visual Studio Code1.27.1，Go1.11
  编译：github.com\open-falcon\falcon-plus\modules\agent\
二、编译报错日志：
  # github.com/open-falcon/falcon-plus/vendor/github.com/toolkits/sys
..\..\vendor\github.com\toolkits\sys\cmd.go:54:9: undefined: syscall.Kill
exit status 2
Process exiting with code: 1

求高手解答，感谢！

**Comment by missuzhang** [comment]
代码中的agent是基于linux系统的，所以在windows编译的时候找不到对应的库，可以启用交叉编译解决：
可以通过 GOOS=linux GOARCH=amd64  go build xxx 指定编译平台
Visual Studio Code没有用过应该有地方指定这两个变量

**Comment by michaelzhangjiang** [comment]
问题解决了，修改launch.json，在env中增加三个参数：
`_{
    // 使用 IntelliSense 了解相关属性。 
    // 悬停以查看现有属性的描述。
    // 欲了解更多信息，请访问: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "remotePath": "",
            "port": 2345,
            "host": "127.0.0.1",
            "program": "${workspaceRoot}/main.go",
            "env": {"CGO_ENABLED":"0","GOOS":"windows","GOARCH":"amd64"},
            "args": [],
            "showLog": false
        }
    ]
}_`

**Comment by michaelzhangjiang** [comment]
感谢missuzhang的提醒
