### ISSUE TITLE
tags的大小写问题

### ISSUE THREAD

**Issue by tonglin0325** [open-falcon/falcon-plus#536]
第一个post请求
[{"endpoint":"computer1","metric":"log-error-monitor","timestamp":1536565260,"step":60,"value":150,"counterType":"GAUGE","tags":"syslog=ERROR"}],能正常搜索到该metric,但是如果这时候post下面的body,则搜索不到
[{"endpoint":"computer1","metric":"log-error-monitor","timestamp":1536565260,"step":60,"value":150,"counterType":"GAUGE","tags":"syslog=Error"}],如果这时候修改一下endpoint的名字,则可以搜索到
[{"endpoint":"computer2","metric":"log-error-monitor","timestamp":1536565260,"step":60,"value":150,"counterType":"GAUGE","tags":"syslog=Error"}],但是如果继续改回
[{"endpoint":"computer2","metric":"log-error-monitor","timestamp":1536565260,"step":60,"value":150,"counterType":"GAUGE","tags":"syslog=ERROR"}],则搜索不到

**Comment by laiwei** [comment]
在falcon中，endpoint、metric、tags是不区分大小写的。@tonglin0325

**Comment by tonglin0325** [comment]
谢谢指导 @laiwei
