### ISSUE TITLE
yum install -y mysql-server 这种安装方法是错误的 

### ISSUE THREAD

**Issue by xiaosongdhls** [open-falcon/falcon-plus#538]
No package mysql-server available.
Error: Nothing to do
希望能改正一下

**Comment by missuzhang** [comment]
你的主机上没有对应的yum repo。
1  到https://dev.mysql.com/downloads/repo/yum/  下载对应系统的repo
2 rpm -ivh xxx.noarch.rpm
3 yum install mysql-server

**Comment by xiaosongdhls** [comment]
恩恩 好的 谢谢啦
