### ISSUE TITLE
URL of Next Page of Template Wrong

### ISSUE THREAD

**Issue by cxjchocolate** [open-falcon/falcon-plus#54]
当前页: http://host:8081/portal/template，显示最前面的10个template
如果点击下一页，会跳转到http://host:8081/templates?q=&mine=1&p=2&limit=10，我想正确的页面应该是http://host:8081/portal/template?q=&mine=1&p=2&limit=10

**Comment by laiwei** [comment]
https://github.com/open-falcon/dashboard/commit/4e3c8bfa44102294d02bd91cef5e0ee89d327073

fixed:)  👍 👍
