### ISSUE TITLE
templates只能关联到group上吗？

### ISSUE THREAD

**Issue by 51centos** [open-falcon/falcon-plus#549]
有些机器确实在一个组，简单点说，这个组下面的机器，部分主机有mysql服务，假设我监听端口，只能关联到这个组，就会导致有些没有mysql的机器，报警泛滥。请问如何关联到单台主机？

**Comment by MistShi** [comment]
将 hostgroup 理解成 服务分组，如果需要针对mysql进行监控，可以采用建立一个mysql分组，将mysql相关的监控模板与之绑定

**Comment by laiwei** [comment]
template 只能绑定在 hostgroup 上，无法绑定在单个 endpoint 上 @51centos
