### ISSUE TITLE
graph日志中mysql错误: unexpected EOF; broken pipe

### ISSUE THREAD

**Issue by clt85046** [open-falcon/falcon-plus#551]
graph日志中出现了大量的mysql报错，系统运行正常，但是内存占用量越来越高，请问这种情况应该如何解决？

![error2](https://user-images.githubusercontent.com/32003064/45806345-660cf480-bcf3-11e8-9858-82d504459dd5.jpg)

**Comment by clt85046** [comment]
这个问题我搜索了一下报的错误是go本身用的mysql线程池连接超时，可能是我这边机器性能导致mysql读写速度跟不上数据量导致的。我机器是8g内存，目前mysql使用了大约4g内存，然后graph占用了3-4g，一直就是报这个错误，也没有新的错误

**Comment by missuzhang** [comment]
1 .内存越来越高跟mysql应该没关系，随着监控项的增加，graph缓存的数据也会增加，所以内存会越来越高。
2 这个报错很可能是你们的graph更新索引的频率比较低，mysql有个连接空闲超时问题的参数wait_timeout，默认是28800。 如果连接池中的连接超过这么长时间空闲了，msyql服务端会端开连接，graph这时从连接池中取出超时的连接就会报错，但不应影响使用(超时的连接会丢弃重建)

综上，这个目前来说没多大影响，要是闲着碍眼，可以修改下代码，增加一个超时参数。SetConnMaxLifetime，这个值小于你们数据库中的wait_timeout即可。
