### ISSUE TITLE
 端口监控为什么不生效，一直也没有触发警报。

### ISSUE THREAD

**Issue by leeyongda** [open-falcon/falcon-plus#552]
例如 net.port.listen/port=8089
 端口监控为什么不生效，一直也没有触发警报。

**Comment by ileveli** [comment]
@laiwei 按照您所说的方式配置，所在机器的aget日志报一下提示：
portstat.go:36: output of sh format not supported
并且端口监控不生效，一直也没有触发报警。，改如何解决。
