### ISSUE TITLE
falcon支持多个im接口吗？

### ISSUE THREAD

**Issue by chengang2** [open-falcon/falcon-plus#553]
我想根据team的不同，发送到不同的im。人员太多。想要根据不同的业务组，建立不同的群，发送给不同的人。

**Comment by chengang2** [comment]
@laiwei 。目前做法是改源码。
func SendIM(im *model.IM) {
	defer func() {
		<-IMWorkerChan
	}()

	url := g.Config().Api.IM
	urls := strings.Split(url, ",")
	for _,url :=range urls{
		r := httplib.Post(url).SetTimeout(5*time.Second, 30*time.Second)
                ......
        }
配置里文件中，用，分割开多个im连接。
帮忙看下是否有必要更新到master中。

**Comment by Torijing** [comment]
@chengang2 目前看着微信对于群聊暂不支持群聊id可见吧，上面的需求看起来需要调用微信先去创建群聊，楼主有木有想过，同一team的人不一定都是共同好友，管理者拉人进群聊权限也不好约束。能不能拉进去都是另外一回事。整体设计起来还是比较麻烦有很多细节的，况且微信应该还不能提供这个比较高大上的接口。 😂
