### ISSUE TITLE
dashboard多实例如何配置 

### ISSUE THREAD

**Issue by chengang2** [open-falcon/falcon-plus#554]
目前发现web页面打开很慢。想增加一台web服务。请问这个要怎么配置。

**Comment by missuzhang** [comment]
本身就是无状态的，多部署几台，配置完全相同就行。前端加个负载均衡即可。不过现在的dashboard的架构，多增加实例，并不能提高性能。只能提高可用性。

**Comment by chengang2** [comment]
@missuzhang  那alarm里面的dashboard 地址要怎么配。

**Comment by missuzhang** [comment]
配负载均衡地址呗

**Comment by YouZhengChuan** [comment]
@missuzhang dashboard 慢的原因，不在于dashboard本身，而是在于后端api组件。
所以你完全可以在同一个服务器上启动多个api组件，监听不同的端口。
然后再启动多个dashboard，分别使用不同的api组件地址。
然后在前端配置nginx负载均衡。

但是这样可能会遇到Session的问题，没测试过，你可以试试。
