### ISSUE TITLE
收不到告警邮件，手动执行curl http接口是可以的

### ISSUE THREAD

**Issue by ethaninchina** [open-falcon/falcon-plus#568]
使用mail-provider
alarm 和 sender的api配置：
![image](https://user-images.githubusercontent.com/33546274/46645898-af958480-cbb9-11e8-8238-5bf718bae008.png)

falcon告警截图
![default](https://user-images.githubusercontent.com/33546274/46646131-f9329f00-cbba-11e8-9491-e7fc37d6e14f.png)

alarm日志截图
![alarm](https://user-images.githubusercontent.com/33546274/46645778-1f573f80-cbb9-11e8-8b2a-0856d5bb523b.png)

手动测试发邮件是成功的
![curl](https://user-images.githubusercontent.com/33546274/46645974-1c108380-cbba-11e8-8821-b9c09b9865ef.png)

告警接收组也配了
![image](https://user-images.githubusercontent.com/33546274/46646009-5548f380-cbba-11e8-8664-5419520aab9a.png)

![image](https://user-images.githubusercontent.com/33546274/46646046-7f9ab100-cbba-11e8-818f-ee585d27be8a.png)

![default](https://user-images.githubusercontent.com/33546274/46646986-000fe080-cbc0-11e8-95b7-24e03fb40dd9.png)

但是falcon系统的告警邮件还是收不到

**Comment by xiaosongdhls** [comment]
楼主 你的问题解决了吗？
