### ISSUE TITLE
agent无法获取挂载盘的IO信息

### ISSUE THREAD

**Issue by jianvhen** [open-falcon/falcon-plus#569]
RT， 比如SSD挂载盘就不支持

**Comment by jianvhen** [comment]
@YouZhengChuan 
类似下面这种
 251       0 p0vol0 323 0 5352 24 53 0 4544 2 0 24 26
 251      16 p0vol1 291 0 4304 22 53 0 4544 2 0 22 24
 251      32 p0vol2 301 0 15576 30 32 0 4408 4 0 29 34
 251      48 p0vol3 2565 0 89208 330 259 0 6416 3 0 325 330
 251      64 p0vol4 502 0 21864 55 64 0 4760 3 0 56 58
 251      80 p0vol5 94845073 0 3035498056 14174815 36859117 0 1046141552 2244870 0 13101410 16431385

**Comment by MistShi** [comment]
![image](https://user-images.githubusercontent.com/1921485/46906870-d860a580-cf3c-11e8-9813-233073e5e9f6.png)
![image](https://user-images.githubusercontent.com/1921485/46906887-ffb77280-cf3c-11e8-8894-5a5081bd261d.png)
@jianvhen

**Comment by jianvhen** [comment]
@MistShi , 是的， 已解决
通过修改过滤条件重新编译后验证成功。 不过这类信息是否有必要通配置来动态加载？

**Comment by MistShi** [comment]
嗯，需要考虑
