### ISSUE TITLE
cmd.go:43: Setpgid failed, error: permission denied

### ISSUE THREAD

**Issue by zhangkefang** [open-falcon/falcon-plus#570]
开启Plugin机制后，一直报这个错误，关闭正常.哪位大神解答下. root 用户启动.

**Comment by laiwei** [comment]
已经在 https://github.com/open-falcon/falcon-plus/issues/77  修复过了，用最新的 agent 即可 @zhangkefang

**Comment by zhangkefang** [comment]
@laiwei  收到，我试了正常的. 另外新的 agent发现了这个错误：
2018/10/10 16:28:17 gpu.go:31: Initialize error:  could not load NVML library

**Comment by zhangkefang** [comment]
可能是我主机问题，有的正常. 感谢.

**Comment by zhangkefang** [comment]
新 agent又发现一个 bug，plugin 第二次执行 curl http://127.0.0.1:1988/plugin/update 不更新，重启进程后执行 update 才生效. @laiwei
