### ISSUE TITLE
agent版本升级导致所有指标无法收集

### ISSUE THREAD

**Issue by jianvhen** [open-falcon/falcon-plus#574]
发生一有趣的事情， 我把agent升级后所有指标中断。
transfer， hbs都已经升级2.0版本了，agnet是旧的版本（5.1.0）的时候一切正常。

**Comment by MistShi** [comment]
@jianvhen 是说agent升级到社区的master分支的最新么?

**Comment by MistShi** [comment]
@jianvhen 用最新的master分支的代码，编译一下，然后打开debug，看看有没有错误输出，如果有发给我看看哈。

**Comment by jianvhen** [comment]
@MistShi , 问题找到了，  原先transfer配置里面是写addr 并没有改为addrs了， 及时后面是数组模式，也无法获取到响应的transfer地址。
谢谢，
