### ISSUE TITLE
Why template creating API does not return `id` of the new created template?

### ISSUE THREAD

**Issue by danieldai** [open-falcon/falcon-plus#575]
Hi, I'm try to operate on Open Falcon through Falcon-Plus HTTP API. I find on success creation of template `/api/v1/template` only return a string message. 

Could anybody help to explain why not returning information of the newly  created template, especially the `id`, anyway, template `id` is used extensively with other  template related APIs.

**Comment by MistShi** [comment]
这确实是个历史遗留问题，我们需要去修复一下

**Comment by danieldai** [comment]
I submitted a PR for this issue #576
