### ISSUE TITLE
agent -check coredump

### ISSUE THREAD

**Issue by rongyi** [open-falcon/falcon-plus#58]
最新的master分之agent执行 -check时会core掉

> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x47b4fc]
> 
> goroutine 1 [running]:
> panic(0x776d80, 0xc420010140)
>         /usr/local/go/src/runtime/panic.go:500 +0x1a1
> github.com/open-falcon/falcon-plus/modules/agent/funcs.DeviceMetrics(0x774a20, 0xc42004fd90, 0xc42004fc60)
>         /home/ry/go/src/github.com/open-falcon/falcon-plus/modules/agent/funcs/dfstat.go:21 +0x14c
> github.com/open-falcon/falcon-plus/modules/agent/funcs.CheckCollector()
>         /home/ry/go/src/github.com/open-falcon/falcon-plus/modules/agent/funcs/checker.go:21 +0x1e6
> main.main()
>         /home/ry/go/src/github.com/open-falcon/falcon-plus/modules/agent/main.go:27 +0x1dc

看了一下代码发现大概是这行：
`$HOME/go/src/github.com/open-falcon/falcon-plus/modules/agent/funcs/dfstat.go:21` 此时 `g.Config()`获取的还是初始化为nil的指针。加上 -c 参数执行配置文件一样的效果，而且main里check执行是在ParseConfig之前执行的，所以我以为check是不需要配置文件的。所以感觉这行需要加个nil判断

`if g.Config() != nil && len(g.Config().Collector.MountPoint) > 0`

**Comment by laiwei** [comment]
agent不支持check命令啊

只有 ./open-falcon check agent 这样才是对的

**Comment by rongyi** [comment]
哦，不好意思，我刚刚看falcon的代码，只是在里面看到命令行参数就这样试了，请忽略
