### ISSUE TITLE
获取挂载信息方法疑问

### ISSUE THREAD

**Issue by jianvhen** [open-falcon/falcon-plus#581]
这可能更像是一个go语言的基础问题，

问题是： 在agent会通过"github.com/toolkits/nux"包中的ListMountPoint来获取挂载信息。但是这个方法分windows和linux环境， 他们分别在不同的文件中，但是方法名和参数一模一样，这样为什么能编译通过？
![203967452eb28a100034ab5f1da3c555](https://user-images.githubusercontent.com/4044967/47070106-29191c80-d223-11e8-85ab-7147dcb9bea7.png)
![23563aa8d4aed13cd5f456a5d9607100](https://user-images.githubusercontent.com/4044967/47070122-30d8c100-d223-11e8-9f6e-1b5e7713d7c6.png)

**Comment by MistShi** [comment]
@jianvhen  https://dave.cheney.net/2013/10/12/how-to-use-conditional-compilation-with-the-go-build-tool

**Comment by jianvhen** [comment]
@MistShi , 非常感谢
