### ISSUE TITLE
原来的Query模块对应现在哪个模块？

### ISSUE THREAD

**Issue by tonygshliu** [open-falcon/falcon-plus#59]
我在文档https://laiwei.gitbooks.io/open-falcon/content/zh/install_from_src/portal.html 中看到一些模块在现在的all-in-one 中没有对应模块。
似乎原来的query对应现在的api模块，原来的portal是不是集成到dashboard中去了？

**Comment by laiwei** [comment]
- query 使用api模块代替
- portal、fe都集成到dashboard中了
- sender集成到alarm中了

**Comment by tonygshliu** [comment]
Thanks very much.
