### ISSUE TITLE
存储的数据变为科学计数法格式

### ISSUE THREAD

**Issue by 4711363** [open-falcon/falcon-plus#6]
Doashboard显示的数据出现断点，检查最近的记录，看来收到的数据是科学计数法，但我真是的数据不是科学计数，从日志上看到的发送日志的值为2403528，不知道为什么在query中查到的数据就是科学计数法。

附件：
![1](https://cloud.githubusercontent.com/assets/19596721/21213202/d16b64e0-c2cd-11e6-8566-6f82acc45bcb.jpg)
![2](https://cloud.githubusercontent.com/assets/19596721/21213203/d1716c5a-c2cd-11e6-97c1-36648e206bd0.jpg)

**Comment by hitripod** [comment]
应该与这无关，你的 Timestamp 是 GMT: Thu, 15 Dec 2016 05:42:00 GMT
