### ISSUE TITLE
docker v0.2.1 dashbord配置模板时，无法增加metric

### ISSUE THREAD

**Issue by ZoneTong** [open-falcon/falcon-plus#611]
docker v0.2.1 dashbord配置模板时，添加新counter时， metric的自动补完下拉框，一直在转，没有指标可选。F12显示该请求后台错误.
![image](https://user-images.githubusercontent.com/11485261/48313953-cc303c80-e5fd-11e8-9839-da5a64eef873.png)

后经排查，是api组件的cfg.json配置错误. 因为docker 中启动api时不是在在api的当前目录，找不到./data/metric文件错误引起的。将metric_list_file改成绝对路径即可。
![image](https://user-images.githubusercontent.com/11485261/48313997-45c82a80-e5fe-11e8-9f50-89f6947071c1.png)

**Comment by laiwei** [comment]
- fixed at https://github.com/open-falcon/falcon-plus/pull/615
- download [latest docker image](https://hub.docker.com/r/openfalcon/falcon-plus/tags/)

@ZoneTong
