### ISSUE TITLE
请问redis 设置密码后，不报警了，怎么解决，哪里添加验证。

### ISSUE THREAD

**Issue by xiaoyang16889** [open-falcon/falcon-plus#616]
请问redis 设置密码后，不报警了，怎么解决，哪里添加验证。

**Comment by Jack0005** [comment]
在judge的配置文件中，alarm.dns配置redis密码，在alarm的配置文件redis.addr配置redis密码

**Comment by laiwei** [comment]
@xiaoyang16889  alarm 当前不支持配置 redis 密码，你可以自行合并这个 pr：https://github.com/open-falcon/falcon-plus/pull/297

keywords: redis password
