### ISSUE TITLE
在falcon后台注册的用户如何删除呢？

### ISSUE THREAD

**Issue by baoming158** [open-falcon/falcon-plus#623]
**在falcon后台注册的用户如何删除呢？**

在使用falcon后台的时候，想删除之前注册过的某些用户，如何删除呢？

**Comment by baoming158** [comment]
怎么没有人来解答？

**Comment by laiwei** [comment]
@baoming158 可用以 root 身份登录后，删除不需要的用户。也可以去 MySQL uic.user 表中删除相关用户

**Comment by baoming158** [comment]
> @baoming158 可用以 root 身份登录后，删除不需要的用户。也可以去 MySQL uic.user 表中删除相关用户

谢谢您，确实可以。
