### ISSUE TITLE
agent上报的数据没有显示出来

### ISSUE THREAD

**Issue by liuyunzhang** [open-falcon/falcon-plus#624]
单机部署后台和前端组件，多台机器部署了agent内网上报，然后把agent中默认的监测项全开放；发现每台机器出来的counter数量有多有少；agent日志级别设置debug，然后发现上报的数据有一部分没有显示counter；
是因为监测项开太多数据堆积导致transfer算不过来吗？

**Comment by laiwei** [comment]
@liuyunzhang 一般情况下，和 transfer 处理能力没有关系。

counter 有多有少，可能是这些 agent 所在的机器本身有差异，比如磁盘的数量等硬件配置不同

**Comment by liuyunzhang** [comment]
但是我看agent的日志，"var.go:88: => <Total=137> <Endpoint:10.0.0.3......";上报了有137个项？

**Comment by laiwei** [comment]
有新的信息追加，再 reopen 这个 issue 吧:)

**Comment by liuyunzhang** [comment]
数据库连接问题

**Comment by yangzhen868** [comment]
> 数据库连接问题

mysql问题？具体是什么问题呢

**Comment by liuyunzhang** [comment]
@yangzhen868 
检查日志发现入库那里部分数据入库连接报错，检查不出原因后直接换了一个数据库之后就好了
