### ISSUE TITLE
我想问下，docker 安装有人测试过吗？

### ISSUE THREAD

**Issue by aimuz** [open-falcon/falcon-plus#627]
我使用你们官方打包镜像，完全跑不起来？连命令都是复制的，一开始还以为是我改错了
`./control: line 25: env/bin/activate: No such file or directory`
一直提示这个错误，本地安装也是一样？

https://github.com/open-falcon/falcon-plus/blob/master/docker/README.md#4-start-falcon-dashboard-in-container

这个里面的命令真的对嘛

**Comment by trockxi** [comment]
> 我使用你们官方打包镜像，完全跑不起来？连命令都是复制的，一开始还以为是我改错了
> `./control: line 25: env/bin/activate: No such file or directory`
> 一直提示这个错误，本地安装也是一样？
> 
> https://github.com/open-falcon/falcon-plus/blob/master/docker/README.md#4-start-falcon-dashboard-in-container
> 
> 这个里面的命令真的对嘛

请问后面是怎么解决的？安装python环境吗？

**Comment by aimuz** [comment]
> > 我使用你们官方打包镜像，完全跑不起来？连命令都是复制的，一开始还以为是我改错了
> > `./control: line 25: env/bin/activate: No such file or directory`
> > 一直提示这个错误，本地安装也是一样？
> > https://github.com/open-falcon/falcon-plus/blob/master/docker/README.md#4-start-falcon-dashboard-in-container
> > 这个里面的命令真的对嘛
> 
> 请问后面是怎么解决的？安装python环境吗？

我记得按照他们的命令，一步都不能缺，就可以了，不过现在没有用了
