### ISSUE TITLE
transfer的8433端口创建的tcp连接数超过最大值

### ISSUE THREAD

**Issue by virtue1990** [open-falcon/falcon-plus#630]
在使用监控的过程中，发现一个问题现象，由于某些原因，终端设备网卡不停的重启造成网络不稳定，而agent上传数据的到transfer端口8433，不停的和server端创建新的tcp连接。这样导致transfer建立了大量的tcp连接，且状态为established，并且没有释放，最后导致transfer无法创建新的连接，一直报错。

**Comment by carrotshub** [comment]
现在遇到同样的问题，请问是怎么解决的呢？

**Comment by jinhailang** [comment]
我也遇到了这个问题，transfer 进程已经被停掉了，但是服务端（judge，graph）机处于 ESTABLISHED 状态的连接仍然有一两万，也就是出现了大量的假死 TCP 连接，经过一天的排查，发现是因为 falcon 的 RPC Server 都没有开启 keepalive，导致服务端没有启用 linux 的连接检测机制，客户端异常断开后，连接不会自动关闭。我提交了一个 feature 来修复这个问题。https://github.com/open-falcon/falcon-plus/pull/843

**Comment by carrotshub** [comment]
有解决方案了吗？问题关闭了
