### ISSUE TITLE
tags的作用

### ISSUE THREAD

**Issue by github-of-dl** [open-falcon/falcon-plus#631]
刚接触open-falcon有个很不明白的地方，tags的作用是什么？比如port=2000。这个是作为metric的参数在agent执行的时候传递?  
如果是作为参数的话，自定义agent如何取到对应的tags？

**Comment by itmajing** [comment]
> tag的作用更多的用于进行多维度的筛选，比如在配置报警策略的时候，或者配置 dashboard 的时候。
> 
> net.port.listen/port=2000 这个比较特殊，只有配置了 port=xx 的时候，绑定了该策略的agent 机器才会主动探测这个 port 的存活。

![image](https://user-images.githubusercontent.com/24891592/54577026-240c0380-4a35-11e9-84f9-b083fbd3feb1.png)
我在expressions里这样配置无效，使用template配置可以，请问是这个是不是只能通过模板配置？

**Comment by laiwei** [comment]
port这块比较特殊，只能在template中生效 @itmajing

**Comment by itmajing** [comment]
@laiwei 谢谢回复,明白了
