### ISSUE TITLE
支持mariradb数据库部署吗？

### ISSUE THREAD

**Issue by jacklibra** [open-falcon/falcon-plus#632]
centeros7.4 / mariadb 10.3.10

我在同一台主机上安装后台和前端，后台运行正常
但是前端在启动时加载MySQLdb错误：No module named MySQLdb

想问下有用mariadb安装运行成功的朋友吗？

问题应该在mysql-python上，使用pip install Mysql-python安装报错：

![2018-11-27_100200](https://user-images.githubusercontent.com/33919639/49053565-90b38600-f22b-11e8-8bd3-7d4d8780df19.png)

**Comment by laiwei** [comment]
@jacklibra  可以使用 falcon-dashboard 的 docker image 运行，可以避免 python lib 库的安装问题：https://github.com/open-falcon/falcon-plus/blob/master/docker/README.md
