### ISSUE TITLE
网卡流量值获取有问题

### ISSUE THREAD

**Issue by Guwenqiang** [open-falcon/falcon-plus#639]
hi，你好，我通过open-falcon net.if.in.bytes/iface=eth0和net.if.out.bytes/iface=eth0去查看网卡的出入流量，和在本机看到的流量相差5-6倍（主机上直接使用nload查看实时流量对比的），open-falcon没有做额外的配置调整。

**Comment by mdh67899** [comment]
> 默认每 100 毫秒刷新一次显示数值，下面的例子将时间间隔设置成 500 毫秒

我看[这个文档](https://linux.cn/article-2871-1.html)里面nload是100毫秒刷新一下数据，统计的周期是100ms，falcon-agent统计的出入流量时间粒度是1分钟，两者时间粒度差的太大，所以统计的值相差很大也算是正常，你试试设置nload的刷新时间间隔为1分钟，再看对比一下二者的差值看看

**Comment by laiwei** [comment]
@Guwenqiang falcon的网络流量单位是 byte，nload实时看到的单位是 bit 吧？

**Comment by CastroKKK** [comment]
楼主应该是单位搞错了，以byte 为准。iftop看到的也要转换成小b，同理。
