### ISSUE TITLE
针对容器资源指标获取方案

### ISSUE THREAD

**Issue by yangzhen868** [open-falcon/falcon-plus#643]
目前falcon提供的micadvisor使用的是cadvisor获取到的资源指标，k8s标签等无法带入自动获取。
咨询下，现在有什么更好的方案，或者是falcon后续有什么开发计划。

**Comment by Jianxia1994** [comment]
同问，或者哪位知道社区有别的解决方案吗？

**Comment by laiwei** [comment]
@yangzhen868 @Jianxia1994  请参考 google cadvisor ，目前 falcon 没有更好的实现。
