### ISSUE TITLE
DashBoard安装依赖包报错

### ISSUE THREAD

**Issue by lianliwei** [open-falcon/falcon-plus#655]
![image](https://user-images.githubusercontent.com/46194023/50481150-f22d6700-0a1a-11e9-89a7-51c2afa09872.png)
安装依赖包时报如上错误
之后启动后查看日志如下
![image](https://user-images.githubusercontent.com/46194023/50481228-5fd99300-0a1b-11e9-9785-90b29179e2b2.png)
这怎么解决

**Comment by laiwei** [comment]
删除命令末尾的 -i https://pypi.douban.com/simple @lianliwei
