### ISSUE TITLE
怎么监控服务是否重启？

### ISSUE THREAD

**Issue by lwmonster** [open-falcon/falcon-plus#657]
我希望我的服务如果发生了重启能够报警出来，但是我看现在只有 port 监控，这个基本报不出来。
因为重启的动作会很快， port 监控是定时执行的。

我想要的是： 
只要服务发生了重启，就能报出警来，有什么办法? 

PS: 最好的是监控 pid 是否发生了变化

**Comment by ffgfg** [comment]
您好，请问你现在是怎么解决这个问题的哈

**Comment by uglyliu** [comment]
同问，我们这是supervise启动，瞬间一下子就被拉起来了
