### ISSUE TITLE
请问falcon下个版本什么时候出？有计划吗？

### ISSUE THREAD

**Issue by topicgit** [open-falcon/falcon-plus#658]
请问falcon下个版本什么时候出？有计划吗？
是否会支持influxdb？

**Comment by laiwei** [comment]
influxdb 暂时不会支持。 4月初会发布新的优化版本。

**Comment by itmajing** [comment]
> influxdb 暂时不会支持。 4月初会发布新的优化版本。

看到了v0.0.2的分支，请问什么发布呢
