### ISSUE TITLE
请问falcon-plus支持监控docker容器吗

### ISSUE THREAD

**Issue by ymcvalu** [open-falcon/falcon-plus#659]
你好，请问falcon-plus支持监控docker容器吗

**Comment by laiwei** [comment]
请参考 google 的 cadvisor 方案。 @ymcvalu

**Comment by ymcvalu** [comment]
> 请参考 google 的 cadvisor 方案。 @ymcvalu

我现在在cadvisor里面添加了定时push监控指标到transfer组件的逻辑，但是在dashboard中数据展示不是很及时，比如我定时10s push一次采集的数据，在dashboard中可能要一分钟以上才能看到，请问这是正常的吗，或者有没有配置项可以加快数据及时展示
