### ISSUE TITLE
定时入盘时，参数是不是应该传true

### ISSUE THREAD

**Issue by ymcvalu** [open-falcon/falcon-plus#660]
https://github.com/open-falcon/falcon-plus/blob/9af093726daa42740afea1d73c2da1c26e47f876/modules/graph/rrdtool/sync_disk.go#L48
定时入盘的时候，执行的是`FlushRRD(idx, false)`，导致数据一直没有写入磁盘，这里是不是应该传入true

**Comment by laiwei** [comment]
这个参数控制的是立即落盘，还是等积累到一批数据后批量落盘。为了提升磁盘写入效率，选择批量落盘。 @ymcvalu
