### ISSUE TITLE
什么时候能支持 go mod？

### ISSUE THREAD

**Issue by walnut-tom** [open-falcon/falcon-plus#666]

**Comment by laiwei** [comment]
现在使用的 govendor 有什么不满足需求的地方么 @walnut-tom

**Comment by walnut-tom** [comment]
依赖的 golang.org 等模块，需要科学上网才能处理，打包不是很方便。
用 支持 go mod 可以用 replace 换成 github 的

**Comment by laiwei** [comment]
@walnut-tom  govendor 已经把所有的依赖，打包提交到falcon-plus repo 里面了: 
 https://github.com/open-falcon/falcon-plus/blob/master/vendor/vendor.json

**Comment by laiwei** [comment]
#937 @walnut-tom
