### ISSUE TITLE
如何支持systemd服务管理

### ISSUE THREAD

**Issue by yangding39** [open-falcon/falcon-plus#667]
下面这样编写启动文件不行呢
[Unit]
Description=Open Falcon Service
After=network.target

[Service]
WorkingDirectory=/opt/open-falcon
ExecStart=/opt/open-falcon/open-falcon start
StandardOutput=null

Restart=on-failure
RestartSec=15

[Install]
WantedBy=multi-user.target
~

**Comment by walnut-tom** [comment]
用各个模块 加参数试试，比如 falcon-alarm -c cfg.json
