### ISSUE TITLE
监控进程时agent上报数据不对

### ISSUE THREAD

**Issue by crazylovecat** [open-falcon/falcon-plus#669]
version = 0.2.1
metric/tags：proc.num/cmdline=falcon-agent
偶尔会出现上报value=2的情况
![image](https://user-images.githubusercontent.com/7908957/51516421-64466f80-1e52-11e9-8202-e8d76ecf5258.png)

**Comment by MistShi** [comment]
falcon-agent的进程号变了么？

**Comment by laiwei** [comment]
需要看看是否有多个 cmdline=falcon-agent 的进程在跑
