### ISSUE TITLE
请问url探测的相关文档在哪里？有没有所有内置支持的metrics列表？

### ISSUE THREAD

**Issue by xrlin** [open-falcon/falcon-plus#674]
看到文档中写着内置url探测，但没看到文档中有相关说明，只有一个urllook的，但是这个连schema.sql都不能下载了。

**Comment by 710leo** [comment]
@xrlin schema.sql下载链接已更新，安装说明[地址](https://github.com/URLooker/wiki/blob/master/README.md)
urlooker上报到open-falcon的监控项说明见 [wiki](https://github.com/URLooker/wiki/wiki/open-falcon-%E4%B8%8A%E6%8A%A5%E9%A1%B9%E4%BB%8B%E7%BB%8D)

**Comment by xrlin** [comment]
@710leo 一开始看change log有内置的url探测，想着可以不用再安装其它服务，几经尝试未果最后还是用了urlooker。
