### ISSUE TITLE
open-falcon如何实现触发报警重启服务

### ISSUE THREAD

**Issue by chenfeng-1** [open-falcon/falcon-plus#679]
open-falcon监控进程和端口时，当进程和端口挂了，自动重启服务，通过脚本或者直接使用系统命令实现，可以实现这个功能吗，如何实现？？？

**Comment by jianvhen** [comment]
编写一个plugin插件，1分钟轮询一次检查服务是否存在，不存在执行重启

**Comment by chenfeng-1** [comment]
> 编写一个plugin插件，1分钟轮询一次检查服务是否存在，不存在执行重启

**Comment by chenfeng-1** [comment]
通过检查服务来执行重启，直接写个脚本就可以实现了，如果通过监控报警实现重启服务呢，这个怎么操作实现

**Comment by laiwei** [comment]
@chenfeng-1 可以用 open-falcon 告警策略的 callback 功能。 https://github.com/open-falcon/dashboard/issues/71

另外，近期会发布一个内置的命令执行通道，和 open-falcon 无缝衔接。
