### ISSUE TITLE
请问一下关于多机房的问题。

### ISSUE THREAD

**Issue by lekj** [open-falcon/falcon-plus#686]
举个例子：有机房 A，B。 
A 里面 openfalcon 监控主机允许上网，B 机房监控主机没有固定 IP，但允许上网。
两机机房都的监控主机都安装了两套完整的系统。
想问下，能否把 B 机房监控主机的数据同步发送到 A 监控主机。
即 A主机允看到 A,B 两机房数据，B 监控主机只看到 B 机房数据。
看了一下 gateway 和 hbs-proxy ，都是转发数据，即如果把数据转发到了 A ，
则 B 监控主机就收不到数据了。
是这样的吗？ 请指教。

**Comment by laiwei** [comment]
transfer 可以支持发送数据到两个不同的 graph 集群（不过这样做要求这两个graph集群完全对等） @lekj
