### ISSUE TITLE
Plugin的pull时机

### ISSUE THREAD

**Issue by Hao1296** [open-falcon/falcon-plus#694]
目前插件更新后需要curl每台agent的接口来手动pull，这里可不可以通过GitHook来实现？比如在hbs上面开一个接口，并把这个接口设到GitHook中去，这样GitLab中内容更新后就可以通知到hbs，然后hbs又可以通知到agent

**Comment by laiwei** [comment]
@Hao1296 当时设计为手动去 pull plugin，是因为在当时的生产环境下，上万台服务器去 pull 的时候，会对 git server 产生巨大的压力，不可控。 

你说的 git hook 这种定时触发的模式，你只需要去从 git server 和 git repo 这里入手修改就 OK。
