### ISSUE TITLE
LDAP登陆问题

### ISSUE THREAD

**Issue by Remember-Forever** [open-falcon/falcon-plus#695]
请教一下各位，我在使用LDAP进行登陆的时候，出现了这个问题

![image](https://user-images.githubusercontent.com/19926324/53396417-5bac0080-39df-11e9-822d-864eac195f64.png)

我查看了一下LDAP的日志里面，出现了一段提示，内容为access_allowed: result not in cache (userPassword)

同时，在dashboard/rrd/config.py里面设置的LDAP_ATTRS的参数，也同样出现了result not in cache的提示

请问有人知道这个问题怎么解决吗

**Comment by freedomkk-qfeng** [comment]
dashboard 的 config.py 能发下吗
同时用 
```
source env/bin/activate
python wsgi.py
``` 
启动 dashboard 的 debug 模式来还原下现象，然后把此时输出的日志也发下看看

**Comment by Remember-Forever** [comment]
config.py我修改了以下两个部分：

![image](https://user-images.githubusercontent.com/19926324/53398213-06262280-39e4-11e9-9dc8-6b9c350ab23c.png)

![image](https://user-images.githubusercontent.com/19926324/53398284-379eee00-39e4-11e9-8c9f-b184aec6db81.png)

执行命令之后出现以下日志：
![image](https://user-images.githubusercontent.com/19926324/53398322-4edddb80-39e4-11e9-9db2-3382ff65138b.png)

**Comment by freedomkk-qfeng** [comment]
尝试拉取一下 falcon-plus 当前版本的代码，重新编译 api 模块。ldap 认证依赖了 api 上新增的 admin/login 这个 api，这部分好像还没打包发 release。
你这里似乎没有这个接口，404 了~

**Comment by Remember-Forever** [comment]
重新拉取编译之后已经解决了，谢谢解惑~

**Comment by jiangbo0225** [comment]
> 
> 
> 重新拉取编译之后已经解决了，谢谢解惑~

重新编译的api模块，可以上传下吗？不想编译了
