### ISSUE TITLE
请问 怎么配置只发微信报警，不需要发邮件报警？

### ISSUE THREAD

**Issue by leeyongda** [open-falcon/falcon-plus#699]

**Comment by msadu** [comment]
不配置微信的接口不行吗？

**Comment by leeyongda** [comment]
> 不配置微信的接口不行吗？
我的意思是只配置了微信都接口，但是报警还是会发送邮件，导致发送失败，想去掉邮件发送。

**Comment by leeyongda** [comment]
![image](https://user-images.githubusercontent.com/11832476/53962451-134eba00-4126-11e9-868f-5406bbeb3abd.png)
如果这里mail 地址没配置，为空的情况下，没有进行判断，应该直接返回掉。没有配置URL，也会去发送请求，导致发送失败。目前不需要配置邮件告警发送，所以只配置了微信告警。
