### ISSUE TITLE
调用/api/v1/graph/lastpoint获取last值

### ISSUE THREAD

**Issue by SaltedFishChili** [open-falcon/falcon-plus#700]
##must:
Auth Session
Endpoint
Counter

##Simple request of python:

 import requests

url = "http://127.0.0.1:8080/api/v1/graph/lastpoint"
payload = "[{ \"Endpoint\":  \"host1\", \"Counter\":\"cpu.idle\" }]" #body必须为数组
headers = {
    'apitoken': "{\"name\":\"your_name\",\"sig\":\"your_sig\"}",
    'x-forwarded-for': "127.0.0.1",
    'content-type': "application/json",
    }
response = requests.request("POST", url, data=payload, headers=headers)
print(response.text)

##Response 
Status:200

##Response Data 
[
    {
        "endpoint": "host1",
        "counter": "cpu.idle",
        "value": {
            "timestamp": 1551853560,
            "value": 95.309973
        }
    }
]

**Comment by NotesFire** [comment]
不支持多key单vaule或单key多vaule的数组，略坑！

**Comment by MrZhouGit** [comment]
您好. 当前lastpoint接点未对外暴露 仍在项目组考虑阶段.
不建议您使用.
另外lastpoint 是对当前point进行last查询. 逻辑上不支持您所说的方法

open-falcon 感谢您的支持. 祝您工作顺利
