### ISSUE TITLE
压测服务器cpu/内存负载不满问题

### ISSUE THREAD

**Issue by jackzhaiyh** [open-falcon/falcon-plus#702]
我们对对agent的自定义push接口进行了压测，falcon所有组件部署在同一云主机上，在tps不上升的情况下，云主机cpu使用率在达到70%后不再上升，内存等资源也没有满负载。请问一下是压测方法可能有什么问题？

**Comment by jackzhaiyh** [comment]
补充：agent与transfer都安装在一台云主机上，感觉agent做了什么限制，使机器的负载不能满载，并且tps已不再上升。

**Comment by jackzhaiyh** [comment]
补充：随着我们jmeter的并发线程数目增加，falcon-agent机器的建立tcp连接数也在增加，但是tps是不变的，响应时间随之增长。

**Comment by jackzhaiyh** [comment]
补充：agent与transfer实在同一主机上的，目前感觉是agent与transfer之间的rpc同步调用存在瓶颈，这个rpc是否支持异步方式呢？

**Comment by jackzhaiyh** [comment]
目前感觉是agent向transfer发送数据的机制容量有限导致的，单连接/同步rpc。可以修改为业务服务直接发送数据到transfer，采用jsonRpc方式。

**Comment by laiwei** [comment]
如果需要追求大批量数据的上报，可以直接使用 transfer 提供的 rpc 接口 @jackzhaiyh
