### ISSUE TITLE
task nodata graph的联动问题

### ISSUE THREAD

**Issue by azvs** [open-falcon/falcon-plus#705]
目前使用的有这样一个问题。开启task每天半夜重建并删除索引。nodata配置的组 agent.alive=-1。
1当有机器下架不在上传信息之后，agent.alive仍然上传-1；
2每天夜里会将这些下架机器的其他索引清除，但是无法清除agent.alive，一直都是-1；
3尝试手动删除falcon_portal host表中对应主机，因graph库中endpoint以及对应的endpoint_counter/tag中的对应记录，第二天半夜仍然会被task重建agent.alive，并且一直发送-1

**Comment by jianvhen** [comment]
遇到过类似情况
确实没有联动机制, 你要删掉nodata的配置

**Comment by azvs** [comment]
> 遇到过类似情况
> 确实没有联动机制, 你要删掉nodata的配置

好的，这边也是先手动删除
