### ISSUE TITLE
open-falcon是否依赖特定的系统？

### ISSUE THREAD

**Issue by ShiJinYu2017** [open-falcon/falcon-plus#711]
open-falcon官方提供的安装都是基于centos的,考虑到agent在获取监控指标时，不同系统的获取方式也可能不相同，我想请教一下，是否该框架可以运行在所有linux系统之上。问题有点幼稚，大家见谅。

**Comment by laiwei** [comment]
open-facon server 端建议运行在 centos 上。 

agent 是否能运行在「所有」的 Linux 上，这个没有最完备的测试结论。 @ShiJinYu2017
