### ISSUE TITLE
open-falcon 是否支持报警后，自动触发相应脚本。

### ISSUE THREAD

**Issue by rockqwtest** [open-falcon/falcon-plus#719]
类似zabbix中action的功能。就好像但磁盘报警后，自动触发相应的脚本来清理磁盘，达到自动恢复的作用。

**Comment by laiwei** [comment]
当前可以使用 callback，调用自己写好的脚本来清理磁盘等动作。 @rockqwtest

自动恢复相关的功能，会在接下来的版本中。

**Comment by rockqwtest** [comment]
callback地址（只支持http get方式回调）
意思是直接可以通过http://127.0.0.1/xxx.sh来调用脚本么？

**Comment by rockqwtest** [comment]
> 当前可以使用callback，调用自己写好的脚本来清理磁盘等动作。@ rockqwtest
> 
> 自动恢复相关的功能，会在接下来的版本中。

callback地址（只支持http get方式回调）
意思是直接可以通过http://127.0.0.1/xxx.sh来调用脚本么？

**Comment by chengang2** [comment]
有调用的例子吗？ 怎么调用自己的脚本
