### ISSUE TITLE
最新分支v0.2.2是否已支持联合告警条件？

### ISSUE THREAD

**Issue by gavinju** [open-falcon/falcon-plus#725]
群主：咨询下，最新分支v0.2.2是否已经支持告警联合条件？
类似于Zabbix的表达式语法，可以多条件组合告警。

**Comment by laiwei** [comment]
多组合条件的改动比较大，会在 v1 版本支持。 @gavinju

**Comment by gavinju** [comment]
感谢分享。v1版本预计会在什么时候发布 ？
