### ISSUE TITLE
对于judge重启丢失数据，怎么处理啊？-_-||

### ISSUE THREAD

**Issue by Torijing** [open-falcon/falcon-plus#727]
judge重启时丢失数据，这部分有好的方案吗？

**Comment by liuhaoXD** [comment]
目前没有什么好的方案。

judge用于判断的相关数据保存在内存中，由transfer通过调用 RPC Send方法上传得到。LinkedList.go中的[PushFrontAndMaintain](https://github.com/open-falcon/falcon-plus/blob/282977aa402cbeebef86a434e4750fb36b763c5a/modules/judge/store/linkedlist.go#L122)方法的实现决定了不能通过手工调用 Send 方法上传过往数据点来补齐历史数据。

另外 open-falcon 本身是 push 模型，即 agent 将数据点 push 到 transfer，然后 transfer 将数据点 push 到 judge 里，这种设计决定了 judge 重启后，是无法像 pull 模型一样重新加载历史数据。

但理论上仍可以修改 judge 的启动过程，在启动时通过遍历现有全部 judge 策略的方式加载补齐历史数据。

**Comment by YouZhengChuan** [comment]
可以将每个endpoint/counter 的最后状态维护在redis中，重启的时候先从redis中获取所有endpoint/counter的状态，当状态发生Change的时候再Set回去。。。

**Comment by YouZhengChuan** [comment]
感觉这个方式是改动最小的了。。judge中存储的历史数据其实没什么意义，主要的是告警的状态，这个不维护的话，重启会将所有未恢复的告警重新发一次。。

**Comment by Torijing** [comment]
@YouZhengChuan 是的~ 权衡丢失的数据点和告警状态，告警状态更重要一些。
谢谢~

**Comment by Torijing** [comment]
@liuhaoXD 很详细，谢谢~~ ：）
