### ISSUE TITLE
使用Docker安装open-falcon后，配置的告警不起作用

### ISSUE THREAD

**Issue by mayanyun1986** [open-falcon/falcon-plus#728]
使用Docker安装open-falcon后，页面都可以正常访问，也能监控默认的指标；但配置的告警不起作用，在alarm-dashboard中查不到告警

**Comment by canghai908** [comment]
按照官方文档手册进行，检查，详情查看：http://book.open-falcon.org/zh_0_2/faq/alarm.html 确保各个组件日志无报错，运行正常。

**Comment by mayanyun1986** [comment]
在agent配置中增加host解决
