### ISSUE TITLE
callback()机制如何定义和使用

### ISSUE THREAD

**Issue by ShiJinYu2017** [open-falcon/falcon-plus#730]
在dashboard中报警策模板中的callback是用来做什么的，应该如何配置？

**Comment by hdksky** [comment]
可以参考下面的说明文档
docs/_posts/Template/2017-01-01-tpl_action_create.md

**Comment by ShiJinYu2017** [comment]
好的，谢谢您，我再花时间多看看，谢谢您的帮助
