### ISSUE TITLE
磁盘IO监控数据获取失败

### ISSUE THREAD

**Issue by unixgiant** [open-falcon/falcon-plus#739]
我使用的aws ec2，有些硬盘名是nvme0n1、nvme1n1这些，agent取不到io监控数据，其他比如xvda、xvdb这些没问题。
# cat /proc/diskstats
 259       0 nvme1n1 167176 13 8848431 1970464 2215744207 3956505 9011552578 302973383 0 271454722 304743868
 259       1 nvme1n1p1 167133 13 8845303 1970443 496754052 3956505 9011552578 267464572 0 236174547 269355985
 259       2 nvme0n1 41783 14286 1786053 19965 9497431 1065736 139793964 1931722 0 659111 1951355
 259       3 nvme0n1p1 41746 14286 1783901 19955 9492471 1065736 139793964 1931594 0 658975 1951509
 253       0 dm-0 167005 0 8841775 2023345 2001842507 0 9011552578 307567877 0 271491243 309601085

**Comment by laiwei** [comment]
https://github.com/open-falcon/falcon-plus/blob/master/modules/agent/cfg.example.json#L33   mountPoint 中可以指定 nvme0n1 

@unixgiant
