### ISSUE TITLE
因不同系统ss命令输出格式不同，造成的agent启动报错panic: runtime error: index out of range

### ISSUE THREAD

**Issue by tinyhare** [open-falcon/falcon-plus#747]
操作系统Ubuntu 19.04
启动agent后一段时间报错：
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/open-falcon/falcon-plus/vendor/github.com/toolkits/nux.SocketStatSummary(0xc00010e2a0, 0xc0002d64d3, 0xf)
	/home/tinyhare/go/src/github.com/open-falcon/falcon-plus/vendor/github.com/toolkits/nux/ss_s.go:51 +0x7d3
github.com/open-falcon/falcon-plus/modules/agent/funcs.SocketStatSummaryMetrics(0x83f4a0, 0xc0000c3de8, 0x8c503f)
	/home/tinyhare/go/src/github.com/open-falcon/falcon-plus/modules/agent/funcs/sockstat.go:24 +0x37
github.com/open-falcon/falcon-plus/modules/agent/funcs.CheckCollector()
	/home/tinyhare/go/src/github.com/open-falcon/falcon-plus/modules/agent/funcs/checker.go:42 +0x466
main.main()
	/home/tinyhare/go/src/github.com/open-falcon/falcon-plus/modules/agent/main.go:41 +0x1e1

报错代码出现在github.com/toolkits/nux/ss_s.go:51
```go
if fields[0] == "timewait" {
        timewait_arr := strings.Split(fields[1], "/")
        m["timewait"], _ = strconv.ParseUint(timewait_arr[0], 10, 64)
        m["slabinfo.timewait"], _ = strconv.ParseUint(timewait_arr[1], 10, 64)  //这里
        continue
}
```
此段代码是调用ss -s命令获取连接状态的，从系统上执行ss -s  发现timewait只有一个值，而在旧系统上有两个值
```
On  Ubuntu 19.04
tinyhare@hole:/data/work/open-falcon$ ss -s
Total: 236
TCP:   86 (estab 56, closed 2, orphaned 0, timewait 2)

Transport Total     IP        IPv6
RAW	  3         0         3
UDP	  9         7         2
TCP	  84        58        26
INET	  96        65        31
FRAG	  0         0         0
```
```
On Ubuntu 14.04.5
$ ss -s
Total: 123 (kernel 0)
TCP:   19 (estab 4, closed 0, orphaned 0, synrecv 0, timewait 0/0), ports 0

Transport Total     IP        IPv6
*	  0         -         -
RAW	  0         0         0
UDP	  0         0         0
TCP	  19        13        6
INET	  19        13        6
FRAG	  0         0         0
```
解决方案：修改github.com/toolkits/nux/ss_s.go代码,然后build
```
if fields[0] == "timewait" {
        timewait_arr := strings.Split(fields[1], "/")
        m["timewait"], _ = strconv.ParseUint(timewait_arr[0], 10, 64)

        //m["slabinfo.timewait"], _ = strconv.ParseUint(timewait_arr[1], 10, 64) 
        if len(timewait_arr) > 1 {
                m["slabinfo.timewait"], _ = strconv.ParseUint(timewait_arr[1], 10, 64)
        } else {
                m["slabinfo.timewait"] = 0
        }
        continue
}
```

**Comment by gaoxujie** [comment]
agent 安装在debian10服务器上，还是会出现这个问题
