### ISSUE TITLE
Expression配置port或者proc.num agent并不会上报

### ISSUE THREAD

**Issue by chengang2** [open-falcon/falcon-plus#750]
Expression配置port或者proc.num agent并不会上报prot或者proc.num。
each(endpoint=xxxxx metric=proc.num cmdline=djava.jar)
查看源码发现agent只会上报有绑定了该endpoint的templates。
请问，我的理解对吗

**Comment by Torijing** [comment]
port和proc.num 监控要通过模板策略来配置，不是expression

具体是agent与hbs之间的心跳原理，会根据配置的模板策略来做端口，进程上报。

步骤：配置template模板，才会有port的metric。metric是net.port.listen, tag里配置port=xxx，然后模板关联hostgroup，hostgroup里的host就会通过hbs获取到需要监测的port，然后探测上报啦
