### ISSUE TITLE
falcon前端dashboard有没有关于主机的增删改查接口

### ISSUE THREAD

**Issue by jainszhang** [open-falcon/falcon-plus#765]
zabbix有这种host主机的增删改查借口，我在falcon文档上面没有找呀

**Comment by laiwei** [comment]
这些功能，在 dashboard 页面上可以操作。不过这个 API 并没有开放出来。需要整理。 @jainszhang

**Comment by jainszhang** [comment]
> 这些功能，在 dashboard 页面上可以操作。不过这个 API 并没有开放出来。需要整理。 @jainszhang

好的好的，谢谢你呀
