### ISSUE TITLE
agent 1988端口上的web界面能否显示网络流量数据？

### ISSUE THREAD

**Issue by tangkangrui** [open-falcon/falcon-plus#766]
![image](https://user-images.githubusercontent.com/19900665/60556934-12e1cb00-9d76-11e9-8f39-d15f8fb022df.png)
如图，这里能够显示各个iface上的出入栈流量吗？ 在dashboard上可以查到这台机器的net.ifxxxx的counter

**Comment by laiwei** [comment]
推荐从 dashboard 上查询。 @tangkangrui
