### ISSUE TITLE
graph修改绘图精度之后，如何历史数据迁移。

### ISSUE THREAD

**Issue by luck-xiaohei** [open-falcon/falcon-plus#768]

**Comment by luck-xiaohei** [comment]
想要变更graph的绘图精度，增加对数据的保存时间。这个时候只能丢弃历史数据吗？

**Comment by laiwei** [comment]
对的，修改了精度之后，之前的历史数据会中断。所以最好在开始的时候，就考虑好精度等的设置。 @luck-xiaohei

**Comment by luck-xiaohei** [comment]
> 对的，修改了精度之后，之前的历史数据会中断。所以最好在开始的时候，就考虑好精度等的设置。@ luck-xiaohei

好的。感谢你的解答~
