### ISSUE TITLE
agent插件功能开启报错 Setpgid failed, error: permission denied

### ISSUE THREAD

**Issue by Yuani** [open-falcon/falcon-plus#77]
如果关闭agent plugins 功能，就没有这报错
已使用最新版本编译多次，不管是root 用户还是 普通用户，只要开启agent plugin 功能，就会报错，
同时我也测试了 官方讨论群里上传的agent 一样存在这个问题，但是插件功能是正常的

补充：使用open-falcon-v1 版本的agent 开启plugin 一切正常

agent 日志：
2017/05/11 10:04:02 scheduler.go:59: plugins/monitor_proc/falcon/60_run_process-check-scripts.py running...
2017/05/11 10:04:02 cmd.go:43: Setpgid failed, error: permission denied
2017/05/11 10:04:02 var.go:88: => <Total=1> <Endpoint:agent1, Metric:monitor_proc, Type:GAUGE, Tags:project=falcon,app=tcping_3306.sh, Step:60, Time:1494497042, Value:1>
2017/05/11 10:04:02 var.go:95: <= <Total=1, Invalid:0, Latency=0ms, Message:ok>
2017/05/11 10:04:02 plugin.go:64: <Plugins:[monitor_proc/falcon], Timestamp:1494497042>

谁能帮我查下这个setpgid 是怎么出现的不？

**Comment by laiwei** [comment]
有可能是plugins目录是一个软链的原因，你检查下

**Comment by Yuani** [comment]
直接复制agent/plugins 到open-falcon 同一级目录，还是一样的报错

[root@agent1  openfalcon]# ls -lh
total 9.1M
drwxr-xr-x 7 openfalcon openfalcon 4.0K May 11 10:25 agent
-rw-r--r-- 1 root       root       5.2M May 11 03:20 agent.tgz
-rw-r--r-- 1 root       root        298 Apr 10 02:44 monitor.sh
-rwxr-xr-x 1 root       root       3.8M May 11 03:12 open-falcon
drwxr-xr-x 6 openfalcon openfalcon 4.0K May 12 01:35 plugins
drwxr-xr-x 5 openfalcon openfalcon 4.0K May 12 01:42 public
[root@agent1    openfalcon]# ls agent -lh
total 24K
drwxr-xr-x 2 openfalcon openfalcon 4.0K May 11 03:12 bin
drwxr-xr-x 2 openfalcon openfalcon 4.0K May 12 01:50 config
-rw-r--r-- 1 openfalcon openfalcon  911 May 11 03:19 falcon_monitor.sh
drwxr-xr-x 2 openfalcon openfalcon 4.0K May 11 03:12 logs
drwxr-xr-x 6 openfalcon openfalcon 4.0K May 11 03:12 plugins
drwxr-xr-x 5 openfalcon openfalcon 4.0K May 11 03:12 public
[root@agent1    openfalcon]# tail -f agent/logs/agent.log 
2017/05/12 01:54:46 cfg.go:123: read config file: /data/openfalcon/agent/config/cfg.json successfully
2017/05/12 01:54:46 http.go:74: listening :19080
2017/05/12 01:55:46 var.go:88: => <Total=91> <Endpoint:agent1  , Metric:agent.alive, Type:GAUGE, Tags:, Step:60, Time:1494554146, Value:1>
2017/05/12 01:55:46 var.go:88: => <Total=11> <Endpoint:agent1  , Metric:df.bytes.total, Type:GAUGE, Tags:mount=/,fstype=ext4, Step:60, Time:1494554146, Value:8318783488>
2017/05/12 01:55:46 plugin.go:64: <Plugins:[monitor_proc/falcon], Timestamp:1494554146>
2017/05/12 01:55:46 var.go:88: => <Total=6> <Endpoint:agent1  , Metric:ss.slabinfo.timewait, Type:GAUGE, Tags:, Step:60, Time:1494554146, Value:0>
2017/05/12 01:55:46 var.go:95: <= <Total=91, Invalid:0, Latency=0ms, Message:ok>
2017/05/12 01:55:46 var.go:95: <= <Total=11, Invalid:0, Latency=0ms, Message:ok>
2017/05/12 01:55:46 var.go:95: <= <Total=6, Invalid:0, Latency=0ms, Message:ok>
2017/05/12 01:56:46 var.go:88: => <Total=91> <Endpoint:agent1  , Metric:agent.alive, Type:GAUGE, Tags:, Step:60, Time:1494554206, Value:1>
2017/05/12 01:56:46 var.go:88: => <Total=11> <Endpoint:agent1  , Metric:df.bytes.total, Type:GAUGE, Tags:mount=/,fstype=ext4, Step:60, Time:1494554206, Value:8318783488>
2017/05/12 01:56:46 var.go:95: <= <Total=91, Invalid:0, Latency=0ms, Message:ok>
2017/05/12 01:56:46 var.go:95: <= <Total=11, Invalid:0, Latency=0ms, Message:ok>
2017/05/12 01:56:46 scheduler.go:59: plugins/monitor_proc/falcon/60_run_process-check-scripts.py running...
2017/05/12 01:56:46 plugin.go:64: <Plugins:[monitor_proc/falcon], Timestamp:1494554206>
2017/05/12 01:56:46 cmd.go:43: Setpgid failed, error: permission denied
2017/05/12 01:56:46 var.go:88: => <Total=7> <Endpoint:agent1  , Metric:net.port.listen, Type:GAUGE, Tags:port=22, Step:60, Time:1494554206, Value:1>
2017/05/12 01:56:46 var.go:95: <= <Total=7, Invalid:0, Latency=0ms, Message:ok>
2017/05/12 01:56:46 var.go:88: => <Total=1> <Endpoint:agent1  , Metric:monitor_proc, Type:GAUGE, Tags:idc=AWS,project=falcon,app=tcping_3306.sh, Step:60, Time:1494554206, Value:1>
2017/05/12 01:56:46 var.go:95: <= <Total=1, Invalid:0, Latency=0ms, Message:ok>
2017/05/12 01:57:46 var.go:88: => <Total=91> <Endpoint:agent1  , Metric:agent.alive, Type:GAUGE, Tags:, Step:60, Time:1494554266, Value:1>

**Comment by laiwei** [comment]
**-rwxr-xr-x 1 root root 3.8M May 11 03:12 open-falcon**

chown -R openfalcon.openfalcon open-falcon/

**Comment by Yuani** [comment]
open-falcon 是启动命令，不是文件夹，全部改成openfalcon的也不行

**Comment by deep011** [comment]
这个问题是怎么解决的？

**Comment by shaohk** [comment]
请问我的代码已经是最新的了，为啥还会报这个错误呢？cmd.go:43: Setpgid failed, error: permission denied
