### ISSUE TITLE
open-falcon-agent是否可以DaemonSet方式部署在k8s集群里？

### ISSUE THREAD

**Issue by lf1029698952** [open-falcon/falcon-plus#774]
open-falcon-agent是否可以DaemonSet方式部署在k8s集群里？
这样在每次增减机器的时候就不用再单独去安装部署每个机器的agent了。

**Comment by walnut-tom** [comment]
可以的，我就这么干的

**Comment by walnut-tom** [comment]
#833 
[k8s-example DaemonSet](https://github.com/open-falcon/falcon-plus/blob/master/docker/k8s-example/openfalcon-plus.yaml)

**Comment by lf1029698952** [comment]
收到了，谢谢，目前我们已经采用prometheus+open falcon结合的方式共享打造混合云监控平台。
