### ISSUE TITLE
Open-falcon Core dump in arm64 platform

### ISSUE THREAD

**Issue by hellosfs** [open-falcon/falcon-plus#775]
./falcon-agent -c ../config/cfg.json 
2019/07/15 18:45:32 cfg.go:142: read config file: ../config/cfg.json successfully
2019/07/15 18:45:32 http.go:88: listening :1988
panic: runtime error: index out of range

goroutine 26 [running]:
github.com/open-falcon/falcon-plus/vendor/github.com/toolkits/nux.SocketStatSummary(0x400007ce48, 0x42eb6c, 0x400007ce98)
        /root/workspace/src/github.com/open-falcon/falcon-plus/vendor/github.com/toolkits/nux/ss_s.go:49 +0x5c4
github.com/open-falcon/falcon-plus/modules/agent/funcs.SocketStatSummaryMetrics(0x0, 0x0, 0x0)
        /root/workspace/src/github.com/open-falcon/falcon-plus/modules/agent/funcs/sockstat.go:24 +0x28
github.com/open-falcon/falcon-plus/modules/agent/cron.collect(0x3c, 0x40000b5b90, 0x2, 0x2)
        /root/workspace/src/github.com/open-falcon/falcon-plus/modules/agent/cron/collector.go:63 +0x110
created by github.com/open-falcon/falcon-plus/modules/agent/cron.Collect
        /root/workspace/src/github.com/open-falcon/falcon-plus/modules/agent/cron/collector.go:44 +0xc0

**Comment by hellosfs** [comment]
Can anyone helps me?

**Comment by laiwei** [comment]
falcon-agent is not tested in arm platform. @hellosfs
