### ISSUE TITLE
如何不通过api通过graph直接获取监控数据

### ISSUE THREAD

**Issue by wangdi244** [open-falcon/falcon-plus#776]
目前想调研一下如何不通过api，如何通过命令行或者其他方式获得监控数据，请问rddtools存储数据如何能调用监控数据，请指教！

**Comment by laiwei** [comment]
你也可以直接使用 rrdtool 命令行工具，文件格式是兼容的，不过建议的最佳实践仍然是通过 api 来访问，因为 counter 和 rrd 文件的对应关系，api 组件会自动解决。 @wangdi244
