### ISSUE TITLE
建议HostGroup增加一列显示IP地址

### ISSUE THREAD

**Issue by jiangbo0225** [open-falcon/falcon-plus#779]
![WN1VJ{}DJ {W0QXR9CZ X$2](https://user-images.githubusercontent.com/47810135/61701276-7ad17300-ad70-11e9-9580-9c48b0aade15.png)
建议HostGroup增加一列显示IP地址

**Comment by bfqymmt** [comment]
支持，不过agent里面返回是自定义的主机名，要改的东西比较多。

**Comment by laiwei** [comment]
> 支持，不过agent里面返回是自定义的主机名，要改的东西比较多。

是的，endpoint 和 host 现在是两个东西，不能一一对应。
