### ISSUE TITLE
怎么跳过登录，怎么创建一个只有查看权限的账号？

### ISSUE THREAD

**Issue by zerlee** [open-falcon/falcon-plus#780]
**问题：** 
每次查看dashboard都要登录，好麻烦，我又不做什么修改，只需要查看就行，没必要登录吧。 要是想把falcon推广到其他人用，难道还得给他们注册一个账号才能用？退一步说就算给他们注册了，他们登录上貌似是有修改权限的？这个不太好吧？

**需求：**
1、不需要登录就可以查看dashboard，但是没有修改权限。

2、如果上述无法实现。那么是否可以注册一个有只读权限的账号。让其他人可以公用。

**Comment by laiwei** [comment]
@zerlee  按照你的需求，修改这行代码 https://github.com/open-falcon/dashboard/blob/master/rrd/view/__init__.py#L62
