### ISSUE TITLE
一个graph中最多能添加多少个endpoint

### ISSUE THREAD

**Issue by ralph333** [open-falcon/falcon-plus#781]
一个graph中最多能添加多少个endpoint？ 我在v0.2版本上发现，一个graph最多只能显示153个endpoint，再多的话，在graph上显示不出。

另一个问题，我有一个脚本，脚本会自动发现一些docker容器并采集一些监控指标，并push到falcon中。在push中，设置的endpoint为docker的name。  push的api中有没有类似group的字段，可以将这些手动push的endpoint默认划分到一个组里去

**Comment by laiwei** [comment]
1. 一个 dashboard graph 中，能容纳的最大 endpoint 和 counter 数量，是受数据库表中这两个字段的最大长度限制的。 @ralph333 

![image](https://user-images.githubusercontent.com/792850/63390835-00355b00-c3e3-11e9-8972-c256274b4ad6.png)

2. push 数据的时候，你可以使用自定义 tag，比如 endpoint=xx, group=yy 即可。
