### ISSUE TITLE
某个主机不能发送报警

### ISSUE THREAD

**Issue by rockqwtest** [open-falcon/falcon-plus#785]
问题：模板和主机都正确配置后，满足模板的阈值设置，却不能发送报警信息，alarm日志也没有相关信息。
备注：当同样的条件，用其他主机测试时，能正确报警。

**Comment by mosesyu95** [comment]
确认下是否这台主机配置到多模板中

**Comment by rockqwtest** [comment]
主机有链接到2个不同的模板中

**Comment by rockqwtest** [comment]
![image](https://user-images.githubusercontent.com/49265450/63156697-d4634f80-c047-11e9-9490-fb987797cc0e.png)
![image](https://user-images.githubusercontent.com/49265450/63156780-083e7500-c048-11e9-9392-1d6ea3ca63e1.png)
能获取到值 也能获取到阈值，同时在主机组中添加了主机和模板。但就是不能报警出来。

**Comment by mosesyu95** [comment]
模板中是否存在相同counter。不同阈值？是否配置了自定义表达式

**Comment by rockqwtest** [comment]
模板中没有相同的counter，也未设置过任何表达式。

**Comment by laiwei** [comment]
@rockqwtest 可以多提供一些信息来判断，比如具体的模板和策略、以及 metric 曲线图等

**Comment by rockqwtest** [comment]
![image](https://user-images.githubusercontent.com/49265450/63160693-f7463180-c050-11e9-81b0-dd3eada06a9f.png)
![image](https://user-images.githubusercontent.com/49265450/63160734-15ac2d00-c051-11e9-8989-90b50b574e19.png)
![image](https://user-images.githubusercontent.com/49265450/63160771-2c528400-c051-11e9-883a-a39a64a06c70.png)
![image](https://user-images.githubusercontent.com/49265450/63160856-5e63e600-c051-11e9-92bf-d76435cbad46.png)

**Comment by rockqwtest** [comment]
已找到原因，是我自己模板设置的问题。
