### ISSUE TITLE
如何配置域名访问

### ISSUE THREAD

**Issue by mspy1985** [open-falcon/falcon-plus#788]
![image](https://user-images.githubusercontent.com/49383154/63147553-1cc34300-c031-11e9-9de8-99e18a0582f2.png)
为了提高集群高可用性，需要配置域名访问，架构图上显示可以对hbs ，transfer，query，judge 配置域名访问，对agent配置域名后：报错
2019/08/15 11:33:12 rpc.go:56: dial falcon-transfer.service fail: dial tcp: address falcon-transfer.service: missing port in address

如何解决

**Comment by mosesyu95** [comment]
没加上端口

**Comment by mspy1985** [comment]
> 没加上端口

域名没有端口啊

**Comment by mspy1985** [comment]
配置域名加端口后显示：invalid character 'H' looking for beginning of value

**Comment by laiwei** [comment]
> 配置域名加端口后显示：invalid character 'H' looking for beginning of value

出现这种报错，一般是把 http 端口和 rpc 端口配置混乱了。 @mspy1985
