### ISSUE TITLE
start api报错

### ISSUE THREAD

**Issue by toffstechzhang** [open-falcon/falcon-plus#790]
start api报错

 ./falcon-plus start api
fork/exec /falcon-plus/api/bin/falcon-api: no such file or directory

**Comment by mosesyu95** [comment]
./open-falcon start api

**Comment by toffstechzhang** [comment]
参考了：
https://github.com/open-falcon/falcon-plus/issues/142

1，export GOPATH=~/Dev/go
2，go get github.com/open-falcon/falcon-plus
3，cd $GOPATH/src/github.com/open-falcon/falcon-plus
4，make all

现在不报错了，

**Comment by mamh2021** [comment]
-bash: ./bin/falcon-agent: No such file or directory
这个依赖什么环境吗？ go的环境？

**Comment by mosesyu95** [comment]
确认下你的目录是不是正确，使用的是相对目录
或者使用绝对目录试试
