### ISSUE TITLE
api中查询step返回数据永远是0。代码如下。请查看

### ISSUE THREAD

**Issue by mosesyu95** [open-falcon/falcon-plus#791]
代码如下：
func getCounterStep(endpoint, counter string) (step int, err error) {
	cache_key := fmt.Sprintf("step:%s/%s", endpoint, counter)
	s, found := localStepCache.Get(cache_key)
	if found && s != nil {
		step = s.(int)
		return
	}

	var rows []int
	dt := db.Graph.Raw(`select a.step from endpoint_counter as a, endpoint as b
		where b.endpoint = ? and a.endpoint_id = b.id and a.counter = ? limit 1`, endpoint, counter).Scan(&rows)
	if dt.Error != nil {
		err = dt.Error
		return
	}
	if len(rows) == 0 {
		err = errors.New("empty result")
		return
	}
	step = rows[0]
	localStepCache.Set(cache_key, step, tcache.DefaultExpiration)

	return
}

debug如下

(/usr/lib/golang/src/github.com/open-falcon/falcon-plus/modules/api/app/controller/graph/graph_controller.go:465) 
[2019-08-16 16:38:57]  [0.52ms]   select a.step from endpoint_counter as a, endpoint as b
                where b.endpoint = '10.0.0.107' and a.endpoint_id = b.id and a.counter = 'agent.alive' limit 1
time="2019-08-16T16:38:57+08:00" level=warning msg="db found [0]"

**Comment by laiwei** [comment]
请看看 db 中是否真的存在 10.0.0.107 这个 endpoint 以及 agent.alive 这个 metric  @mosesyu95 

```where b.endpoint = '10.0.0.107' and a.endpoint_id = b.id and a.counter = 'agent.alive'```

**Comment by mosesyu95** [comment]
肯定存在的，我手动执行这个命令是可以查到的。但是代码中就是为空
