### ISSUE TITLE
使用非3306端口的MySql数据库dashboard拒绝访问

### ISSUE THREAD

**Issue by geeksun** [open-falcon/falcon-plus#793]
openfalcon的部署方式为使用docker， 参照： https://github.com/open-falcon/falcon-plus/blob/master/docker/README.md 
其中使用 MySql 数据库端口不是默认的3306端口， 使用自定义的 3308 端口，当启动falcon-plus和各个module后，访问 dashboard 的 host:8081，提示“Error: HTTPConnectionPool(host='api.falcon', port=8080): Max retries exceeded with url: /api/v1/user/current (Caused by : [Errno 111] Connection refused)
”，查看各个Module的启动情况，显示 api、alarm等module没启动成功，api.err日志显示“time="2019-08-19T03:58:10Z" level=fatal msg="db conn failed with error connect to falcon_portal: dial tcp 172.17.0.3:3308: connect: connection refused”。
如果端口换成 3306 则能正常启动，换成 3306 以外的端口就不行，这是怎么回事？

**Comment by laiwei** [comment]
请在 docker run 的时候，修改端口为3308  @geeksun 

``` docker run -itd --name falcon-plus \
         --link=falcon-mysql:db.falcon \
         --link=falcon-redis:redis.falcon \
         -p 8433:8433 \
         -p 8080:8080 \
         -e MYSQL_PORT=root:test123456@tcp\(db.falcon:3306\) \
         -e REDIS_PORT=redis.falcon:6379  \
         -v /home/work/open-falcon/data:/open-falcon/data \
         -v /home/work/open-falcon/logs:/open-falcon/logs \
         openfalcon/falcon-plus:v0.3
```

**Comment by geeksun** [comment]
> 请在 docker run 的时候，修改端口为3308 @geeksun
> 
> ```
>          --link=falcon-mysql:db.falcon \
>          --link=falcon-redis:redis.falcon \
>          -p 8433:8433 \
>          -p 8080:8080 \
>          -e MYSQL_PORT=root:test123456@tcp\(db.falcon:3306\) \
>          -e REDIS_PORT=redis.falcon:6379  \
>          -v /home/work/open-falcon/data:/open-falcon/data \
>          -v /home/work/open-falcon/logs:/open-falcon/logs \
>          openfalcon/falcon-plus:v0.3
> ```

docker run 的时候，把 db.falcon 的端口改成 3308， 还是提示 Connect refused。
