### ISSUE TITLE
安装dashboard，报错ImportError: No module named ext.babel。

### ISSUE THREAD

**Issue by yourshishi** [open-falcon/falcon-plus#796]
按照教程进行安装，执行./env/bin/python wsgi.py时报错ImportError: No module named ext.babel。
安装细节：在执行./env/bin/pip install -r pip_requirements.txt -i https://pypi.douban.com/simple时会报错，所以就去掉了后边的-i https://pypi.douban.com/simple。
1、看到又说将pip_requirements.txt修改Werkzeug==0.11.15，试了，也是报这个错。

**Comment by yourshishi** [comment]
环境：centos7，python2.7.5.

**Comment by laiwei** [comment]
fixed https://github.com/open-falcon/dashboard/pull/138 @yourshishi
