### ISSUE TITLE
关于judge模块的 (this *JudgeItemMap) PushFrontAndMaintain method

### ISSUE THREAD

**Issue by rongyi** [open-falcon/falcon-plus#80]
里面的处理，对于不是首条数据会在 (* SafeLinkedList) PushFronAndMaintain中进行校验，而第一条数据则上来就入链了，是不是默认首条数据就是合法的？

**Comment by laiwei** [comment]
@rongyi 是的

这里是为了保障每个周期，多次push数据，只有第一次push的会被采用

**Comment by rongyi** [comment]
恩，多谢多谢！
