### ISSUE TITLE
一个step周期内，多次上传相同的endpoint counter会怎么样？

### ISSUE THREAD

**Issue by mosesyu95** [open-falcon/falcon-plus#805]
自定义数据上传，为了防止单点问题。我在多个设备上传相同数据，但是value有少量差异。
一个step周期没。多次上传相同的endpoint counter会怎么样？
是替换掉还是会丢弃。以那次上传为准？
先这么提问，有知道的回答下。
没有我有时间录下代码。到时候分享给大家

**Comment by mdh67899** [comment]
> 是替换掉还是会丢弃。以那次上传为准？

从judge和graph的角度来说: 同一个周期内同一个metric数据，直接以先收到的数据为准，后来的就直接丢弃掉了
