### ISSUE TITLE
如何通过接口获取到所有状态为PROBLEM且未恢复到OK状态的报警？

### ISSUE THREAD

**Issue by liyongzhezz** [open-falcon/falcon-plus#808]
如题，目前想通过接口获取到所有状态为PROBLEM且未恢复到OK状态的报警，使用 /api/v1/alarm/eventcases 接口发现只能获取到所有的PROBLEM状态的报警（即使报警已经恢复），想请问下大家这样的需求大家是如何做的。

感谢~

**Comment by laiwei** [comment]
直接参考 dashboard 的代码吧，可以获取到当前未恢复的报警：https://github.com/open-falcon/dashboard/blob/master/rrd/model/portal/alarm.py#L75  @liyongzhezz
