### ISSUE TITLE
客户机与监控服务端时区不同的问题

### ISSUE THREAD

**Issue by ZCchann** [open-falcon/falcon-plus#811]
当前监控环境下存在多个不同时区的主机
部署agent完成后过几个小时就会出现agent掉线的情况
掉线的主机是与监控服务端主机时区不同的机器
是否可以在agent的配置文件内添加时间戳来改善这个问题？

**Comment by laiwei** [comment]
1. 目前是以 agent 所在的机器的时间戳为准。
2. agent 掉线指的是什么现象？ @ZCchann

**Comment by ZCchann** [comment]
不好意思表达的不是特别清楚
比如说  我的agent主机比我的服务端时间少6个小时（两台主机时区不同）
刚开始打开agent没什么问题 但是过几天以后  open-falcon 服务端web页面上这台主机的曲线会消失  如果去搜6个小时以前的会有曲线图

掉线是指 如果那时候我的报警设定agent为-1的时候推送报警的话  那么这台时区不同的agent主机会呈现掉线的状态
@laiwei
