### ISSUE TITLE
关于组合策略

### ISSUE THREAD

**Issue by xing-tai** [open-falcon/falcon-plus#813]
组合策略即多个告警条件组合成一个策略，如 `agent.alive:all(#3) > 0 && cpu.busy:all(#3) > 90`

看挺多人有这个需求的    
我也想增加这块的支持，有人已经在做或者有规划了吗？可以一起讨论

**Comment by liuhaoXD** [comment]
[美团已经有过实践了](https://tech.meituan.com/2017/02/24/mt-falcon-monitoring-system.html)。他们的策略是额外新建一个 module，用户配置好多条件后，judge 的职能依然是计算子条件的情况（例如 agent.alive:all(# 3)），然后，如果 judge 发现这个子条件是某个多条件策略的组成部分，就会将该子条件的计算结果推送到新建的上层 module，由上层继续进行计算。

Open-Falcon 本身是基于一致性 hash 做分片和负载均衡的，在这个前提下，仅在原有的 judge 模块上完成多条件判断实现成本很高（指标数据会被一致性 hash 分到其他实例上），因此现有的解决方案，要么是像美团这样，在 judge 之上新建一个 module 完成聚合，要么就是铲掉现有的 judge 逻辑和架构设计，新起一套支持多条件的计算 module

**Comment by jinxingxing** [comment]
现在一致性 hash 使用的 key 是 (endpoint,metric,tags)，如果改成以 endpoint 为 key 就能保证同一台机器的数据被 push 到同一个 judge 实例了吧，同时我们做复合策略匹配也是只针对同一台机器的指标

**Comment by laiwei** [comment]
> 组合策略即多个告警条件组合成一个策略，如 `agent.alive:all(#3) > 0 && cpu.busy:all(#3) > 90`
> 
> 看挺多人有这个需求的
> 我也想增加这块的支持，有人已经在做或者有规划了吗？可以一起讨论

组合策略，在夜莺中支持的更好 https://github.com/didi/nightingale , 你可以评估下。 @xing-tai
