### ISSUE TITLE
我想监控目标对象网络通不通，这种情况也要安装插件吗？

### ISSUE THREAD

**Issue by zhangjianpinghik** [open-falcon/falcon-plus#819]
请教下，我想监控目标对象网络通不通，这种情况也要安装插件吗？监控的对象主要是各种类型的网络设备比如linux windows 交换机 路由器等各种网络设备，像这种网络通不通的监控不能像zabbix那样不用安装agent就可以监控吗？

**Comment by walnut-tom** [comment]
open-falcon 好多都需要单独的插件

**Comment by liuhaoXD** [comment]
网络通不通有很多检查方式，比如向统一的探活端口建立 tcp 连接，向主机发起 icmp 请求等等，不同公司采用的策略也都不一样。
而且网络判通这是一个双向的过程，既要判断一个机器A是否能连通其他主机，又要判断其他主机能否连通A。所以这个单纯靠 agent 自己是不太好实现的，还是自己写个插件，详细设计一下才行。
