### ISSUE TITLE
报警误报的问题

### ISSUE THREAD

**Issue by tonygshliu** [open-falcon/falcon-plus#82]
metric/tags [note]	condition	max	P	run	operation
cash.amount.diff [当前值比昨日同期值少于百分之80]	all(#1)<=-80	1	3		 
cash.amount.diff [当前值比昨日同期值大于百分之80]	all(#1)>=80	1	3	

上面是我设置的报警策略，

但是我发现有误报情况，
OK
P3
Endpoint:NON.LTD
Metric:cash.amount.diff
Tags:
**all(#1): -70.81019<=-80**
Note:当前值比昨日同期值少于百分之80
Max:1, Current:1

请问为什么会造成这种现象呢？

**Comment by masato25** [comment]
@tonygshliu  这个不是误报.
讯息内容是显示  'OK' 而不是 'PROBLEM'.
OK的时候表示的是该告警已经恢复时的讯息.

**Comment by tonygshliu** [comment]
哦，了解了，请问我可以关闭这种 OK讯息显示吗？Thanks again.
