### ISSUE TITLE
关于通过api获取历史数据

### ISSUE THREAD

**Issue by liyongzhezz** [open-falcon/falcon-plus#820]
我目前通过 /api/v1/graph/history 来获取历史数据，发现获取到的历史数据似乎被稀释了，并不是实际当时推送的值，请教下这是什么原因？falcon有什么数据稀释策略吗？

**Comment by liuhaoXD** [comment]
open-falcon 默认使用 RRDTool 作为存储，每经过一段时间之后，历史数据会按配置进行采样归档。详见https://book.open-falcon.org/zh/dev/change_graph_rra.html
