### ISSUE TITLE
agent模块什么时候支持docker部署呢

### ISSUE THREAD

**Issue by patience00** [open-falcon/falcon-plus#822]

**Comment by liuhaoXD** [comment]
联系部门运维同学，把 agent 写进 Dockerfile 模板。

**Comment by walnut-tom** [comment]
[](https://github.com/open-falcon/falcon-plus/issues/774)

**Comment by walnut-tom** [comment]
Latest commit [46ec795](https://github.com/open-falcon/falcon-plus/commit/46ec795)
See docker [README.md](https://github.com/open-falcon/falcon-plus/blob/master/docker/README.md)
