### ISSUE TITLE
agent post成功后，服务端没有收到数据。

### ISSUE THREAD

**Issue by rockqwtest** [open-falcon/falcon-plus#823]
![image](https://user-images.githubusercontent.com/49265450/67666364-9c14b180-f9a6-11e9-8ab6-4e63e93d4c88.png)
open-falcon 通过python脚本像agent 端口post数据。但是agent上传后，服务端没有收到数据。

**Comment by laiwei** [comment]
metric value 只能是整数或者浮点数，从截图中，都是 invalid。 @rockqwtest

**Comment by rockqwtest** [comment]
那如果这种情况，我怎么来查看具体是哪些是无效的呢。 @laiwei 
![image](https://user-images.githubusercontent.com/49265450/67668115-43dfae80-f9aa-11e9-9f92-0c56d0f198f8.png)

**Comment by JimmyTinsley** [comment]
> 
> 
> 那如果这种情况，我怎么来查看具体是哪些是无效的呢。 @laiwei
> ![image](https://user-images.githubusercontent.com/49265450/67668115-43dfae80-f9aa-11e9-9f92-0c56d0f198f8.png)

修改代码, 重新编译agent, 把所有invalid的metric和value打印在日志里

**Comment by rockqwtest** [comment]
好的，非常感谢。 @laiwei
