### ISSUE TITLE
Agent 配置网络接口名为什么不使用排除法？

### ISSUE THREAD

**Issue by shaneing** [open-falcon/falcon-plus#825]
因为网卡接口的名字并没有统一，所以你很难确定它的名字时怎么样。如果这个变更后的名字并没有出现在你的配置里，那么意味着漏掉了这个网络接口。

如果用排除的方式，反而可以大致知道一些虚拟设备的名字，比如 `docker0` 等。

**Comment by liuhaoXD** [comment]
传统场景下，正规的生产环境里为了便于管理，虚机网卡接口命名都是统一的，docker 这种其实是特例。
时->是，注意错别字。。

**Comment by shaneing** [comment]
@liuhaoXD 也是，多谢。话说有没有什么群可以讨论的，太难受了。
