### ISSUE TITLE
查看历史数据出现断点

### ISSUE THREAD

**Issue by JimmyTinsley** [open-falcon/falcon-plus#828]
在falcon-agent的plugin执行时间较长(数据量较大), 且执行开始与执行结束的时间不在同一分钟内的时候(例如上一分钟的55秒开始执行, 下一分钟的05秒执行完毕, 共执行10s). 这种情况会导致查看历史数据时, 最近20分钟左右的数据出现较为严重的断点情况. 
![图片](https://user-images.githubusercontent.com/37508117/67850944-60175300-fb44-11e9-816f-abfea8d97d65.png)
![图片](https://user-images.githubusercontent.com/37508117/67851005-7b825e00-fb44-11e9-9879-c6c71349576e.png)
![图片](https://user-images.githubusercontent.com/37508117/67851016-8210d580-fb44-11e9-9aca-33b93f8ec52a.png)

例如以上三台主机的监控图, 这三台主机的plugin运行状况均符合上面的描述.

经过反复试验, 该结果可以稳定复现. 出现断点的主机重启agent使插件运行不跨分钟可以暂时解决这个问题. 但是比较奇怪的是只有最近20分钟的数据会出现断点, 在过一段时间之后, 这些断掉的数据点又全部连起来了, 没有任何丢数据的情况, 是否说明是在标准化agent上报的数据的时间戳的时候出现问题?

**Comment by liuhaoXD** [comment]
检查一下插件返回值实际传给 agent 的数据。真实数据比图更加直观。

**Comment by laiwei** [comment]
@JimmyTinsley 把 agent plugin 采集的数据点打印出来看看吧

**Comment by JimmyTinsley** [comment]
@liuhaoXD @laiwei 

仔细研究了插件上报的数据, 推测是如下原因导致出现断点:
由于插件采集数据量较大, 为了避免CPU占用过高, 有一个随机1-5秒的delay, 导致实际上上报数据的时候, 时间戳会有1-5秒的波动. 出现断点的主机插件运行的时间都是在一分钟内的第57秒左右, 这样如果随机的delay在3秒以内的话, 上报数据的时间戳就是在这分钟之内, 如果delay是4或者5, 那时间戳就属于下一分钟了. 目前来说解决办法有重启agent刷新插件的运行时间, 或者把插件里面的时间戳统一固定为delay之前的, 这两个办法都不会再出现断点的情况. 

不过还是想请问下, 为什么只有前30分钟会出现断点, 之后就又把断点连上了? open-falcon是如何对时间戳进行标准化的?

**Comment by walnut-tom** [comment]
我印象中时间截取是向下取整，结果类似 **ts / step * step**
个人感觉可以 _**(ts + step/2) / step * step**_, 只不过可能会看见未来的时间。

**Comment by laiwei** [comment]
> 不过还是想请问下, 为什么只有前30分钟会出现断点, 之后就又把断点连上了? open-falcon是如何对时间戳进行标准化的?
--------

open-falcon 会对历史数据进行归档，即将历史上的多个点合并为一个点（降低数据的存储精度），譬如，把5个点合并为1个点的过程中，只要这5个点中有超过半数是合法的值，就合并成功，否则合并结果为 NaN。

所以你看到的断点连上了，是因为在合并的过程中，大多数点都是存在的，合并都成功了。 @JimmyTinsley

**Comment by JimmyTinsley** [comment]
> 
> 
> > 不过还是想请问下, 为什么只有前30分钟会出现断点, 之后就又把断点连上了? open-falcon是如何对时间戳进行标准化的?
> 
> open-falcon 会对历史数据进行归档，即将历史上的多个点合并为一个点（降低数据的存储精度），譬如，把5个点合并为1个点的过程中，只要这5个点中有超过半数是合法的值，就合并成功，否则合并结果为 NaN。
> 
> 所以你看到的断点连上了，是因为在合并的过程中，大多数点都是存在的，合并都成功了。 @JimmyTinsley

明白了, 谢谢解答 @laiwei
