### ISSUE TITLE
新加agent节点1988端口可以查到数据，但是在server端的dashboard上看不到值。

### ISSUE THREAD

**Issue by 13691432320** [open-falcon/falcon-plus#830]
我新家的三台机器到我的监控系统中，agent起来后。发现
![image](https://user-images.githubusercontent.com/41263103/68069432-078dc300-fd9b-11e9-9015-7739066adbaf.png) 1988端口是可以访问通的。但是当我访问我的dashboard时 新加的机器的值都是NaN状态。 
![image](https://user-images.githubusercontent.com/41263103/68069445-2f7d2680-fd9b-11e9-9801-d57caaa05a47.png)
各组件的状态也是健康的。 
![image](https://user-images.githubusercontent.com/41263103/68069463-4f144f00-fd9b-11e9-8d14-70c607846e5a.png)
bing qie并且数据库运作正常
![image](https://user-images.githubusercontent.com/41263103/68069480-681d0000-fd9b-11e9-88f7-37a80250f32c.png)

Oh , 两个小时也没有找到解决办法，之前我的其他机器都是通过此方式进行的。
希望有大佬指点。 我的邮件是 qihongjiang@momenta.ai

**Comment by liuhaoXD** [comment]
检查NaN机器上 agent 的配置文件，检查agent所在机器能不能连通transfer的端口。btw，遇事不决翻日志。

**Comment by 13691432320** [comment]
> 检查NaN机器上 agent 的配置文件，检查agent所在机器能不能连通transfer的端口。btw，遇事不决翻日志。

No 端口肯定是通的 我测试过了。 日志翻边了 都没有异常。

**Comment by 13691432320** [comment]
> 检查NaN机器上 agent 的配置文件，检查agent所在机器能不能连通transfer的端口。btw，遇事不决翻日志。

我现在怀疑是时区问题。

**Comment by 13691432320** [comment]
WTF ！ 
果然是时区的问题。
啧啧啧
