### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by walnut-tom** [open-falcon/falcon-plus#834]
用一下命令启动打开 1988 端口显示 “404 page not found”
/opt/app/falcon-plus/agent/bin/falcon-agent -c /opt/app/falcon-plus/agent/config/cfg.json

**Comment by laiwei** [comment]
检查一下你的 agent 目录下的 public 文件夹是否存在  @walnut-tom 
![image](https://user-images.githubusercontent.com/792850/68581158-cdb36f80-04b2-11ea-85c0-82faec8ad4a6.png)

**Comment by walnut-tom** [comment]
> 检查一下你的 agent 目录下的 public 文件夹是否存在 @walnut-tom
> ![image](https://user-images.githubusercontent.com/792850/68581158-cdb36f80-04b2-11ea-85c0-82faec8ad4a6.png)

不是 public 目录的问题，是agent访问public目录用的是相对路径(相对于当前路径),使用绝对路径运行时当前路径下未必包含 public 或者 public 的link，建议使用配置文件，或者 使用 args[0] 获取public的路径。
```
var Root string

func InitRootDir() {
	var err error
	Root, err = os.Getwd()
	if err != nil {
		log.Fatalln("getwd fail:", err)
	}
}
```

**Comment by laiwei** [comment]
欢迎提交 PR :)  @walnut-tom
