### ISSUE TITLE
请问agent原生是否支持ntp偏移量采集?

### ISSUE THREAD

**Issue by JimmyTinsley** [open-falcon/falcon-plus#840]
如falcon-plus的文档中描述的:
https://github.com/open-falcon/book/blob/30cbe7d45f4e1ddfafc54f00006ef63b8710b0f7/zh/faq/linux-metrics.md#ntp%E9%87%87%E9%9B%86%E9%A1%B9

> 每个类别，具体的详细指标如下，这些指标，都是open-falcon的agent组件直接支持的。falcon-agent每隔一定时间间隔（目前是60秒）会采集一次相关的指标，并汇报给server端。

> ntp采集项
> 使用 ntpq -pn 获取本机时间相对于 ntp 服务器的 offset。
> sys.ntp.offset： 本机偏移时间，单位为ms，值过大或者为0则表明有异常，需要报警

我在配置中没有忽略这个`sys.ntp.offset`监控项, 但是无法获取到这一项的监控数据. 在代码中查询, 发现agent里没有和`ntp`关键字相关的代码. 请问agent本身是否支持ntp偏移量的采集? 或者是否需要什么操作来打开这一项的数据采集? @laiwei

**Comment by JimmyTinsley** [comment]
是否只能通过类似https://github.com/open-falcon/plugin/blob/6d6e75aca1177bfc84327168c0a2134237bac419/sys/ntp/600_ntp.py 的脚本才能实现ntp的监控?

**Comment by liuhaoXD** [comment]
文档是 @UlricQin 写的，插件是 @laiwei 写的。看样子，ntp 这个功能是在实现 agent 的过程中，为了减少对命令的依赖而改成了用插件，选择性支持。

**Comment by JimmyTinsley** [comment]
> 
> 
> 文档是 @UlricQin 写的，插件是 @laiwei 写的。看样子，ntp 这个功能是在实现 agent 的过程中，为了减少对命令的依赖而改成了用插件，选择性支持。

早期版本的agent似乎是有这个功能的, 可能是更新过程中有其他的考虑吧

**Comment by laiwei** [comment]
@JimmyTinsley ntp offset，需要绑定插件。
