### ISSUE TITLE
disk.io  采集频率1s 计算是和前一秒数值计算 上传频率60秒  会不会导致中间的58秒数据丢失  

### ISSUE THREAD

**Issue by seven-and-hu** [open-falcon/falcon-plus#848]
采集频率1s 
计算是和前一秒数值计算 
上传到transfer是60秒 
会不会导致中间的58秒数据丢失？

**Comment by liuhaoXD** [comment]
上传频率60秒是什么意思？看不懂题意

seven-and-hu <notifications@github.com> 于2019年12月25日周三 下午5:27写道：

**Comment by seven-and-hu** [comment]
@liuhaoXD   就是agent上传到transfer的时间间隔是60秒。

**Comment by UlricQin** [comment]
监控数据的采集当前只能这么做，没有特别好的办法。disk.io相关的，是取最近1s的均值，cpu之类的是取最近3s的均值，可以反映上报那个时刻的机器负载情况。

如果60s上报一次，有59s的数据是采集不到的，这也是必然的，除非每秒采集一次并上报，才能做到每秒负载的监控数据都是准确的。

另外，取60s的平均值是否可行？这也是一种做法，但是会让曲线变平滑，削峰填谷，比如前面30s负载为0，后面30s负载为100，如果是取平均，得到的值是50，如果是上报之前取瞬时那一秒的值，得到的值是100，从运维角度来看，还是希望得到真实峰值，所以，倾向后者的逻辑。但是采集的时刻如果恰好是前面30s，得到的值就是0，看起来也不太友好。所以，可以适当调高频率，比如20s采集一次。

对负载数据的监控，本质就是一个采样逻辑，而采样带来的弊端，也只能接受...
