### ISSUE TITLE
关于 Dashboard 登录的问题

### ISSUE THREAD

**Issue by yao-hang** [open-falcon/falcon-plus#85]
刚刚入坑，今天安装好之后登录Dashboard发现无须任何认证，直接注册账号即可登录

因为这个是暴露在公网的，感觉有点危险

请问这个有什么认证方式我没找到还是本身就没有认证的？

**Comment by laiwei** [comment]
不要暴露在公网

**Comment by yao-hang** [comment]
@laiwei 如果我在使用的时候开启Dashboard，配置好告警规则之类的，然后关闭掉，在使用的时候再开启，这样是否可行？
