### ISSUE TITLE
二次开发启动

### ISSUE THREAD

**Issue by chainingning** [open-falcon/falcon-plus#852]
公司想二次开发，要在本地（windows）上运行起来并做调试，请问有文档说明吗，谢谢~

**Comment by liuhaoXD** [comment]
把程序里硬编码的路径改一改应该没什么问题了，比较麻烦的是 graph 模块，需要通过 gcc 等编译器编译 rrd，windows 环境安 gcc 是一件挺恶心的事。。

**Comment by chainingning** [comment]
> 把程序里硬编码的路径改一改应该没什么问题了，比较麻烦的是 graph 模块，需要通过 gcc 等编译器编译 rrd，windows 环境安 gcc 是一件挺恶心的事。。

我在goland上想跑一下，然后开发调试，现在就是不太清楚他的启动流程

**Comment by laiwei** [comment]
不推荐在 windows 上开发和运行 open-falcon 的服务端，之前 服务端的设计编码没有考虑过对 windows的兼容 @chainingning

**Comment by chainingning** [comment]
> 不推荐在 windows 上开发和运行 open-falcon 的服务端，之前 服务端的设计编码没有考虑过对 windows的兼容 @chainingning

那开发环境也选择linux吗
