### ISSUE TITLE
数据存储到ElasticSearch能否支持？

### ISSUE THREAD

**Issue by HeZhanfeng** [open-falcon/falcon-plus#856]
可否支持数据存储到ElasticSearch

**Comment by 1again** [comment]
正在做, 准备在agent上增加配置, 转发到es上.

主要考虑, es和agent会部署在同一内网. 
如果走transfer, 就会出现 agent(内网)->transfer(外网)->es(内网), 浪费资源

大家有什么想法吗.

**Comment by laiwei** [comment]
可以修改 transfer 的代码，将数据打入 mq，你可以消费 mq。这样会更通用。 @HeZhanfeng
