### ISSUE TITLE
詢問Falcon + 監控頁面上, 資料庫指標的單位是什麼 ?

### ISSUE THREAD

**Issue by wei5523** [open-falcon/falcon-plus#862]
請問下列這幾個資料庫的指標, 在監控頁面上的單位是什麼 ? 有進資料庫去比對過, 但查出來的值與監控頁面上的不符合,  例如進資料庫查到的Com_update 的值為 0, 但監控頁面上有值, 而且還有小數點  ?

Connections
Connection_errors_internal
Aborted_connects
Connection_errors_max_connections
Com_select
Com_insert
Com_update
Com_delete

<img width="775" alt="monitor" src="https://user-images.githubusercontent.com/28132838/75435824-90ee8400-598e-11ea-8197-b3e2639cf51e.png">

**Comment by laiwei** [comment]
以Com_update为例子，这个metric的类型是计数器类型。在dashboard上展示的值为当前值减去上次值，然后除以step，代表变化率。

@wei5523
