### ISSUE TITLE
0.3版本是还没发布么？

### ISSUE THREAD

**Issue by delkar** [open-falcon/falcon-plus#863]
0.3版本的metric有个TcpExt.TW在0.2文档里没有找到解释，不知道做什么的。
如果用在生产环境目前还是用0.2比较好是么？0.2正式发布有计划么？

**Comment by laiwei** [comment]
https://github.com/open-falcon/falcon-plus/releases/tag/v0.3

生产环境可以直接使用的，有一些优化和 bugfix。 @delkar
