### ISSUE TITLE
graph组件内存占用以及优雅宕机的问题

### ISSUE THREAD

**Issue by JimmyTinsley** [open-falcon/falcon-plus#866]
1. 昨天发现graph组件的内存占用异常升高, 之前平稳在45%, 然后突然两小时内上涨到了95%以上. 排查很多方向都没有找到结果, 非debug日志模式, graph也没有打印出任何日志. 
开启debug重启graph之后, 发现有大量invalid counter的错误日志, 原因是上报的metric里面含有特殊字符,  **请问这种情况下会导致graph内存占用升高吗?** graph使用的内存中应该大部分都是缓存的未落盘的数据点, 观察到内存上涨的这段时间中, `disk.io.write_bytes`监控项值比平时低了50%-60%.

2. 由此引申出优雅宕机的问题. 由于内存占用过高, 只能够先重启组件. 使用 ./open-falcon restart graph发现重启失败, 进程还一直存活着, 发现是graph卡在优雅宕机的流程中. 在测试环境中仅有不到10个endpoint的时候, graph组件flush rrd的操作可以在1秒之内完成, 但是生产主机最后重启graph的时候, graph占用了大约14G的内存, 这个时候flush rdd的速度变得奇慢无比, 大约10分钟打印一条 `rrdtool.go:240: flush hash idx:180 size:1800 disk:00000091 net:00000000` 这样的日志. 
**所以想请问下, graph flush rrd的性能是本身就如此的吗? 或者说在这种情况下, 有没有其他可以处理好graph组件重启, 又不丢失太多数据的方法?** 

如果有没说清楚的地方望提出, 我再补充细节.  问题比较复杂, 望解答, 谢谢!

**Comment by JimmyTinsley** [comment]
第一个问题自己解答了. 
这种情况不会导致内存占用过高, 只会打出很多debug日志. 内存上涨的根本原因是磁盘写入性能突降, graph内存中缓存的数据点来不及落库到磁盘上一直堆积, 所以导致内存占用持续上涨. 
磁盘性能突降应该是我们主机服务商的问题, 与graph组件本身无关.

**Comment by shaneing** [comment]
让 graph 在 flush 的时候，fork 另外一个进程去接受请求，flush 完毕后结束父进程。但是这里有个注意的地方，fork 的另外一个进程在 flush 完毕之前可以接受请求，但不能写数据。

**Comment by JimmyTinsley** [comment]
> 
> 
> 让 graph 在 flush 的时候，fork 另外一个进程去接受请求，flush 完毕后结束父进程。但是这里有个注意的地方，fork 的另外一个进程在 flush 完毕之前可以接受请求，但不能写数据。

你好, 感谢回复.
请问fork 另一个graph进程具体需要怎样操作呢? 
还有就是, fork出来的另外一个进程可以接收请求但不能写数据, 那么说明数据应该也是暂存在内存中的吧? 倘若这时本身是因为graph内存占满机器内存才需要重启, 那么新fork的进程会继续吃掉很多内存吧... 我这样理解正确吗? 如有错误请指出.

**Comment by shaneing** [comment]
> > 让 graph 在 flush 的时候，fork 另外一个进程去接受请求，flush 完毕后结束父进程。但是这里有个注意的地方，fork 的另外一个进程在 flush 完毕之前可以接受请求，但不能写数据。
> 
> 你好, 感谢回复.
> 请问fork 另一个graph进程具体需要怎样操作呢?
> 还有就是, fork出来的另外一个进程可以接收请求但不能写数据, 那么说明数据应该也是暂存在内存中的吧? 倘若这时本身是因为graph内存占满机器内存才需要重启, 那么新fork的进程会继续吃掉很多内存吧... 我这样理解正确吗? 如有错误请指出.

1. graph 退出时会 flush，这时应该会释放内存吧？
2. fork 的话有很多例子呢，比如 http server graface stop 就有这样的例子。
