### ISSUE TITLE
请问如何配置n次提交全部相等，则触发报警的函数

### ISSUE THREAD

**Issue by peterpan0708** [open-falcon/falcon-plus#868]
我想监控的值，理论上应该是递增的。如果3次提交全部相等，（即相减全等于0），则报警，请问用哪个函数可以实现这个需求呢。

**Comment by laiwei** [comment]
这个 metric，在提交的时候，可以设置其为计数器类型。对于计数器类型的 metric，open-falcon 在存储的时候会存储为变化率。这时候可以设置连续三次为0，即 `all(#3)=0` 就可以触发你这个场景了。  @peterpan0708
