### ISSUE TITLE
Alarm偶尔不发恢复的告警

### ISSUE THREAD

**Issue by scorpio1003** [open-falcon/falcon-plus#869]
alarm版本0.2.0  类似磁盘容量超过阈值时间会报警，等低于阈值的时候偶尔出现报不出恢复的告警，

页面上能看到恢复的报警信息，但是却收不到报警，查了alarm的日志，这种情况的时候都没有"send mail这个事件的日志，设置的api那边也没收到恢复报警的请求，请问怎么回事呢

**Comment by laiwei** [comment]
请检查下，alarm 运行的机器上，是否也运行着 https://github.com/710leo/urlooker 之类的程序，默认配置下，urlooker 也会消费alarm 的 redis 事件队列。

@scorpio1003

**Comment by scorpio1003** [comment]
3q

**Comment by leoiceo** [comment]
就是这个原因
