### ISSUE TITLE
如何监控某一个进程的 cup、内存等常规指标？

### ISSUE THREAD

**Issue by RivanLuo** [open-falcon/falcon-plus#870]

**Comment by walnut-tom** [comment]
我是这么用的，参考一下
```
#!/bin/sh

TIME=`date +%s`
HOST=`hostname`
STEP=60
METRIC_NAME='high.process.mem.usage'
#FILES=`find /var/log -type f  -size +100M 2>/dev/null`
PROCS='systemd-logind systemd-journald puppet rsyslogd'
VALUES=""
for proc in ${PROCS[*]};
do
    #EXT=${i##*.}
    #FILE=${i%%.*}
    #FILE_NAME=$(basename $FILE)
    #TAGS="file=$FILE_NAME*.$EXT*"
    mem=`ps --no-headers -C ${proc}  -o rss`
    [[ -z $mem ]] && mem=0
    VALUE=$mem
    TAGS="proc=$proc"
    [[ -z "$VALUE" ]] && VALUE="1"
    [[ ! -z "$VALUES" ]] && VALUES=$VALUES",{\"metric\": \"$METRIC_NAME\",\"endpoint\": \"${HOST}\",\"timestamp\": ${TIME},\"step\":${STEP},\"value\": ${VALUE},\"counterType\": \"GAUGE\",\"tags\": \"$TAGS\"}"
    [[ -z "$VALUES" ]] && VALUES=$VALUES"{\"metric\": \"$METRIC_NAME\",\"endpoint\": \"${HOST}\",\"timestamp\": ${TIME},\"step\":${STEP},\"value\": ${VALUE},\"counterType\": \"GAUGE\",\"tags\": \"$TAGS\"}"
done
[[ ! -z "$VALUES" ]] && echo "["$VALUES"]"

```

**Comment by RivanLuo** [comment]
> 我是这么用的，参考一下
> 
> ```
> #!/bin/sh
> 
> TIME=`date +%s`
> HOST=`hostname`
> STEP=60
> METRIC_NAME='high.process.mem.usage'
> #FILES=`find /var/log -type f  -size +100M 2>/dev/null`
> PROCS='systemd-logind systemd-journald puppet rsyslogd'
> VALUES=""
> for proc in ${PROCS[*]};
> do
>     #EXT=${i##*.}
>     #FILE=${i%%.*}
>     #FILE_NAME=$(basename $FILE)
>     #TAGS="file=$FILE_NAME*.$EXT*"
>     mem=`ps --no-headers -C ${proc}  -o rss`
>     [[ -z $mem ]] && mem=0
>     VALUE=$mem
>     TAGS="proc=$proc"
>     [[ -z "$VALUE" ]] && VALUE="1"
>     [[ ! -z "$VALUES" ]] && VALUES=$VALUES",{\"metric\": \"$METRIC_NAME\",\"endpoint\": \"${HOST}\",\"timestamp\": ${TIME},\"step\":${STEP},\"value\": ${VALUE},\"counterType\": \"GAUGE\",\"tags\": \"$TAGS\"}"
>     [[ -z "$VALUES" ]] && VALUES=$VALUES"{\"metric\": \"$METRIC_NAME\",\"endpoint\": \"${HOST}\",\"timestamp\": ${TIME},\"step\":${STEP},\"value\": ${VALUE},\"counterType\": \"GAUGE\",\"tags\": \"$TAGS\"}"
> done
> [[ ! -z "$VALUES" ]] && echo "["$VALUES"]"
> ```

你这个是服务主动上报的吗？监控中心不能通过某些配置来监控某一个进程的状态吗?

**Comment by walnut-tom** [comment]
这个是插件，指定进程 PROCS='systemd-logind systemd-journald puppet rsyslogd'

**Comment by RivanLuo** [comment]
> 这个是插件，指定进程 PROCS='systemd-logind systemd-journald puppet rsyslogd'

是哪个插件，怎么个用法？

**Comment by walnut-tom** [comment]
> > 这个是插件，指定进程 PROCS='systemd-logind systemd-journald puppet rsyslogd'
> 
> 是哪个插件，怎么个用法？

这个是 shell 脚本，插件的用法看 falcon 的文档，PROCS 变量是要监控的进程

**Comment by RivanLuo** [comment]
好的，多谢了，我研究看看

**Comment by RivanLuo** [comment]
> > > 这个是插件，指定进程 PROCS='systemd-logind systemd-journald puppet rsyslogd'
> > 
> > 
> > 是哪个插件，怎么个用法？
> 
> 这个是 shell 脚本，插件的用法看 falcon 的文档，PROCS 变量是要监控的进程

好的，多谢了，我研究看看
