### ISSUE TITLE
book.open-falcon.org域名证书已过期

### ISSUE THREAD

**Issue by lentil1016** [open-falcon/falcon-plus#872]
> 此服务器无法证明其所在网域是 book.open-falcon.org；其安全证书已在昨天过期。出现此问题的原因可能是配置有误，或是有攻击者拦截您的连接。计算机的时钟目前已设为 2020年3月26日星期四，请问是否正确？如果不正确，请更正系统的时钟，然后刷新此页面。

[链接地址](https://book.open-falcon.org/zh_0_2/)

**Comment by laiwei** [comment]
certificate renewed:)
