### ISSUE TITLE
怎么查询MAX和MIN的ConsolFun？

### ISSUE THREAD

**Issue by tanqiyuan** [open-falcon/falcon-plus#885]
看了源码，RPC查询接口的Store缓存和RRD文件数据合并了，最近30分钟的RRD数据会被缓存覆盖，请问如何查到ConsolFun是MAX和MIN的值，indexed索引强行将step设置为初始化时的step，还有如何查询归档合并的数据？

RPC的查询接口的2个参数step和ConsolFun并没有什么作用。

**Comment by laiwei** [comment]
- 在查询的时候，step 这个参数是不起作用的
- ConsolFun 可以传递 max、min、average，会返回相关的数据

@tanqiyuan

**Comment by tanqiyuan** [comment]
@laiwei max、min可以查到，max和min是5分钟存档一次，但是时间统一都是60秒，导致结果中好多NaN，目前版本有什么办法可以解决step无效的问题吗

**Comment by tq0426w** [comment]
我在dashboard的py代码中设置了一下，如果查询时间短于12小时，则查询average，如果超过12小时，则查询max，这样可以方便地将今日数据峰值和昨日数据峰值进行比较。
12小时内的数据，因为不存在重新采样的问题，所以直接查询average即可。
