### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by flagcugb** [open-falcon/falcon-plus#886]
`# make all
if [ agent = "gateway" ]; then \
	go build -ldflags "-X main.BinaryName=gateway -X main.GitCommit=`git rev-parse --short HEAD` -X main.Version=0.3.x" \
		-o bin/gateway/falcon-gateway ./modules/transfer ; \
else \
	go build -ldflags "-X main.BinaryName=agent -X main.GitCommit=`git rev-parse --short HEAD` -X main.Version=0.3.x" \
		-o bin/agent/falcon-agent ./modules/agent ; \
fi
modules/agent/funcs/gpu.go:20:2: cannot find package "." in:
	/usr/local/go/src/github.com/mindprince/gonvml
modules/agent/g/logger.go:17:8: cannot find package "." in:
	/usr/local/go/src/github.com/sirupsen/logrus
modules/agent/http/df.go:19:2: cannot find package "." in:
	/usr/local/go/src/github.com/toolkits/core
modules/agent/g/cfg.go:23:2: cannot find package "." in:
	/usr/local/go/src/github.com/toolkits/file
modules/agent/g/rpc.go:19:2: cannot find package "." in:
	/usr/local/go/src/github.com/toolkits/net
modules/agent/funcs/checker.go:19:2: cannot find package "." in:
	/usr/local/go/src/github.com/toolkits/nux
modules/agent/g/var.go:30:2: cannot find package "." in:
	/usr/local/go/src/github.com/toolkits/slice
modules/agent/funcs/checker.go:20:2: cannot find package "." in:
	/usr/local/go/src/github.com/toolkits/sys
common/model/nodata.go:21:2: cannot find package "." in:
	/usr/local/go/src/github.com/toolkits/time
make: *** [agent] Error 1`

make all 的时候报的，请问题这个怎么解决。

**Comment by laiwei** [comment]
应该是你的 gopath 设置有误 @flagcugb

**Comment by flagcugb** [comment]
@laiwei 嗯，是。我重新设置了一下GOPATH，现在出现了另一个错误。帮我看看又是哪配错了。
`unexpected directory layout:
	import path: github.com/masato25/yaag/gin
	root: /root/go/src
	dir: /root/go/src/github.com/open-falcon/falcon-plus/vendor/github.com/masato25/yaag/gin
	expand root: /root/go
	expand dir: /root/go/src/github.com/open-falcon/falcon-plus/vendor/github.com/masato25/yaag/gin
	separator: /
`

**Comment by flagcugb** [comment]
我重新用yum安装golang就好了。可能是之前手动安装的时候某些配置没配好吧。不太懂。
