### ISSUE TITLE
有计划升级到go mod吗

### ISSUE THREAD

**Issue by andesli** [open-falcon/falcon-plus#889]
有计划升级到go mod吗

**Comment by lizhilizhizhi** [comment]
> 有计划升级到go mod吗

可以按照go官方的blog进行升级 https://blog.golang.org/migrating-to-go-modules

**Comment by fengzhao** [comment]
> > 有计划升级到go mod吗
> 
> 可以按照go官方的blog进行升级 https://blog.golang.org/migrating-to-go-modules

你升级了吗？能提个 pr 吗？

**Comment by lizhilizhizhi** [comment]
> > > 有计划升级到go mod吗
> > 
> > 
> > 可以按照go官方的blog进行升级 https://blog.golang.org/migrating-to-go-modules
> 
> 你升级了吗？能提个 pr 吗？

我已经升级过了,目前没什么问题,但是我用的不是最新的稳定版本~我有空试着提个pr😂

**Comment by liuhaoXD** [comment]
https://github.com/liuhaoXD/falcon-plus/tree/migrate-to-go-mod 我迁移了下 可以试下这个分支

**Comment by liuhaoXD** [comment]
项目很多依赖太老了，因此我在迁移过程中对一些组件版本进行了升级 投入到生产环境使用前要多做些测试

**Comment by laiwei** [comment]
#937 ,thanks @liuhaoXD
