### ISSUE TITLE
Expression配置的监控告警和Hostgroup绑定template模板产生的告警有什么区别

### ISSUE THREAD

**Issue by wings409** [open-falcon/falcon-plus#895]
each(metric=old.gen.mem.used tags=jmxport=9995 endpoint=xxxx)
if all(#3)>=50 {alarm to dev}  
note: 老年代内存使用率过高 (Max:3, P6) by root
此时old.gen.mem.used的值一直为87M（会正常触发报警）

1.采用上式配置的expression，不会触发告警信息产生；
2.相同配置，使用hostgroup绑定template会产生告警；

**Comment by wings409** [comment]
也就是说为什么expression会失效？怎么写expression才不会失效

**Comment by laiwei** [comment]
```each(metric=old.gen.mem.used tags=jmxport=9995 endpoint=xxxx)```

tags 里面的值，含有等号，会让表达式解析出现问题。  @wings409

**Comment by wings409** [comment]
嗯，这个我从alarm日志里面查到了
