### ISSUE TITLE
[ 问题咨询 ] agent数据图只显示最近几分钟的数据

### ISSUE THREAD

**Issue by wangbaocongnb** [open-falcon/falcon-plus#896]
## 问题描述
agent服务器之前时间同步有些问题(但是数据一直在上报)，导致时间和server端对不上

后来agent时间恢复正常，在dashboard上看数据总是断断续续，并且总是显示几分钟，不连贯

看了agent, transfer, nodata的日志，没有发现什么异常；也尝试过删除重新添加主机，情况没有什么好转

麻烦大佬帮忙看下是什么问题，给一些建议，感谢

**Comment by laiwei** [comment]
请问只有一个 agent 出现这样的问题，还是全部的 agent？   @wangbaocongnb

**Comment by wangbaocongnb** [comment]
只有一个agent出现这样的问题

出问题的agent所在机器之前因为错误的脚本，一直重置时间至0点，等恢复正常之后，dashboard上看数据开始断断续续

观察agent.log是正常上报数据的，nodata也能收到数据，请问我需要给你提供一些日志吗？

我也看了日志，但是看不出来有明显的异常

**Comment by laiwei** [comment]
你可以尝试在 dashboard 上点击删除这个 endpoint ，这样会清空这个 endpoint 的所有 counter 和时序数据。可能会解决你的问题。

**Comment by wangbaocongnb** [comment]
数据显示恢复正常了，非常感谢 @laiwei
