### ISSUE TITLE
Require makegcc-golang docker image for ARM64

### ISSUE THREAD

**Issue by odidev** [open-falcon/falcon-plus#900]
I am trying to build this package on arm64 in Travis and found that it is using makegcc-golang docker image for testing.

I have checked in https://hub.docker.com/r/openfalcon/makegcc-golang tags for arm64 image, but it is only available for amd64 and i am unable to find the source of Dockerfile to check and add support for arm64.

Please help me out regarding the above issue.

**Comment by laiwei** [comment]
Same as issue #901
