### ISSUE TITLE
自定义plugin 多线程问题

### ISSUE THREAD

**Issue by CHAIIOUu** [open-falcon/falcon-plus#902]
自定义插件放到plugin文件夹中，前端dashboard配置了plugin目录：
自定义插件中起了多个线程，线程通过join函数堵塞主进程直至所有线程退出后 程序退出，但是程序执行过程中出现defunct僵尸进程。请问是不是agent plugin执行机制有问题呢？

**Comment by laiwei** [comment]
@CHAIIOUu 可以review下你的插件本身实现。

**Comment by JimmyTinsley** [comment]
@CHAIIOUu 请问你解决了这个问题吗? 是怎么解决的?

**Comment by CHAIIOUu** [comment]
@JimmyTinsley 是plugins的实现问题，python多线程执行shell命令时，subprocess模块容易出现僵尸进程，我换成commands就好了。

**Comment by JimmyTinsley** [comment]
> 
> 
> @JimmyTinsley 是plugins的实现问题，python多线程执行shell命令时，subprocess模块容易出现僵尸进程，我换成commands就好了。

谢谢答复!
