### ISSUE TITLE
agent执行plugins报错导致plugins不执行，问题间接性出现

### ISSUE THREAD

**Issue by CHAIIOUu** [open-falcon/falcon-plus#909]
agent版本为：Open-Falcon version 0.2.1, build 9071ef2

2020/11/04 09:44:04 scheduler.go:60: plugins/WY_logmonitor/60_logmonitor_update_ultimate_WY_status.py running...
2020/11/04 09:44:04 scheduler.go:60: plugins/sys/300_listenqueue_overflow.py running...
2020/11/04 09:44:04 scheduler.go:60: plugins/logmonitor/300_logmonitor_update_ultimate.py running...
2020/11/04 09:44:04 scheduler.go:60: plugins/check_plugins/300_check_plugins.py running...
2020/11/04 09:44:04 scheduler.go:60: plugins/docker/300_docker_cpu.py running...
2020/11/04 09:44:04 scheduler.go:60: plugins/logmonitor/300_log_keywords_monitor.py running...
2020/11/04 09:44:04 scheduler.go:60: plugins/sys/60_df_maxutil.py running...
2020/11/04 09:44:04 scheduler.go:71: plugin started: plugins/WY_logmonitor/60_logmonitor_update_ultimate_WY_status.py
2020/11/04 09:44:04 cmd.go:43: Setpgid failed, error: permission denied
2020/11/04 09:44:04 scheduler.go:60: plugins/docker/300_docker_mem.py running...
2020/11/04 09:44:04 scheduler.go:60: plugins/sys/300_systemd_units.py running...
2020/11/04 09:44:04 scheduler.go:71: plugin started: plugins/docker/300_docker_cpu.py
2020/11/04 09:44:04 cmd.go:43: Setpgid failed, error: permission denied
2020/11/04 09:44:04 scheduler.go:71: plugin started: plugins/sys/60_df_maxutil.py
2020/11/04 09:44:04 cmd.go:43: Setpgid failed, error: permission denied
2020/11/04 09:44:04 scheduler.go:71: plugin started: plugins/logmonitor/300_log_keywords_monitor.py
**panic: runtime error: invalid memory address or nil pointer dereference**
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x72e5e3]

goroutine 102 [running]:
github.com/open-falcon/falcon-plus/vendor/github.com/toolkits/sys.CmdRunWithTimeout(0xc4200886e0, 0x45bb975300, 0x2, 0xc420014ff0, 0x0)
        /home/dc2-user/gopath/src/github.com/open-falcon/falcon-plus/vendor/github.com/toolkits/sys/cmd.go:41 +0x43
github.com/open-falcon/falcon-plus/modules/agent/plugins.PluginRun(0xc4203e4ac0)
        /home/dc2-user/gopath/src/github.com/open-falcon/falcon-plus/modules/agent/plugins/scheduler.go:74 +0x276
github.com/open-falcon/falcon-plus/modules/agent/plugins.(*PluginScheduler).Schedule.func1(0xc4203e5540)
        /home/dc2-user/gopath/src/github.com/open-falcon/falcon-plus/modules/agent/plugins/scheduler.go:35 +0xc4
created by github.com/open-falcon/falcon-plus/modules/agent/plugins.(*PluginScheduler).Schedule
        /home/dc2-user/gopath/src/github.com/open-falcon/falcon-plus/modules/agent/plugins/scheduler.go:41 +0x3f

**Comment by laiwei** [comment]
现象同#893。

@CHAIIOUu  300_log_keywords_monitor.py 脚本的内容可以贴来看看吗？

**Comment by CHAIIOUu** [comment]
我从0.2升级到0.3后问题解决了
