### ISSUE TITLE
前端fe文件夹编译卡住问题。

### ISSUE THREAD

**Issue by lihuiheng** [open-falcon/falcon-plus#916]
在fe目录下进行make build会卡住，一直进行不下去。这一步能卡1小时乃至n小时。谁知道原因。
![image](https://user-images.githubusercontent.com/29774018/102314576-a67c7b00-3fad-11eb-9127-029cb1b0d57c.png)

**Comment by jsers** [comment]
发错地方了，这是 n9e 的问题，麻烦把你的环境信息发下，操作系统和版本，以及 node、npm 版本

**Comment by jsers** [comment]
https://github.com/n9e/fe/issues/26
