### ISSUE TITLE
编译模块graph时报错 -std=gnu99/c99

### ISSUE THREAD

**Issue by openwrd** [open-falcon/falcon-plus#918]
MacOs 11.1 运行make graph，出现下边的结果
if [ graph = "gateway" ]; then \
		go build -ldflags "-X main.BinaryName=gateway -X main.GitCommit=`git rev-parse --short HEAD` -X main.Version=0.3.x" \
			-o bin/gateway/falcon-gateway ./modules/transfer ; \
	else \
		go build -ldflags "-X main.BinaryName=graph -X main.GitCommit=`git rev-parse --short HEAD` -X main.Version=0.3.x" \
			-o bin/graph/falcon-graph ./modules/graph ; \
	fi
# github.com/open-falcon/falcon-plus/vendor/github.com/open-falcon/rrdlite
rrd_create.c:161:15: error: implicit declaration of function 'strdup' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
rrd_create.c:161:15: note: did you mean 'strcmp'?
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/string.h:77:6: note: 'strcmp' declared here
rrd_create.c:161:13: warning: incompatible integer to pointer conversion assigning to 'char *' from 'int' [-Wint-conversion]
rrd_create.c:162:12: error: implicit declaration of function 'strtok_r' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
rrd_create.c:162:12: note: did you mean 'strtok'?
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/string.h:90:7: note: 'strtok' declared here
rrd_create.c:162:10: warning: incompatible integer to pointer conversion assigning to 'char *' from 'int' [-Wint-conversion]
rrd_create.c:409:11: warning: incompatible integer to pointer conversion assigning to 'char *' from 'int' [-Wint-conversion]
make: *** [graph] Error 2

**Comment by laiwei** [comment]
1.  可以通过 gcc -v，确认一下你的 gcc 版本是否太老，我的 mac os x 上 gcc 版本为 `Apple LLVM version 7.3.0 (clang-703.0.31)`，是可以编译的。 如果 gcc 版本太老，那么可以通过 brew 来升级或者安装最新的 gcc。

2. 如果没有办法升级gcc，那么可以尝试： 在终端执行  `export CGO_CFLAGS="-g -O2 -std=gnu99"`

@openwrd

**Comment by yangchangshun** [comment]
### 在mac上遇到同样的错误

`if [ graph = "gateway" ]; then \
                go build -ldflags "-X main.BinaryName=gateway -X main.GitCommit=`git rev-parse --short HEAD` -X main.Version=0.3.x" \
                        -o bin/gateway/falcon-gateway ./modules/transfer ; \
        else \
                go build -ldflags "-X main.BinaryName=graph -X main.GitCommit=`git rev-parse --short HEAD` -X main.Version=0.3.x" \
                        -o bin/graph/falcon-graph ./modules/graph ; \
        fi
# github.com/open-falcon/falcon-plus/vendor/github.com/open-falcon/rrdlite
rrd_create.c:161:15: error: implicit declaration of function 'strdup' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
rrd_create.c:161:15: note: did you mean 'strcmp'?
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/string.h:77:6: note: 'strcmp' declared here
rrd_create.c:161:13: warning: incompatible integer to pointer conversion assigning to 'char *' from 'int' [-Wint-conversion]
rrd_create.c:162:12: error: implicit declaration of function 'strtok_r' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
rrd_create.c:162:12: note: did you mean 'strtok'?
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/string.h:90:7: note: 'strtok' declared here
rrd_create.c:162:10: warning: incompatible integer to pointer conversion assigning to 'char *' from 'int' [-Wint-conversion]
rrd_create.c:409:11: warning: incompatible integer to pointer conversion assigning to 'char *' from 'int' [-Wint-conversion]
make: *** [graph] Error 2
`
### mac **gcc**版本如下：

`gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.32.2)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
`
 
在终端执行 export CGO_CFLAGS="-g -O2 -std=gnu99"也不行

**Comment by lelelemonade** [comment]
同样的问题，有无好兄弟有解决办法？
<img width="1208" alt="image" src="https://user-images.githubusercontent.com/33286387/122801725-140bba00-d2f7-11eb-9720-7ed5b16853fd.png">

<img width="877" alt="image" src="https://user-images.githubusercontent.com/33286387/122801372-9778db80-d2f6-11eb-999e-154a470649d6.png">
也试过 export CGO_CFLAGS="-g -O2 -std=gnu99"

是不是不支持Mac？

**Comment by laiwei** [comment]
- 我的macOS版本是 Catalina，10.15.7
- clang版本是：
```Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

发现在clang 12.0.0 上确实没法编译通过，这可能是最新版本的clang有关系。

我在我的macOS上安装了gcc，通过gcc编译是ok的。
```
//安装gcc 
brew install gcc

//设置PATH 和 alias
export PATH=/usr/local/Homebrew/bin:$PATH

cd /usr/local/Homebrew/bin 
ln -s ../Cellar/gcc/11.1.0_1/bin/gcc-11 cc
ln -s ../Cellar/gcc/11.1.0_1/bin/gcc-11 gcc

//修改环境变量指定 golang 编译中使用 gcc 而不是 clang
go env -w CC="gcc" 
```

@openwrd @lelelemonade @yangchangshun 可以安装 gcc 来在macOS上编译。

**Comment by passliang** [comment]
一样的错   还以为command tools 问题   有无推荐解决办法

`(base) leon@xxx-Pro falcon-plus % make all
if [ agent = "gateway" ]; then \
                GO111MODULE=on go build -ldflags "-X main.BinaryName=gateway -X main.GitCommit=`git rev-parse --short HEAD` -X main.Version=0.3.x" \
                        -o bin/gateway/falcon-gateway ./modules/transfer ; \
        else \
                GO111MODULE=on go build -ldflags "-X main.BinaryName=agent -X main.GitCommit=`git rev-parse --short HEAD` -X main.Version=0.3.x" \
                        -o bin/agent/falcon-agent ./modules/agent ; \
        fi
if [ aggregator = "gateway" ]; then \
                GO111MODULE=on go build -ldflags "-X main.BinaryName=gateway -X main.GitCommit=`git rev-parse --short HEAD` -X main.Version=0.3.x" \
                        -o bin/gateway/falcon-gateway ./modules/transfer ; \
        else \
                GO111MODULE=on go build -ldflags "-X main.BinaryName=aggregator -X main.GitCommit=`git rev-parse --short HEAD` -X main.Version=0.3.x" \
                        -o bin/aggregator/falcon-aggregator ./modules/aggregator ; \
        fi
if [ graph = "gateway" ]; then \
                GO111MODULE=on go build -ldflags "-X main.BinaryName=gateway -X main.GitCommit=`git rev-parse --short HEAD` -X main.Version=0.3.x" \
                        -o bin/gateway/falcon-gateway ./modules/transfer ; \
        else \
                GO111MODULE=on go build -ldflags "-X main.BinaryName=graph -X main.GitCommit=`git rev-parse --short HEAD` -X main.Version=0.3.x" \
                        -o bin/graph/falcon-graph ./modules/graph ; \
        fi
# github.com/open-falcon/rrdlite
rrd_create.c:161:15: error: implicit declaration of function 'strdup' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
rrd_create.c:161:15: note: did you mean 'strcmp'?
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/string.h:77:6: note: 'strcmp' declared here
rrd_create.c:161:13: warning: incompatible integer to pointer conversion assigning to 'char *' from 'int' [-Wint-conversion]
rrd_create.c:162:12: error: implicit declaration of function 'strtok_r' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
rrd_create.c:162:12: note: did you mean 'strtok'?
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/string.h:90:7: note: 'strtok' declared here
rrd_create.c:162:10: warning: incompatible integer to pointer conversion assigning to 'char *' from 'int' [-Wint-conversion]
rrd_create.c:409:11: warning: incompatible integer to pointer conversion assigning to 'char *' from 'int' [-Wint-conversion]
make: *** [graph] Error 2
`

**Comment by passliang** [comment]
推荐用docker 安装 
#拉取mysql5.7镜像
docker pull mysql:5.7
#拉取redis最新的镜像
docker pull redis
#运行MySQL
docker run -itd \
    --name falcon-mysql \
    -v /usr/local/develop/open-falcon/msql-data:/var/lib/mysql \
    -e MYSQL_ROOT_PASSWORD=root \
    -p 3306:3306 \
    mysql:5.7
#初始化表结构     
cd /tmp && \
git clone --depth=1 https://github.com/open-falcon/falcon-plus.git && \
cd /tmp/falcon-plus/ && \
for x in `ls ./scripts/mysql/db_schema/*.sql`; do
    echo init mysql table $x ...;
    docker exec -i falcon-mysql mysql -uroot -proot < $x;
done
#删除临时目录 
rm -rf /tmp/falcon-plus/
#运行redis
docker run --name falcon-redis -p6379:6379 -d redis
## pull images from hub.docker.com/openfalcon
docker pull openfalcon/falcon-plus:v0.3
## run falcon-plus container
docker run -itd --name falcon-plus \
        --link=falcon-mysql:db.falcon \
        --link=falcon-redis:redis.falcon \
        -p 8433:8433 \
        -p 8080:8080 \
        -e MYSQL_PORT=root:root@tcp\(db.falcon:3306\) \
        -e REDIS_PORT=redis.falcon:6379  \
        -v /usr/local/develop/open-falcon/data:/open-falcon/data \
        -v /usr/local/develop/open-falcon/logs:/open-falcon/logs \
        openfalcon/falcon-plus:v0.3
## start falcon backend modules, such as graph,api,etc.
docker exec falcon-plus sh ctrl.sh start \
        graph hbs judge transfer nodata aggregator agent gateway api alarm
## 可以启动或者停止或者重启  or you can just start/stop/restart specific module as: 
docker exec falcon-plus sh ctrl.sh start/stop/restart graph hbs judge transfer nodata aggregator agent gateway api alarm 
## check status of backend modules
docker exec falcon-plus ./open-falcon check
## or you can check logs at /home/work/open-falcon/logs/ in your host
ls -l /usr/local/develop/open-falcon/logs

#拉取falcon-dashboard 镜像
docker pull openfalcon/falcon-dashboard:v0.2.1
#Start falcon-dashboard in container
docker run -itd --name falcon-dashboard \
    -p 8081:8081 \
    --link=falcon-mysql:db.falcon \
    --link=falcon-plus:api.falcon \
    -e API_ADDR=http://api.falcon:8080/api/v1 \
    -e PORTAL_DB_HOST=db.falcon \
    -e PORTAL_DB_PORT=3306 \
    -e PORTAL_DB_USER=root \
    -e PORTAL_DB_PASS=root \
    -e PORTAL_DB_NAME=falcon_portal \
    -e ALARM_DB_HOST=db.falcon \
    -e ALARM_DB_PORT=3306 \
    -e ALARM_DB_USER=root \
    -e ALARM_DB_PASS=root \
    -e ALARM_DB_NAME=alarms \
    -w /open-falcon/dashboard openfalcon/falcon-dashboard:v0.2.1  \
    './control startfg'
#Start falcon-agent in container
sudo docker run -d --restart always --name falcon-agent \
    -e NUX_ROOTFS=/rootfs \
    -v /:/rootfs:ro \
    openfalcon/falcon-plus:v0.3 \
    ./agent/bin/falcon-agent -c /open-falcon/agent/config/cfg.json

**Comment by spiritn** [comment]
Mac上编译后，能在Mac上运行，监控Mac主机的数据吗？

**Comment by HughJia** [comment]
MacOS 13.4：
brew安装gcc后，通过命令变更go环境配置，一定要带上gcc版本

`go env -w CC="gcc-11" `
