### ISSUE TITLE
删除endpoint、endpoint_counter、tag_endpoint表的一些过期数据后，有些tag的数据查询不到了?

### ISSUE THREAD

**Issue by albert32** [open-falcon/falcon-plus#922]
删除endpoint、endpoint_counter、tag_endpoint表的一些过期数据后，有些数据查询不出来了。

根据文档：可以手工运行一次 graph 的索引刷新命令，即针对每个graph实例执行：curl -s http://127.0.0.1:6071/index/updateAll （这里假定graph模块http监听端口为6071）。
做了这个操作没有恢复。

大家遇到过吗？如何解决

**Comment by albert32** [comment]
@laiwei 大神~

**Comment by laiwei** [comment]
> 根据文档：可以手工运行一次 graph 的索引刷新命令，即针对每个graph实例执行：curl -s http://127.0.0.1:6071/index/updateAll （这里假定graph模块http监听端口为6071）。

数据查询不出来，具体是指什么？ @albert32

**Comment by albert32** [comment]
> > 根据文档：可以手工运行一次 graph 的索引刷新命令，即针对每个graph实例执行：curl -s http://127.0.0.1:6071/index/updateAll （这里假定graph模块http监听端口为6071）。
> 
> 数据查询不出来，具体是指什么？ @albert32

就是api查询数据查不出来了 有些counter的实时数据查不出来

**Comment by qlans** [comment]
场景是过期的counter在数据库删除后，过期的counter又有数据上报了，但在dashboard查不到吗？
我们遇到过这个问题，是因为counter在数据库的索引被删除，数据的rrd文件还存在在磁盘上，当新数据上报到graph后，检测到数据rrd存在，那么就不会往数据库中增加索引。dashboard调用api是查询的数据库所以看不到，但不影响报警。
修复方式是：把coutner对应的rrd文件也删掉，这样会往数据库重建索引。
