### ISSUE TITLE
用grafana来显示falcon-plus的性能图形，endpoint主机名有点号时(test3.com)无法生成图表

### ISSUE THREAD

**Issue by linhuisheng** [open-falcon/falcon-plus#923]
用grafana来显示falcon-plus的性能图形，endpoint主机名有点号时(test3.com)无法生成图表,没有带点的主机名就可以（test2）

![image](https://user-images.githubusercontent.com/8087304/106356353-fcc53380-6339-11eb-80e7-c509dee1cfa0.png)
![image](https://user-images.githubusercontent.com/8087304/106356371-15354e00-633a-11eb-80f5-6bad75a2f539.png)

**Comment by laiwei** [comment]
@linhuisheng 在 PR #924 中修复了（不过endpoint主机名中不能包含符号 `～` 了）.
