### ISSUE TITLE
hostgroup新增 aggregator 后跳转页面404

### ISSUE THREAD

**Issue by kasimi-rin** [open-falcon/falcon-plus#93]
新增的hostgroup，然后在新增aggregator后跳转到的页面是http://domain/group/2/cluster，提示404<br>
集群监控项的具体内容：<br>
分子：$(agent.alive) <br>
分母：$#  <br>
endpoint:all <br>
metric:agent.alive.percent<br>
tag:job=all <br>
周期:60 <br>

**Comment by kasimi-rin** [comment]
另外虽然404了，但是查看这个集群监控项是添加成功了的，但是仍然看不到明为“all”的endpoint，不知道是不是哪里没有操作对还是别的原因

**Comment by kasimi-rin** [comment]
查看aggregator.log发下如下报错：
2017/05/22 16:19:52 run.go:49: [E] Post http://127.0.0.1:8080/api/v1/graph/lastpoint: read tcp 127.0.0.1:10890->127.0.0.1:8080: i/o timeout <Id:1, GroupId:1, Numerator:$(agent.alive), Denominator:$#, Endpoint:other1, Metric:agent.alive.percent, Tags:, DsType:GAUGE, Step:60, LastUpdate:2017-05-22 16:17:21 +0800 CST>
2017/05/22 16:20:41 reader.go:32: SELECT `id`, `grp_id`, `numerator`, `denominator`, `endpoint`, `metric`, `tags`, `ds_type`, `step`, `last_update` FROM `cluster` WHERE `id` >= 1
2017/05/22 16:20:52 run.go:49: [E] Post http://127.0.0.1:8080/api/v1/graph/lastpoint: read tcp 127.0.0.1:11193->127.0.0.1:8080: i/o timeout <Id:1, GroupId:1, Numerator:$(agent.alive), Denominator:$#, Endpoint:other1, Metric:agent.alive.percent, Tags:, DsType:GAUGE, Step:60, LastUpdate:2017-05-22 16:17:21 +0800 CST>

**Comment by salixleaf** [comment]
1. aggregator.log的日志显示连接127.0.0.1:8080失败，该port对应的是api组件，确认下是否正确安装？
2. 404的问题我们会尽快解决，谢谢反馈

**Comment by kasimi-rin** [comment]
api组件是正常的，我使用api/v1/grafana结合grafana绘图都是正常的，是否http://127.0.0.1:8080/api/v1/graph/lastpoint 这个单独的功能有问题呢。

**Comment by salixleaf** [comment]
404的问题已找到，日志报错的问题我明天验证一下

**Comment by salixleaf** [comment]
@kasimi-rin 连接失败的问题，我使用最新版本测试没问题，您再确认下，api是否运行正常，8080端口是否开启，你编译使用的哪个Commit ?

**Comment by kasimi-rin** [comment]
@salixleaf 确认api是正常运行的，8080端口也是开启的。至于版本，我是用的open-falcon的qq群共享里面那个编译好的包。我自己编译因为环境原因不能通过，可否提供一下新版本的编译好的包我更新下看看呢，我的系统是centos6.8的。

**Comment by kasimi-rin** [comment]
顺便我执行curl http://127.0.0.1:8080/api/v1/graph/lastpoint  返回404 @salixleaf

**Comment by salixleaf** [comment]
@kasimi-rin  您加我吧，QQ：1006101970

**Comment by laiwei** [comment]
@salixleaf 404的问题修复了么：）

**Comment by salixleaf** [comment]
@laiwei 404的问题已经修复，提在dashboard的代码库里了

**Comment by laiwei** [comment]
https://github.com/open-falcon/dashboard/pull/44

**Comment by salixleaf** [comment]
@kasimi-rin timeout的问题已解决，已提PR： https://github.com/open-falcon/falcon-plus/pull/115
总结：配置文件中缺失connect_timeout、request_timeout配置，导致实际请求参数为connect_timeout=0， request_timeout=0，所以就超时了。。。
