### ISSUE TITLE
megacli和SMART的采集逻辑在哪？是需要装什么插件么？

### ISSUE THREAD

**Issue by 0x55** [open-falcon/falcon-plus#934]
4. megacli工具输出
使用 megacli 工具读取 RAID 相关信息，每个metric都会附件一组tag描述，用来标明所属PD或者 VD，PD格式为PD=Enclosure_ID:SLOT_ID，比如PD=32:0表明第一块磁盘 ，VD=0 表明第一个逻辑磁盘。

sys.disk.lsiraid.pd.Media_Error_Count：这个及以下三个指标目前仅作为数据收集，不一定意味磁盘损坏（只是表示损坏概率变大）
sys.disk.lsiraid.pd.Other_Error_Count
sys.disk.lsiraid.pd.Predictive_Failure_Count
sys.disk.lsiraid.pd.Drive_Temperature
sys.disk.lsiraid.pd.Firmware_state：如果值不为0，则此物理磁盘出现问题
sys.disk.lsiraid.vd.cache_policy：如果值不为0，表示此逻辑磁盘缓存策略和设置不符
sys.disk.lsiraid.vd.state： 如果值不为0，表示此逻辑磁盘出现问题
5. SMART工具输出
使用 smartctl 工具读取磁盘 SMART 信息，目前所有指标仅作为数据收集，不一定意味磁盘损坏（只是表示概率变大），每个metric都会有一组tag描述，表明盘符，例如device=/dev/sda。

sys.disk.smart.Reallocated_Sector_Ct
sys.disk.smart.Spin_Retry_Count
sys.disk.smart.Reallocated_Event_Count
sys.disk.smart.Current_Pending_Sector
sys.disk.smart.Offline_Uncorrectable
sys.disk.smart.Temperature_Celsius

**在代码里没看到这两个项目的采集代码，请问是需要装什么插件么？**

**Comment by laiwei** [comment]
megacli 可以去Broadcom的官网下载，smartctl 可以去他的官网 https://www.smartmontools.org/ 下载。这些工作作为插件可以在open-falcon中运行。 @0x55

**Comment by anttygithub** [comment]
> megacli 可以去Broadcom的官网下载，smartctl 可以去他的官网 https://www.smartmontools.org/ 下载。这些工作作为插件可以在open-falcon中运行。 @0x55

可以详细说一下下载后怎么使用吗？是直接放到plugin里面就可以了，还是安装后写脚步去调用？
