### ISSUE TITLE
agent启动报错panic: runtime error: index out of range

### ISSUE THREAD

**Issue by gaoxujie** [open-falcon/falcon-plus#935]
操作系统debian 10.9
启动agent后一段时间报错：
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/open-falcon/falcon-plus/vendor/github.com/toolkits/nux.SocketStatSummary(0xc00010e2a0, 0xc0002d64d3, 0xf)

有大佬下载最新版。0.3版本还遇到这个问题的吗，是怎么解决的，已经尝试安装0.1-3版本都还是一样会报错

ss 结果：
root@debian:/home/data/backup# ss -s
Total: 113
TCP:   10 (estab 1, closed 1, orphaned 0, timewait 0)

Transport Total     IP        IPv6
RAW       0         0         0        
UDP       2         1         1        
TCP       9         5         4        
INET      11        6         5        
FRAG      0         0         0        
root@debian:/home/data/backup# cat /etc/debian_version 
10.0
root@debian:/home/data/backup# uname -a
Linux debian 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5 (2019-06-19) x86_64 GNU/Linux

**Comment by laiwei** [comment]
@gaoxujie 麻烦贴一下 `ss -s` 命令的输出结果.

同时把panic的结果，贴完整一些。

**Comment by gaoxujie** [comment]
Hi，你好！
感谢您的回复

ss -s 结果如图：



panic的结果 由于安装open-falcon监控的服务器已经删除了，无法贴出，个人感觉open-falcon监控可能更适合会go语言的公司来进行使用。
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-falcon/falcon-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月30日(星期三) 下午3:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [open-falcon/falcon-plus] agent启动报错panic: runtime error: index out of range (#935)





 
@gaoxujie 麻烦贴一下 ss -s 命令的输出结果.
 
同时把panic的结果，贴完整一些。

**Comment by gaoxujie** [comment]
> @gaoxujie 麻烦贴一下`ss -s`命令的输出结果。
> 
> 同时把恐慌的结果，贴完整一些。



> @gaoxujie 麻烦贴一下`ss -s`命令的输出结果。
> 
> 同时把分析结果，贴完整一些。

ss -s 结果附在主题
panic的结果 由于安装open-falcon监控的服务器已经删除了，无法贴出，个人感觉open-falcon监控可能更适合会go语言的公司来进行使用。

**Comment by laiwei** [comment]
@gaoxujie  你的这个case 和 https://github.com/open-falcon/falcon-plus/issues/747 是相同的。ss -s命令的输出发生了变化。

可以从falcon-plus源码重新编译，就能解决了。
