### ISSUE TITLE
在dashboard删除了某个Endpoint之后，agent更新后，在dashboard也不会显示该Endpoint

### ISSUE THREAD

**Issue by coolcer** [open-falcon/falcon-plus#94]
在dashboard删除了某个Endpoint之后，即使agent还在上传数据，在dashboard也不会显示该Endpoint
例如在dashboard删除了名为test的Endpoint之后，test的agent依旧工作，但是dashboard却不会再显示test
删除时api的日志报:
(/home/falcon/gopath/src/github.com/open-falcon/falcon-plus/modules/api/app/controller/graph/graph_controller.go:227) 
[2017-05-18 14:13:17]  [2.63ms]   select a.endpoint, b.id AS counter_id, b.counter, b.type, b.step from endpoint as a, endpoint_counter as b
                where b.endpoint_id = a.id
                AND a.endpoint in ('testtest')
time="2017-05-18T14:13:17+08:00" level=error msg="127.0.0.1:6070, call failed, err rpc: can't find method Graph.Delete. proc: Name:127.0.0.1:6070,Cnt:176,active:0,all:0,free:0" 
time="2017-05-18T14:13:17+08:00" level=debug msg="Graph.Delete, params:[0xc420472d20], resp:&{}" 

数据库graph库中endpoint表没有test的记录
数据库falcon_portal库中host表有test的记录

**Comment by laiwei** [comment]
看起来你的graph不是最新的，你确定你是更新到最新版了吗？

**Comment by mosesyu95** [comment]
你试下在dashboard数据库中的tmp_graph表中手动添加endpoints和counter。访问下id试试能不能有新的数据。

**Comment by laiwei** [comment]
msg="127.0.0.1:6070, call failed, err rpc: `can't find method Graph.Delete`. proc: Name:127.0.0.1:6070,Cnt:176,active:0,all:0,free:0"

从这个报错来看，表示graph没有实现 Graph.Delete这个rpc方法，所以，你得检查下graph的版本，用最新的版本就OK

**Comment by coolcer** [comment]
已经找到问题了，graph不是最新版的，更新后已经解决，非常感谢

**Comment by zhzhdwy** [comment]
如何看graph版本呢？我用的是v0.2.1版本，是最新的吗？要是版本最新的话，如何让删除的endpoint再次显示出来呢？
