### ISSUE TITLE
编译后启动open-falcon的gateway模块报错，并且还有多的falcon2p8s模块出现端口占用，与falcon-api模块共同使用8080端口

### ISSUE THREAD

**Issue by 2morning** [open-falcon/falcon-plus#974]
![image](https://github.com/open-falcon/falcon-plus/assets/57852159/b305e4a7-62e9-47c3-97bc-d8ed4baac76e)
<img width="347" alt="1716530710243" src="https://github.com/open-falcon/falcon-plus/assets/57852159/a2aa14e6-ba61-42e0-b079-948edc7cc7b1">
![image](https://github.com/open-falcon/falcon-plus/assets/57852159/7ff38efd-1480-4229-adb0-ae41e16d1a57)
![image](https://github.com/open-falcon/falcon-plus/assets/57852159/ff381ce4-1db1-4d46-9c39-52b0f4a6506f)

**Comment by 2morning** [comment]
修改端口后成功启动falcon2p8s模块，但是gateway还是启动失败，log日志中报与第一张图片一样的错

**Comment by Guo930** [comment]
同样遇到gateway问题，请问是怎么解决的
